//go:build !enthistorycodegen

// Code generated by ent, DO NOT EDIT.

package organizationhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/theopenlane/core/internal/ent/historygenerated/predicate"
	"github.com/theopenlane/entx/history"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldID, id))
}

// HistoryTime applies equality check predicate on the "history_time" field. It's identical to HistoryTimeEQ.
func HistoryTime(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldHistoryTime, v))
}

// Ref applies equality check predicate on the "ref" field. It's identical to RefEQ.
func Ref(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldRef, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldDeletedBy, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldName, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldDisplayName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldDescription, v))
}

// ParentOrganizationID applies equality check predicate on the "parent_organization_id" field. It's identical to ParentOrganizationIDEQ.
func ParentOrganizationID(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldParentOrganizationID, v))
}

// PersonalOrg applies equality check predicate on the "personal_org" field. It's identical to PersonalOrgEQ.
func PersonalOrg(v bool) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldPersonalOrg, v))
}

// AvatarRemoteURL applies equality check predicate on the "avatar_remote_url" field. It's identical to AvatarRemoteURLEQ.
func AvatarRemoteURL(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldAvatarRemoteURL, v))
}

// AvatarLocalFileID applies equality check predicate on the "avatar_local_file_id" field. It's identical to AvatarLocalFileIDEQ.
func AvatarLocalFileID(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldAvatarLocalFileID, v))
}

// AvatarUpdatedAt applies equality check predicate on the "avatar_updated_at" field. It's identical to AvatarUpdatedAtEQ.
func AvatarUpdatedAt(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldAvatarUpdatedAt, v))
}

// DedicatedDb applies equality check predicate on the "dedicated_db" field. It's identical to DedicatedDbEQ.
func DedicatedDb(v bool) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldDedicatedDb, v))
}

// StripeCustomerID applies equality check predicate on the "stripe_customer_id" field. It's identical to StripeCustomerIDEQ.
func StripeCustomerID(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldStripeCustomerID, v))
}

// HistoryTimeEQ applies the EQ predicate on the "history_time" field.
func HistoryTimeEQ(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldHistoryTime, v))
}

// HistoryTimeNEQ applies the NEQ predicate on the "history_time" field.
func HistoryTimeNEQ(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldHistoryTime, v))
}

// HistoryTimeIn applies the In predicate on the "history_time" field.
func HistoryTimeIn(vs ...time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldHistoryTime, vs...))
}

// HistoryTimeNotIn applies the NotIn predicate on the "history_time" field.
func HistoryTimeNotIn(vs ...time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldHistoryTime, vs...))
}

// HistoryTimeGT applies the GT predicate on the "history_time" field.
func HistoryTimeGT(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldHistoryTime, v))
}

// HistoryTimeGTE applies the GTE predicate on the "history_time" field.
func HistoryTimeGTE(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldHistoryTime, v))
}

// HistoryTimeLT applies the LT predicate on the "history_time" field.
func HistoryTimeLT(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldHistoryTime, v))
}

// HistoryTimeLTE applies the LTE predicate on the "history_time" field.
func HistoryTimeLTE(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldHistoryTime, v))
}

// RefEQ applies the EQ predicate on the "ref" field.
func RefEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldRef, v))
}

// RefNEQ applies the NEQ predicate on the "ref" field.
func RefNEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldRef, v))
}

// RefIn applies the In predicate on the "ref" field.
func RefIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldRef, vs...))
}

// RefNotIn applies the NotIn predicate on the "ref" field.
func RefNotIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldRef, vs...))
}

// RefGT applies the GT predicate on the "ref" field.
func RefGT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldRef, v))
}

// RefGTE applies the GTE predicate on the "ref" field.
func RefGTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldRef, v))
}

// RefLT applies the LT predicate on the "ref" field.
func RefLT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldRef, v))
}

// RefLTE applies the LTE predicate on the "ref" field.
func RefLTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldRef, v))
}

// RefContains applies the Contains predicate on the "ref" field.
func RefContains(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContains(FieldRef, v))
}

// RefHasPrefix applies the HasPrefix predicate on the "ref" field.
func RefHasPrefix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasPrefix(FieldRef, v))
}

// RefHasSuffix applies the HasSuffix predicate on the "ref" field.
func RefHasSuffix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasSuffix(FieldRef, v))
}

// RefIsNil applies the IsNil predicate on the "ref" field.
func RefIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldRef))
}

// RefNotNil applies the NotNil predicate on the "ref" field.
func RefNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldRef))
}

// RefEqualFold applies the EqualFold predicate on the "ref" field.
func RefEqualFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldRef, v))
}

// RefContainsFold applies the ContainsFold predicate on the "ref" field.
func RefContainsFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldRef, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v history.OpType) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v history.OpType) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...history.OpType) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...history.OpType) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldOperation, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldUpdatedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldDeletedAt))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByContains applies the Contains predicate on the "deleted_by" field.
func DeletedByContains(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContains(FieldDeletedBy, v))
}

// DeletedByHasPrefix applies the HasPrefix predicate on the "deleted_by" field.
func DeletedByHasPrefix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasPrefix(FieldDeletedBy, v))
}

// DeletedByHasSuffix applies the HasSuffix predicate on the "deleted_by" field.
func DeletedByHasSuffix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasSuffix(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldDeletedBy))
}

// DeletedByEqualFold applies the EqualFold predicate on the "deleted_by" field.
func DeletedByEqualFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldDeletedBy, v))
}

// DeletedByContainsFold applies the ContainsFold predicate on the "deleted_by" field.
func DeletedByContainsFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldDeletedBy, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldTags))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldName, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldDisplayName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldDescription, v))
}

// ParentOrganizationIDEQ applies the EQ predicate on the "parent_organization_id" field.
func ParentOrganizationIDEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldParentOrganizationID, v))
}

// ParentOrganizationIDNEQ applies the NEQ predicate on the "parent_organization_id" field.
func ParentOrganizationIDNEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldParentOrganizationID, v))
}

// ParentOrganizationIDIn applies the In predicate on the "parent_organization_id" field.
func ParentOrganizationIDIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldParentOrganizationID, vs...))
}

// ParentOrganizationIDNotIn applies the NotIn predicate on the "parent_organization_id" field.
func ParentOrganizationIDNotIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldParentOrganizationID, vs...))
}

// ParentOrganizationIDGT applies the GT predicate on the "parent_organization_id" field.
func ParentOrganizationIDGT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldParentOrganizationID, v))
}

// ParentOrganizationIDGTE applies the GTE predicate on the "parent_organization_id" field.
func ParentOrganizationIDGTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldParentOrganizationID, v))
}

// ParentOrganizationIDLT applies the LT predicate on the "parent_organization_id" field.
func ParentOrganizationIDLT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldParentOrganizationID, v))
}

// ParentOrganizationIDLTE applies the LTE predicate on the "parent_organization_id" field.
func ParentOrganizationIDLTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldParentOrganizationID, v))
}

// ParentOrganizationIDContains applies the Contains predicate on the "parent_organization_id" field.
func ParentOrganizationIDContains(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContains(FieldParentOrganizationID, v))
}

// ParentOrganizationIDHasPrefix applies the HasPrefix predicate on the "parent_organization_id" field.
func ParentOrganizationIDHasPrefix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasPrefix(FieldParentOrganizationID, v))
}

// ParentOrganizationIDHasSuffix applies the HasSuffix predicate on the "parent_organization_id" field.
func ParentOrganizationIDHasSuffix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasSuffix(FieldParentOrganizationID, v))
}

// ParentOrganizationIDIsNil applies the IsNil predicate on the "parent_organization_id" field.
func ParentOrganizationIDIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldParentOrganizationID))
}

// ParentOrganizationIDNotNil applies the NotNil predicate on the "parent_organization_id" field.
func ParentOrganizationIDNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldParentOrganizationID))
}

// ParentOrganizationIDEqualFold applies the EqualFold predicate on the "parent_organization_id" field.
func ParentOrganizationIDEqualFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldParentOrganizationID, v))
}

// ParentOrganizationIDContainsFold applies the ContainsFold predicate on the "parent_organization_id" field.
func ParentOrganizationIDContainsFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldParentOrganizationID, v))
}

// PersonalOrgEQ applies the EQ predicate on the "personal_org" field.
func PersonalOrgEQ(v bool) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldPersonalOrg, v))
}

// PersonalOrgNEQ applies the NEQ predicate on the "personal_org" field.
func PersonalOrgNEQ(v bool) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldPersonalOrg, v))
}

// PersonalOrgIsNil applies the IsNil predicate on the "personal_org" field.
func PersonalOrgIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldPersonalOrg))
}

// PersonalOrgNotNil applies the NotNil predicate on the "personal_org" field.
func PersonalOrgNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldPersonalOrg))
}

// AvatarRemoteURLEQ applies the EQ predicate on the "avatar_remote_url" field.
func AvatarRemoteURLEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldAvatarRemoteURL, v))
}

// AvatarRemoteURLNEQ applies the NEQ predicate on the "avatar_remote_url" field.
func AvatarRemoteURLNEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldAvatarRemoteURL, v))
}

// AvatarRemoteURLIn applies the In predicate on the "avatar_remote_url" field.
func AvatarRemoteURLIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldAvatarRemoteURL, vs...))
}

// AvatarRemoteURLNotIn applies the NotIn predicate on the "avatar_remote_url" field.
func AvatarRemoteURLNotIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldAvatarRemoteURL, vs...))
}

// AvatarRemoteURLGT applies the GT predicate on the "avatar_remote_url" field.
func AvatarRemoteURLGT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldAvatarRemoteURL, v))
}

// AvatarRemoteURLGTE applies the GTE predicate on the "avatar_remote_url" field.
func AvatarRemoteURLGTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldAvatarRemoteURL, v))
}

// AvatarRemoteURLLT applies the LT predicate on the "avatar_remote_url" field.
func AvatarRemoteURLLT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldAvatarRemoteURL, v))
}

// AvatarRemoteURLLTE applies the LTE predicate on the "avatar_remote_url" field.
func AvatarRemoteURLLTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldAvatarRemoteURL, v))
}

// AvatarRemoteURLContains applies the Contains predicate on the "avatar_remote_url" field.
func AvatarRemoteURLContains(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContains(FieldAvatarRemoteURL, v))
}

// AvatarRemoteURLHasPrefix applies the HasPrefix predicate on the "avatar_remote_url" field.
func AvatarRemoteURLHasPrefix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasPrefix(FieldAvatarRemoteURL, v))
}

// AvatarRemoteURLHasSuffix applies the HasSuffix predicate on the "avatar_remote_url" field.
func AvatarRemoteURLHasSuffix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasSuffix(FieldAvatarRemoteURL, v))
}

// AvatarRemoteURLIsNil applies the IsNil predicate on the "avatar_remote_url" field.
func AvatarRemoteURLIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldAvatarRemoteURL))
}

// AvatarRemoteURLNotNil applies the NotNil predicate on the "avatar_remote_url" field.
func AvatarRemoteURLNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldAvatarRemoteURL))
}

// AvatarRemoteURLEqualFold applies the EqualFold predicate on the "avatar_remote_url" field.
func AvatarRemoteURLEqualFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldAvatarRemoteURL, v))
}

// AvatarRemoteURLContainsFold applies the ContainsFold predicate on the "avatar_remote_url" field.
func AvatarRemoteURLContainsFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldAvatarRemoteURL, v))
}

// AvatarLocalFileIDEQ applies the EQ predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldAvatarLocalFileID, v))
}

// AvatarLocalFileIDNEQ applies the NEQ predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDNEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldAvatarLocalFileID, v))
}

// AvatarLocalFileIDIn applies the In predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldAvatarLocalFileID, vs...))
}

// AvatarLocalFileIDNotIn applies the NotIn predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDNotIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldAvatarLocalFileID, vs...))
}

// AvatarLocalFileIDGT applies the GT predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDGT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldAvatarLocalFileID, v))
}

// AvatarLocalFileIDGTE applies the GTE predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDGTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldAvatarLocalFileID, v))
}

// AvatarLocalFileIDLT applies the LT predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDLT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldAvatarLocalFileID, v))
}

// AvatarLocalFileIDLTE applies the LTE predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDLTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldAvatarLocalFileID, v))
}

// AvatarLocalFileIDContains applies the Contains predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDContains(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContains(FieldAvatarLocalFileID, v))
}

// AvatarLocalFileIDHasPrefix applies the HasPrefix predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDHasPrefix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasPrefix(FieldAvatarLocalFileID, v))
}

// AvatarLocalFileIDHasSuffix applies the HasSuffix predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDHasSuffix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasSuffix(FieldAvatarLocalFileID, v))
}

// AvatarLocalFileIDIsNil applies the IsNil predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldAvatarLocalFileID))
}

// AvatarLocalFileIDNotNil applies the NotNil predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldAvatarLocalFileID))
}

// AvatarLocalFileIDEqualFold applies the EqualFold predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDEqualFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldAvatarLocalFileID, v))
}

// AvatarLocalFileIDContainsFold applies the ContainsFold predicate on the "avatar_local_file_id" field.
func AvatarLocalFileIDContainsFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldAvatarLocalFileID, v))
}

// AvatarUpdatedAtEQ applies the EQ predicate on the "avatar_updated_at" field.
func AvatarUpdatedAtEQ(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldAvatarUpdatedAt, v))
}

// AvatarUpdatedAtNEQ applies the NEQ predicate on the "avatar_updated_at" field.
func AvatarUpdatedAtNEQ(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldAvatarUpdatedAt, v))
}

// AvatarUpdatedAtIn applies the In predicate on the "avatar_updated_at" field.
func AvatarUpdatedAtIn(vs ...time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldAvatarUpdatedAt, vs...))
}

// AvatarUpdatedAtNotIn applies the NotIn predicate on the "avatar_updated_at" field.
func AvatarUpdatedAtNotIn(vs ...time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldAvatarUpdatedAt, vs...))
}

// AvatarUpdatedAtGT applies the GT predicate on the "avatar_updated_at" field.
func AvatarUpdatedAtGT(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldAvatarUpdatedAt, v))
}

// AvatarUpdatedAtGTE applies the GTE predicate on the "avatar_updated_at" field.
func AvatarUpdatedAtGTE(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldAvatarUpdatedAt, v))
}

// AvatarUpdatedAtLT applies the LT predicate on the "avatar_updated_at" field.
func AvatarUpdatedAtLT(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldAvatarUpdatedAt, v))
}

// AvatarUpdatedAtLTE applies the LTE predicate on the "avatar_updated_at" field.
func AvatarUpdatedAtLTE(v time.Time) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldAvatarUpdatedAt, v))
}

// AvatarUpdatedAtIsNil applies the IsNil predicate on the "avatar_updated_at" field.
func AvatarUpdatedAtIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldAvatarUpdatedAt))
}

// AvatarUpdatedAtNotNil applies the NotNil predicate on the "avatar_updated_at" field.
func AvatarUpdatedAtNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldAvatarUpdatedAt))
}

// DedicatedDbEQ applies the EQ predicate on the "dedicated_db" field.
func DedicatedDbEQ(v bool) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldDedicatedDb, v))
}

// DedicatedDbNEQ applies the NEQ predicate on the "dedicated_db" field.
func DedicatedDbNEQ(v bool) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldDedicatedDb, v))
}

// StripeCustomerIDEQ applies the EQ predicate on the "stripe_customer_id" field.
func StripeCustomerIDEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEQ(FieldStripeCustomerID, v))
}

// StripeCustomerIDNEQ applies the NEQ predicate on the "stripe_customer_id" field.
func StripeCustomerIDNEQ(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNEQ(FieldStripeCustomerID, v))
}

// StripeCustomerIDIn applies the In predicate on the "stripe_customer_id" field.
func StripeCustomerIDIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIn(FieldStripeCustomerID, vs...))
}

// StripeCustomerIDNotIn applies the NotIn predicate on the "stripe_customer_id" field.
func StripeCustomerIDNotIn(vs ...string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotIn(FieldStripeCustomerID, vs...))
}

// StripeCustomerIDGT applies the GT predicate on the "stripe_customer_id" field.
func StripeCustomerIDGT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGT(FieldStripeCustomerID, v))
}

// StripeCustomerIDGTE applies the GTE predicate on the "stripe_customer_id" field.
func StripeCustomerIDGTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldGTE(FieldStripeCustomerID, v))
}

// StripeCustomerIDLT applies the LT predicate on the "stripe_customer_id" field.
func StripeCustomerIDLT(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLT(FieldStripeCustomerID, v))
}

// StripeCustomerIDLTE applies the LTE predicate on the "stripe_customer_id" field.
func StripeCustomerIDLTE(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldLTE(FieldStripeCustomerID, v))
}

// StripeCustomerIDContains applies the Contains predicate on the "stripe_customer_id" field.
func StripeCustomerIDContains(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContains(FieldStripeCustomerID, v))
}

// StripeCustomerIDHasPrefix applies the HasPrefix predicate on the "stripe_customer_id" field.
func StripeCustomerIDHasPrefix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasPrefix(FieldStripeCustomerID, v))
}

// StripeCustomerIDHasSuffix applies the HasSuffix predicate on the "stripe_customer_id" field.
func StripeCustomerIDHasSuffix(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldHasSuffix(FieldStripeCustomerID, v))
}

// StripeCustomerIDIsNil applies the IsNil predicate on the "stripe_customer_id" field.
func StripeCustomerIDIsNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldIsNull(FieldStripeCustomerID))
}

// StripeCustomerIDNotNil applies the NotNil predicate on the "stripe_customer_id" field.
func StripeCustomerIDNotNil() predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldNotNull(FieldStripeCustomerID))
}

// StripeCustomerIDEqualFold applies the EqualFold predicate on the "stripe_customer_id" field.
func StripeCustomerIDEqualFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldEqualFold(FieldStripeCustomerID, v))
}

// StripeCustomerIDContainsFold applies the ContainsFold predicate on the "stripe_customer_id" field.
func StripeCustomerIDContainsFold(v string) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.FieldContainsFold(FieldStripeCustomerID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrganizationHistory) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrganizationHistory) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrganizationHistory) predicate.OrganizationHistory {
	return predicate.OrganizationHistory(sql.NotPredicates(p))
}
