-- Create "control_action_plans" table
CREATE TABLE "control_action_plans" ("control_id" character varying NOT NULL, "action_plan_id" character varying NOT NULL, PRIMARY KEY ("control_id", "action_plan_id"), CONSTRAINT "control_action_plans_action_plan_id" FOREIGN KEY ("action_plan_id") REFERENCES "action_plans" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "control_action_plans_control_id" FOREIGN KEY ("control_id") REFERENCES "controls" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Modify "control_objectives" table
ALTER TABLE "control_objectives" DROP CONSTRAINT "control_objectives_organizations_controlobjectives", DROP COLUMN "control_controlobjectives", ADD COLUMN "control_control_objectives" character varying NULL, ADD CONSTRAINT "control_objectives_controls_control_objectives" FOREIGN KEY ("control_control_objectives") REFERENCES "controls" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "control_objectives_organizations_control_objectives" FOREIGN KEY ("owner_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "document_data" table
ALTER TABLE "document_data" DROP CONSTRAINT "document_data_organizations_documentdata", ADD CONSTRAINT "document_data_organizations_document_data" FOREIGN KEY ("owner_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "entity_types" table
ALTER TABLE "entity_types" DROP CONSTRAINT "entity_types_organizations_entitytypes", ADD CONSTRAINT "entity_types_organizations_entity_types" FOREIGN KEY ("owner_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "internal_policies" table
ALTER TABLE "internal_policies" DROP CONSTRAINT "internal_policies_organizations_internalpolicies", ADD CONSTRAINT "internal_policies_organizations_internal_policies" FOREIGN KEY ("owner_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create "internal_policy_control_objectives" table
CREATE TABLE "internal_policy_control_objectives" ("internal_policy_id" character varying NOT NULL, "control_objective_id" character varying NOT NULL, PRIMARY KEY ("internal_policy_id", "control_objective_id"), CONSTRAINT "internal_policy_control_objectives_control_objective_id" FOREIGN KEY ("control_objective_id") REFERENCES "control_objectives" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "internal_policy_control_objectives_internal_policy_id" FOREIGN KEY ("internal_policy_id") REFERENCES "internal_policies" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Modify "org_subscriptions" table
ALTER TABLE "org_subscriptions" DROP CONSTRAINT "org_subscriptions_organizations_orgsubscriptions", ADD CONSTRAINT "org_subscriptions_organizations_org_subscriptions" FOREIGN KEY ("owner_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create "program_action_plans" table
CREATE TABLE "program_action_plans" ("program_id" character varying NOT NULL, "action_plan_id" character varying NOT NULL, PRIMARY KEY ("program_id", "action_plan_id"), CONSTRAINT "program_action_plans_action_plan_id" FOREIGN KEY ("action_plan_id") REFERENCES "action_plans" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "program_action_plans_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "program_control_objectives" table
CREATE TABLE "program_control_objectives" ("program_id" character varying NOT NULL, "control_objective_id" character varying NOT NULL, PRIMARY KEY ("program_id", "control_objective_id"), CONSTRAINT "program_control_objectives_control_objective_id" FOREIGN KEY ("control_objective_id") REFERENCES "control_objectives" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "program_control_objectives_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "program_internal_policies" table
CREATE TABLE "program_internal_policies" ("program_id" character varying NOT NULL, "internal_policy_id" character varying NOT NULL, PRIMARY KEY ("program_id", "internal_policy_id"), CONSTRAINT "program_internal_policies_internal_policy_id" FOREIGN KEY ("internal_policy_id") REFERENCES "internal_policies" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "program_internal_policies_program_id" FOREIGN KEY ("program_id") REFERENCES "programs" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "risk_action_plans" table
CREATE TABLE "risk_action_plans" ("risk_id" character varying NOT NULL, "action_plan_id" character varying NOT NULL, PRIMARY KEY ("risk_id", "action_plan_id"), CONSTRAINT "risk_action_plans_action_plan_id" FOREIGN KEY ("action_plan_id") REFERENCES "action_plans" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "risk_action_plans_risk_id" FOREIGN KEY ("risk_id") REFERENCES "risks" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "standard_action_plans" table
CREATE TABLE "standard_action_plans" ("standard_id" character varying NOT NULL, "action_plan_id" character varying NOT NULL, PRIMARY KEY ("standard_id", "action_plan_id"), CONSTRAINT "standard_action_plans_action_plan_id" FOREIGN KEY ("action_plan_id") REFERENCES "action_plans" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "standard_action_plans_standard_id" FOREIGN KEY ("standard_id") REFERENCES "standards" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "standard_control_objectives" table
CREATE TABLE "standard_control_objectives" ("standard_id" character varying NOT NULL, "control_objective_id" character varying NOT NULL, PRIMARY KEY ("standard_id", "control_objective_id"), CONSTRAINT "standard_control_objectives_control_objective_id" FOREIGN KEY ("control_objective_id") REFERENCES "control_objectives" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "standard_control_objectives_standard_id" FOREIGN KEY ("standard_id") REFERENCES "standards" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "user_action_plans" table
CREATE TABLE "user_action_plans" ("user_id" character varying NOT NULL, "action_plan_id" character varying NOT NULL, PRIMARY KEY ("user_id", "action_plan_id"), CONSTRAINT "user_action_plans_action_plan_id" FOREIGN KEY ("action_plan_id") REFERENCES "action_plans" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "user_action_plans_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
