-- Create "trust_center_watermark_config_history" table
CREATE TABLE "trust_center_watermark_config_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "trust_center_id" character varying NULL, "logo_id" character varying NULL, "text" character varying NULL, "font_size" double precision NULL DEFAULT 48, "opacity" double precision NULL DEFAULT 0.3, "rotation" double precision NULL DEFAULT 45, "color" character varying NULL, "font" character varying NULL, PRIMARY KEY ("id"));
-- Create index "trustcenterwatermarkconfighistory_history_time" to table: "trust_center_watermark_config_history"
CREATE INDEX "trustcenterwatermarkconfighistory_history_time" ON "trust_center_watermark_config_history" ("history_time");
-- Create "trust_center_watermark_configs" table
CREATE TABLE "trust_center_watermark_configs" ("id" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "trust_center_id" character varying NULL, "text" character varying NULL, "font_size" double precision NULL DEFAULT 48, "opacity" double precision NULL DEFAULT 0.3, "rotation" double precision NULL DEFAULT 45, "color" character varying NULL, "font" character varying NULL, "logo_id" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "trust_center_watermark_configs_files_file" FOREIGN KEY ("logo_id") REFERENCES "files" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "text_or_logo_id_not_null" CHECK ((text IS NOT NULL) OR (logo_id IS NOT NULL)));
-- Create index "trustcenterwatermarkconfig_trust_center_id" to table: "trust_center_watermark_configs"
CREATE UNIQUE INDEX "trustcenterwatermarkconfig_trust_center_id" ON "trust_center_watermark_configs" ("trust_center_id") WHERE (deleted_at IS NULL);
-- Modify "trust_centers" table
ALTER TABLE "trust_centers" ADD COLUMN "trust_center_watermark_config" character varying NULL, ADD CONSTRAINT "trust_centers_trust_center_watermark_configs_watermark_config" FOREIGN KEY ("trust_center_watermark_config") REFERENCES "trust_center_watermark_configs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
