-- Create index "actionplan_id" to table: "action_plans"
CREATE UNIQUE INDEX "actionplan_id" ON "action_plans" ("id");
-- Create index "apitoken_id" to table: "api_tokens"
CREATE UNIQUE INDEX "apitoken_id" ON "api_tokens" ("id");
-- Create index "contact_id" to table: "contacts"
CREATE UNIQUE INDEX "contact_id" ON "contacts" ("id");
-- Create index "controlimplementation_id" to table: "control_implementations"
CREATE UNIQUE INDEX "controlimplementation_id" ON "control_implementations" ("id");
-- Modify "control_objective_history" table
ALTER TABLE "control_objective_history" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
-- Modify "control_objectives" table
ALTER TABLE "control_objectives" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
-- Create index "controlobjective_id" to table: "control_objectives"
CREATE UNIQUE INDEX "controlobjective_id" ON "control_objectives" ("id");
-- Create index "control_id" to table: "controls"
CREATE UNIQUE INDEX "control_id" ON "controls" ("id");
-- Create index "documentdata_id" to table: "document_data"
CREATE UNIQUE INDEX "documentdata_id" ON "document_data" ("id");
-- Create index "emailverificationtoken_id" to table: "email_verification_tokens"
CREATE UNIQUE INDEX "emailverificationtoken_id" ON "email_verification_tokens" ("id");
-- Create index "entity_id" to table: "entities"
CREATE UNIQUE INDEX "entity_id" ON "entities" ("id");
-- Create index "entitytype_id" to table: "entity_types"
CREATE UNIQUE INDEX "entitytype_id" ON "entity_types" ("id");
-- Create index "event_id" to table: "events"
CREATE UNIQUE INDEX "event_id" ON "events" ("id");
-- Create index "evidence_id" to table: "evidences"
CREATE UNIQUE INDEX "evidence_id" ON "evidences" ("id");
-- Create index "file_id" to table: "files"
CREATE UNIQUE INDEX "file_id" ON "files" ("id");
-- Create index "groupmembership_id" to table: "group_memberships"
CREATE UNIQUE INDEX "groupmembership_id" ON "group_memberships" ("id");
-- Create index "groupsetting_id" to table: "group_settings"
CREATE UNIQUE INDEX "groupsetting_id" ON "group_settings" ("id");
-- Create index "group_id" to table: "groups"
CREATE UNIQUE INDEX "group_id" ON "groups" ("id");
-- Create index "hush_id" to table: "hushes"
CREATE UNIQUE INDEX "hush_id" ON "hushes" ("id");
-- Create index "integration_id" to table: "integrations"
CREATE UNIQUE INDEX "integration_id" ON "integrations" ("id");
-- Create index "internalpolicy_id" to table: "internal_policies"
CREATE UNIQUE INDEX "internalpolicy_id" ON "internal_policies" ("id");
-- Create index "invite_id" to table: "invites"
CREATE UNIQUE INDEX "invite_id" ON "invites" ("id");
-- Create index "mappedcontrol_id" to table: "mapped_controls"
CREATE UNIQUE INDEX "mappedcontrol_id" ON "mapped_controls" ("id");
-- Create index "narrative_id" to table: "narratives"
CREATE UNIQUE INDEX "narrative_id" ON "narratives" ("id");
-- Create index "note_id" to table: "notes"
CREATE UNIQUE INDEX "note_id" ON "notes" ("id");
-- Create index "onboarding_id" to table: "onboardings"
CREATE UNIQUE INDEX "onboarding_id" ON "onboardings" ("id");
-- Create index "orgmembership_id" to table: "org_memberships"
CREATE UNIQUE INDEX "orgmembership_id" ON "org_memberships" ("id");
-- Create index "orgsubscription_id" to table: "org_subscriptions"
CREATE UNIQUE INDEX "orgsubscription_id" ON "org_subscriptions" ("id");
-- Create index "organizationsetting_id" to table: "organization_settings"
CREATE UNIQUE INDEX "organizationsetting_id" ON "organization_settings" ("id");
-- Create index "organization_id" to table: "organizations"
CREATE UNIQUE INDEX "organization_id" ON "organizations" ("id");
-- Create index "passwordresettoken_id" to table: "password_reset_tokens"
CREATE UNIQUE INDEX "passwordresettoken_id" ON "password_reset_tokens" ("id");
-- Create index "personalaccesstoken_id" to table: "personal_access_tokens"
CREATE UNIQUE INDEX "personalaccesstoken_id" ON "personal_access_tokens" ("id");
-- Create index "procedure_id" to table: "procedures"
CREATE UNIQUE INDEX "procedure_id" ON "procedures" ("id");
-- Create index "programmembership_id" to table: "program_memberships"
CREATE UNIQUE INDEX "programmembership_id" ON "program_memberships" ("id");
-- Create index "program_id" to table: "programs"
CREATE UNIQUE INDEX "program_id" ON "programs" ("id");
-- Create index "risk_id" to table: "risks"
CREATE UNIQUE INDEX "risk_id" ON "risks" ("id");
-- Create index "standard_id" to table: "standards"
CREATE UNIQUE INDEX "standard_id" ON "standards" ("id");
-- Create index "subcontrol_id" to table: "subcontrols"
CREATE UNIQUE INDEX "subcontrol_id" ON "subcontrols" ("id");
-- Create index "subscriber_id" to table: "subscribers"
CREATE UNIQUE INDEX "subscriber_id" ON "subscribers" ("id");
-- Create index "task_id" to table: "tasks"
CREATE UNIQUE INDEX "task_id" ON "tasks" ("id");
-- Create index "template_id" to table: "templates"
CREATE UNIQUE INDEX "template_id" ON "templates" ("id");
-- Create index "tfasetting_id" to table: "tfa_settings"
CREATE UNIQUE INDEX "tfasetting_id" ON "tfa_settings" ("id");
-- Create index "usersetting_id" to table: "user_settings"
CREATE UNIQUE INDEX "usersetting_id" ON "user_settings" ("id");
-- Drop index "user_email_auth_provider" from table: "users"
DROP INDEX "user_email_auth_provider";
-- Create index "user_email" to table: "users"
CREATE UNIQUE INDEX "user_email" ON "users" ("email") WHERE (deleted_at IS NULL);
-- Create index "webauthn_id" to table: "webauthns"
CREATE UNIQUE INDEX "webauthn_id" ON "webauthns" ("id");
