-- Modify "note_history" table
ALTER TABLE "note_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "internal_policy_history" table
ALTER TABLE "internal_policy_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "organization_setting_history" table
ALTER TABLE "organization_setting_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "contact_history" table
ALTER TABLE "contact_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "org_subscription_history" table
ALTER TABLE "org_subscription_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "action_plan_history" table
ALTER TABLE "action_plan_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "control_objective_history" table
ALTER TABLE "control_objective_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "procedure_history" table
ALTER TABLE "procedure_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "org_membership_history" table
ALTER TABLE "org_membership_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "document_data_history" table
ALTER TABLE "document_data_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "users" table
ALTER TABLE "users" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "control_history" table
ALTER TABLE "control_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "program_history" table
ALTER TABLE "program_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "entity_history" table
ALTER TABLE "entity_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "entity_type_history" table
ALTER TABLE "entity_type_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "narrative_history" table
ALTER TABLE "narrative_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "event_history" table
ALTER TABLE "event_history" DROP COLUMN "created_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL;
-- Modify "program_membership_history" table
ALTER TABLE "program_membership_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "file_history" table
ALTER TABLE "file_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "user_setting_history" table
ALTER TABLE "user_setting_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "group_history" table
ALTER TABLE "group_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "group_membership_history" table
ALTER TABLE "group_membership_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "user_history" table
ALTER TABLE "user_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "group_setting_history" table
ALTER TABLE "group_setting_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "template_history" table
ALTER TABLE "template_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "task_history" table
ALTER TABLE "task_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "hush_history" table
ALTER TABLE "hush_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "subcontrol_history" table
ALTER TABLE "subcontrol_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "integration_history" table
ALTER TABLE "integration_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "standard_history" table
ALTER TABLE "standard_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "risk_history" table
ALTER TABLE "risk_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "organization_history" table
ALTER TABLE "organization_history" DROP COLUMN "created_by", DROP COLUMN "deleted_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD COLUMN "deleted_by_id" character varying NULL;
-- Modify "action_plans" table
ALTER TABLE "action_plans" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "action_plans_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "action_plans_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "api_tokens" table
ALTER TABLE "api_tokens" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "api_tokens_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "api_tokens_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "contacts" table
ALTER TABLE "contacts" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "contacts_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "contacts_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "control_objectives" table
ALTER TABLE "control_objectives" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "control_objectives_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "control_objectives_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "controls" table
ALTER TABLE "controls" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "controls_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "controls_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "document_data" table
ALTER TABLE "document_data" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "document_data_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "document_data_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "email_verification_tokens" table
ALTER TABLE "email_verification_tokens" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "email_verification_tokens_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "email_verification_tokens_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "entities" table
ALTER TABLE "entities" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "entities_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "entities_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "entity_types" table
ALTER TABLE "entity_types" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "entity_types_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "entity_types_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "events" table
ALTER TABLE "events" DROP COLUMN "created_by", DROP COLUMN "updated_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "events_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "events_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "files" table
ALTER TABLE "files" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "files_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "files_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "group_memberships" table
ALTER TABLE "group_memberships" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "group_memberships_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "group_memberships_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "group_settings" table
ALTER TABLE "group_settings" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "group_settings_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "group_settings_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "groups" table
ALTER TABLE "groups" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "groups_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "groups_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "hushes" table
ALTER TABLE "hushes" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "hushes_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "hushes_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "integrations" table
ALTER TABLE "integrations" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "integrations_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "integrations_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "internal_policies" table
ALTER TABLE "internal_policies" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "internal_policies_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "internal_policies_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "invites" table
ALTER TABLE "invites" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "invites_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "invites_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "narratives" table
ALTER TABLE "narratives" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "narratives_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "narratives_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "notes" table
ALTER TABLE "notes" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "notes_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "notes_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "org_memberships" table
ALTER TABLE "org_memberships" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "org_memberships_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "org_memberships_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "org_subscriptions" table
ALTER TABLE "org_subscriptions" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "org_subscriptions_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "org_subscriptions_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "organization_settings" table
ALTER TABLE "organization_settings" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "organization_settings_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "organization_settings_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "organizations" table
ALTER TABLE "organizations" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "organizations_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "organizations_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "password_reset_tokens" table
ALTER TABLE "password_reset_tokens" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "password_reset_tokens_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "password_reset_tokens_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "personal_access_tokens" table
ALTER TABLE "personal_access_tokens" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "personal_access_tokens_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "personal_access_tokens_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "procedures" table
ALTER TABLE "procedures" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "procedures_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "procedures_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "program_memberships" table
ALTER TABLE "program_memberships" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "program_memberships_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "program_memberships_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "programs" table
ALTER TABLE "programs" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "programs_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "programs_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "risks" table
ALTER TABLE "risks" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "risks_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "risks_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "standards" table
ALTER TABLE "standards" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "standards_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "standards_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "subcontrols" table
ALTER TABLE "subcontrols" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "subcontrols_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "subcontrols_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "subscribers" table
ALTER TABLE "subscribers" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "subscribers_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "subscribers_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "tasks" table
ALTER TABLE "tasks" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "tasks_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "tasks_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "templates" table
ALTER TABLE "templates" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "templates_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "templates_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "tfa_settings" table
ALTER TABLE "tfa_settings" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "tfa_settings_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "tfa_settings_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "user_settings" table
ALTER TABLE "user_settings" DROP COLUMN "created_by", DROP COLUMN "updated_by", DROP COLUMN "deleted_by", ADD COLUMN "deleted_by_id" character varying NULL, ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "user_settings_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "user_settings_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "webauthns" table
ALTER TABLE "webauthns" DROP COLUMN "created_by", DROP COLUMN "updated_by", ADD COLUMN "created_by_id" character varying NULL, ADD COLUMN "updated_by_id" character varying NULL, ADD CONSTRAINT "webauthns_users_created_by" FOREIGN KEY ("created_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "webauthns_users_updated_by" FOREIGN KEY ("updated_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
