-- Modify "subcontrol_history" table
ALTER TABLE "subcontrol_history" ADD COLUMN "subcontrol_kind_name" character varying NULL, ADD COLUMN "subcontrol_kind_id" character varying NULL;
-- Modify "risk_history" table
ALTER TABLE "risk_history" ADD COLUMN "risk_kind_name" character varying NULL, ADD COLUMN "risk_kind_id" character varying NULL, ADD COLUMN "risk_category_name" character varying NULL, ADD COLUMN "risk_category_id" character varying NULL;
-- Modify "control_history" table
ALTER TABLE "control_history" ADD COLUMN "control_kind_name" character varying NULL, ADD COLUMN "control_kind_id" character varying NULL;
-- Modify "task_history" table
ALTER TABLE "task_history" ADD COLUMN "task_kind_name" character varying NULL, ADD COLUMN "task_kind_id" character varying NULL, ADD COLUMN "system_generated" boolean NOT NULL DEFAULT false, ADD COLUMN "idempotency_key" character varying NULL, ADD COLUMN "external_reference_url" jsonb NULL;
-- Modify "action_plan_history" table
ALTER TABLE "action_plan_history" ADD COLUMN "action_plan_kind_name" character varying NULL, ADD COLUMN "action_plan_kind_id" character varying NULL;
-- Modify "internal_policy_history" table
ALTER TABLE "internal_policy_history" ADD COLUMN "internal_policy_kind_name" character varying NULL, ADD COLUMN "internal_policy_kind_id" character varying NULL;
-- Modify "procedure_history" table
ALTER TABLE "procedure_history" ADD COLUMN "procedure_kind_name" character varying NULL, ADD COLUMN "procedure_kind_id" character varying NULL;
-- Modify "program_history" table
ALTER TABLE "program_history" ADD COLUMN "program_kind_name" character varying NULL, ADD COLUMN "program_kind_id" character varying NULL;
-- Create "custom_type_enums" table
CREATE TABLE "custom_type_enums" ("id" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "object_type" character varying NOT NULL, "field" character varying NOT NULL DEFAULT 'kind', "name" citext NOT NULL, "description" character varying NULL, "color" character varying NULL, "owner_id" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "custom_type_enums_organizations_custom_type_enums" FOREIGN KEY ("owner_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "customtypeenum_name_owner_id" to table: "custom_type_enums"
CREATE UNIQUE INDEX "customtypeenum_name_owner_id" ON "custom_type_enums" ("name", "owner_id") WHERE (deleted_at IS NULL);
-- Create index "customtypeenum_object_type" to table: "custom_type_enums"
CREATE INDEX "customtypeenum_object_type" ON "custom_type_enums" ("object_type");
-- Create index "customtypeenum_owner_id" to table: "custom_type_enums"
CREATE INDEX "customtypeenum_owner_id" ON "custom_type_enums" ("owner_id") WHERE (deleted_at IS NULL);
-- Modify "action_plans" table
ALTER TABLE "action_plans" ADD COLUMN "action_plan_kind_name" character varying NULL, ADD COLUMN "action_plan_kind_id" character varying NULL, ADD COLUMN "custom_type_enum_action_plans" character varying NULL, ADD CONSTRAINT "action_plans_custom_type_enums_action_plan_kind" FOREIGN KEY ("action_plan_kind_id") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "action_plans_custom_type_enums_action_plans" FOREIGN KEY ("custom_type_enum_action_plans") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "controls" table
ALTER TABLE "controls" ADD COLUMN "control_kind_name" character varying NULL, ADD COLUMN "control_kind_id" character varying NULL, ADD COLUMN "custom_type_enum_controls" character varying NULL, ADD CONSTRAINT "controls_custom_type_enums_control_kind" FOREIGN KEY ("control_kind_id") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "controls_custom_type_enums_controls" FOREIGN KEY ("custom_type_enum_controls") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "internal_policies" table
ALTER TABLE "internal_policies" ADD COLUMN "internal_policy_kind_name" character varying NULL, ADD COLUMN "custom_type_enum_internal_policies" character varying NULL, ADD COLUMN "internal_policy_kind_id" character varying NULL, ADD CONSTRAINT "internal_policies_custom_type_enums_internal_policies" FOREIGN KEY ("custom_type_enum_internal_policies") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "internal_policies_custom_type_enums_internal_policy_kind" FOREIGN KEY ("internal_policy_kind_id") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "procedures" table
ALTER TABLE "procedures" ADD COLUMN "procedure_kind_name" character varying NULL, ADD COLUMN "custom_type_enum_procedures" character varying NULL, ADD COLUMN "procedure_kind_id" character varying NULL, ADD CONSTRAINT "procedures_custom_type_enums_procedure_kind" FOREIGN KEY ("procedure_kind_id") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "procedures_custom_type_enums_procedures" FOREIGN KEY ("custom_type_enum_procedures") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "programs" table
ALTER TABLE "programs" ADD COLUMN "program_kind_name" character varying NULL, ADD COLUMN "custom_type_enum_programs" character varying NULL, ADD COLUMN "program_kind_id" character varying NULL, ADD CONSTRAINT "programs_custom_type_enums_program_kind" FOREIGN KEY ("program_kind_id") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "programs_custom_type_enums_programs" FOREIGN KEY ("custom_type_enum_programs") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "risks" table
ALTER TABLE "risks" ADD COLUMN "risk_kind_name" character varying NULL, ADD COLUMN "risk_category_name" character varying NULL, ADD COLUMN "custom_type_enum_risks" character varying NULL, ADD COLUMN "custom_type_enum_risk_categories" character varying NULL, ADD COLUMN "risk_kind_id" character varying NULL, ADD COLUMN "risk_category_id" character varying NULL, ADD CONSTRAINT "risks_custom_type_enums_risk_categories" FOREIGN KEY ("custom_type_enum_risk_categories") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "risks_custom_type_enums_risk_category" FOREIGN KEY ("risk_category_id") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "risks_custom_type_enums_risk_kind" FOREIGN KEY ("risk_kind_id") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "risks_custom_type_enums_risks" FOREIGN KEY ("custom_type_enum_risks") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "subcontrols" table
ALTER TABLE "subcontrols" ADD COLUMN "subcontrol_kind_name" character varying NULL, ADD COLUMN "custom_type_enum_subcontrols" character varying NULL, ADD COLUMN "subcontrol_kind_id" character varying NULL, ADD CONSTRAINT "subcontrols_custom_type_enums_subcontrol_kind" FOREIGN KEY ("subcontrol_kind_id") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "subcontrols_custom_type_enums_subcontrols" FOREIGN KEY ("custom_type_enum_subcontrols") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create "tag_definitions" table
CREATE TABLE "tag_definitions" ("id" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "name" citext NOT NULL, "aliases" jsonb NULL, "slug" citext NULL, "description" character varying NULL, "color" character varying NULL, "owner_id" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "tag_definitions_organizations_tag_definitions" FOREIGN KEY ("owner_id") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "tagdefinition_name_owner_id" to table: "tag_definitions"
CREATE UNIQUE INDEX "tagdefinition_name_owner_id" ON "tag_definitions" ("name", "owner_id") WHERE (deleted_at IS NULL);
-- Create index "tagdefinition_owner_id" to table: "tag_definitions"
CREATE INDEX "tagdefinition_owner_id" ON "tag_definitions" ("owner_id") WHERE (deleted_at IS NULL);
-- Create index "tagdefinition_slug_owner_id" to table: "tag_definitions"
CREATE UNIQUE INDEX "tagdefinition_slug_owner_id" ON "tag_definitions" ("slug", "owner_id") WHERE (deleted_at IS NULL);
-- Modify "tasks" table
ALTER TABLE "tasks" ADD COLUMN "task_kind_name" character varying NULL, ADD COLUMN "system_generated" boolean NOT NULL DEFAULT false, ADD COLUMN "idempotency_key" character varying NULL, ADD COLUMN "external_reference_url" jsonb NULL, ADD COLUMN "custom_type_enum_tasks" character varying NULL, ADD COLUMN "task_kind_id" character varying NULL, ADD CONSTRAINT "tasks_custom_type_enums_task_kind" FOREIGN KEY ("task_kind_id") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "tasks_custom_type_enums_tasks" FOREIGN KEY ("custom_type_enum_tasks") REFERENCES "custom_type_enums" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
