-- Modify "scheduled_job_runs" table
ALTER TABLE "scheduled_job_runs" ADD COLUMN "metadata" jsonb NULL;
-- Modify "job_results" table
ALTER TABLE "job_results" ALTER COLUMN "exit_code" DROP NOT NULL, ADD COLUMN "compliance_job_id" character varying NULL, ADD COLUMN "metadata" jsonb NULL;
-- Modify "scheduled_job_history" table
ALTER TABLE "scheduled_job_history" ADD COLUMN "metadata" jsonb NULL;
-- Modify "job_template_history" table
ALTER TABLE "job_template_history" ALTER COLUMN "download_url" DROP NOT NULL, ADD COLUMN "runtime_platform" character varying NULL, ADD COLUMN "script_path" character varying NULL, ADD COLUMN "metadata" jsonb NULL;
-- Modify "job_runners" table
ALTER TABLE "job_runners" ADD COLUMN "metadata" jsonb NULL;
-- Modify "job_templates" table
ALTER TABLE "job_templates" ALTER COLUMN "download_url" DROP NOT NULL, ADD COLUMN "runtime_platform" character varying NULL, ADD COLUMN "script_path" character varying NULL, ADD COLUMN "metadata" jsonb NULL;
-- Modify "scheduled_jobs" table
ALTER TABLE "scheduled_jobs" ADD COLUMN "metadata" jsonb NULL;
-- Modify "assets" table
ALTER TABLE "assets" ADD COLUMN "job_result_assets" character varying NULL, ADD COLUMN "job_template_assets" character varying NULL, ADD COLUMN "scheduled_job_assets" character varying NULL, ADD CONSTRAINT "assets_job_results_assets" FOREIGN KEY ("job_result_assets") REFERENCES "job_results" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "assets_job_templates_assets" FOREIGN KEY ("job_template_assets") REFERENCES "job_templates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "assets_scheduled_jobs_assets" FOREIGN KEY ("scheduled_job_assets") REFERENCES "scheduled_jobs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "contacts" table
ALTER TABLE "contacts" ADD COLUMN "job_result_contacts" character varying NULL, ADD COLUMN "job_template_contacts" character varying NULL, ADD COLUMN "scheduled_job_contacts" character varying NULL, ADD CONSTRAINT "contacts_job_results_contacts" FOREIGN KEY ("job_result_contacts") REFERENCES "job_results" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "contacts_job_templates_contacts" FOREIGN KEY ("job_template_contacts") REFERENCES "job_templates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "contacts_scheduled_jobs_contacts" FOREIGN KEY ("scheduled_job_contacts") REFERENCES "scheduled_jobs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "controls" table
ALTER TABLE "controls" ADD COLUMN "job_result_controls" character varying NULL, ADD COLUMN "job_template_controls" character varying NULL, ADD CONSTRAINT "controls_job_results_controls" FOREIGN KEY ("job_result_controls") REFERENCES "job_results" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "controls_job_templates_controls" FOREIGN KEY ("job_template_controls") REFERENCES "job_templates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "entities" table
ALTER TABLE "entities" ADD COLUMN "job_result_entities" character varying NULL, ADD COLUMN "job_template_entities" character varying NULL, ADD COLUMN "scheduled_job_entities" character varying NULL, ADD CONSTRAINT "entities_job_results_entities" FOREIGN KEY ("job_result_entities") REFERENCES "job_results" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "entities_job_templates_entities" FOREIGN KEY ("job_template_entities") REFERENCES "job_templates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "entities_scheduled_jobs_entities" FOREIGN KEY ("scheduled_job_entities") REFERENCES "scheduled_jobs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "evidences" table
ALTER TABLE "evidences" ADD COLUMN "job_result_evidence" character varying NULL, ADD COLUMN "job_template_evidence" character varying NULL, ADD COLUMN "scheduled_job_evidence" character varying NULL, ADD CONSTRAINT "evidences_job_results_evidence" FOREIGN KEY ("job_result_evidence") REFERENCES "job_results" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "evidences_job_templates_evidence" FOREIGN KEY ("job_template_evidence") REFERENCES "job_templates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "evidences_scheduled_jobs_evidence" FOREIGN KEY ("scheduled_job_evidence") REFERENCES "scheduled_jobs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "findings" table
ALTER TABLE "findings" ADD COLUMN "job_result_findings" character varying NULL, ADD COLUMN "job_template_findings" character varying NULL, ADD COLUMN "scheduled_job_findings" character varying NULL, ADD CONSTRAINT "findings_job_results_findings" FOREIGN KEY ("job_result_findings") REFERENCES "job_results" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "findings_job_templates_findings" FOREIGN KEY ("job_template_findings") REFERENCES "job_templates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "findings_scheduled_jobs_findings" FOREIGN KEY ("scheduled_job_findings") REFERENCES "scheduled_jobs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "risks" table
ALTER TABLE "risks" ADD COLUMN "job_result_risks" character varying NULL, ADD COLUMN "job_template_risks" character varying NULL, ADD COLUMN "scheduled_job_risks" character varying NULL, ADD CONSTRAINT "risks_job_results_risks" FOREIGN KEY ("job_result_risks") REFERENCES "job_results" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "risks_job_templates_risks" FOREIGN KEY ("job_template_risks") REFERENCES "job_templates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "risks_scheduled_jobs_risks" FOREIGN KEY ("scheduled_job_risks") REFERENCES "scheduled_jobs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "standards" table
ALTER TABLE "standards" ADD COLUMN "job_result_standards" character varying NULL, ADD COLUMN "job_template_standards" character varying NULL, ADD COLUMN "scheduled_job_standards" character varying NULL, ADD CONSTRAINT "standards_job_results_standards" FOREIGN KEY ("job_result_standards") REFERENCES "job_results" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "standards_job_templates_standards" FOREIGN KEY ("job_template_standards") REFERENCES "job_templates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "standards_scheduled_jobs_standards" FOREIGN KEY ("scheduled_job_standards") REFERENCES "scheduled_jobs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "tasks" table
ALTER TABLE "tasks" ADD COLUMN "job_result_tasks" character varying NULL, ADD COLUMN "job_template_tasks" character varying NULL, ADD COLUMN "scheduled_job_tasks" character varying NULL, ADD CONSTRAINT "tasks_job_results_tasks" FOREIGN KEY ("job_result_tasks") REFERENCES "job_results" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "tasks_job_templates_tasks" FOREIGN KEY ("job_template_tasks") REFERENCES "job_templates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "tasks_scheduled_jobs_tasks" FOREIGN KEY ("scheduled_job_tasks") REFERENCES "scheduled_jobs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "vulnerabilities" table
ALTER TABLE "vulnerabilities" ADD COLUMN "job_result_vulnerabilities" character varying NULL, ADD COLUMN "job_template_vulnerabilities" character varying NULL, ADD COLUMN "scheduled_job_vulnerabilities" character varying NULL, ADD CONSTRAINT "vulnerabilities_job_results_vulnerabilities" FOREIGN KEY ("job_result_vulnerabilities") REFERENCES "job_results" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "vulnerabilities_job_templates_vulnerabilities" FOREIGN KEY ("job_template_vulnerabilities") REFERENCES "job_templates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "vulnerabilities_scheduled_jobs_vulnerabilities" FOREIGN KEY ("scheduled_job_vulnerabilities") REFERENCES "scheduled_jobs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
