-- Create "action_plan_history" table
CREATE TABLE "action_plan_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "revision" character varying NULL DEFAULT 'v0.0.1', "name" character varying NOT NULL, "status" character varying NULL DEFAULT 'DRAFT', "management_mode" character varying NULL DEFAULT 'OPENLANE_MANAGED', "details" text NULL, "details_json" jsonb NULL, "approval_required" boolean NULL DEFAULT true, "review_due" timestamptz NULL, "review_frequency" character varying NULL DEFAULT 'YEARLY', "approver_id" character varying NULL, "delegate_id" character varying NULL, "summary" character varying NULL, "tag_suggestions" jsonb NULL, "dismissed_tag_suggestions" jsonb NULL, "control_suggestions" jsonb NULL, "dismissed_control_suggestions" jsonb NULL, "improvement_suggestions" jsonb NULL, "dismissed_improvement_suggestions" jsonb NULL, "url" character varying NULL, "file_id" character varying NULL, "external_file_id" character varying NULL, "external_contents" character varying NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "action_plan_kind_name" character varying NULL, "action_plan_kind_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "title" character varying NOT NULL, "description" text NULL, "due_date" timestamptz NULL, "completed_at" timestamptz NULL, "priority" character varying NULL, "requires_approval" boolean NOT NULL DEFAULT false, "blocked" boolean NOT NULL DEFAULT false, "blocker_reason" text NULL, "metadata" jsonb NULL, "raw_payload" jsonb NULL, "source" character varying NULL, PRIMARY KEY ("id"));
-- Create index "actionplanhistory_history_time" to table: "action_plan_history"
CREATE INDEX "actionplanhistory_history_time" ON "action_plan_history" ("history_time");
-- Create "assessment_history" table
CREATE TABLE "assessment_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "name" character varying NOT NULL, "assessment_type" character varying NOT NULL DEFAULT 'INTERNAL', "template_id" character varying NULL, "jsonconfig" jsonb NULL, "uischema" jsonb NULL, "response_due_duration" bigint NULL, PRIMARY KEY ("id"));
-- Create index "assessmenthistory_history_time" to table: "assessment_history"
CREATE INDEX "assessmenthistory_history_time" ON "assessment_history" ("history_time");
-- Create "assessment_response_history" table
CREATE TABLE "assessment_response_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "owner_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "assessment_id" character varying NOT NULL, "is_test" boolean NOT NULL DEFAULT false, "campaign_id" character varying NULL, "identity_holder_id" character varying NULL, "entity_id" character varying NULL, "display_name" character varying NULL, "email" character varying NULL, "send_attempts" bigint NOT NULL DEFAULT 1, "email_delivered_at" timestamptz NULL, "email_opened_at" timestamptz NULL, "email_clicked_at" timestamptz NULL, "email_open_count" bigint NULL DEFAULT 0, "email_click_count" bigint NULL DEFAULT 0, "last_email_event_at" timestamptz NULL, "email_metadata" jsonb NULL, "status" character varying NOT NULL DEFAULT 'SENT', "assigned_at" timestamptz NOT NULL, "started_at" timestamptz NOT NULL, "completed_at" timestamptz NULL, "due_date" timestamptz NULL, "document_data_id" character varying NULL, "is_draft" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"));
-- Create index "assessmentresponsehistory_history_time" to table: "assessment_response_history"
CREATE INDEX "assessmentresponsehistory_history_time" ON "assessment_response_history" ("history_time");
-- Create "asset_history" table
CREATE TABLE "asset_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "internal_owner" character varying NULL, "internal_owner_user_id" character varying NULL, "internal_owner_group_id" character varying NULL, "asset_subtype_name" character varying NULL, "asset_subtype_id" character varying NULL, "asset_data_classification_name" character varying NULL, "asset_data_classification_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "access_model_name" character varying NULL, "access_model_id" character varying NULL, "encryption_status_name" character varying NULL, "encryption_status_id" character varying NULL, "security_tier_name" character varying NULL, "security_tier_id" character varying NULL, "criticality_name" character varying NULL, "criticality_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "asset_type" character varying NOT NULL DEFAULT 'TECHNOLOGY', "name" character varying NOT NULL, "display_name" character varying NULL, "description" character varying NULL, "identifier" character varying NULL, "website" character varying NULL, "physical_location" character varying NULL, "region" character varying NULL, "contains_pii" boolean NULL DEFAULT false, "source_type" character varying NOT NULL DEFAULT 'MANUAL', "source_platform_id" character varying NULL, "source_identifier" character varying NULL, "cost_center" character varying NULL, "estimated_monthly_cost" double precision NULL, "purchase_date" timestamptz NULL, "cpe" character varying NULL, "categories" jsonb NULL, "integration_id" character varying NULL, "observed_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "assethistory_history_time" to table: "asset_history"
CREATE INDEX "assethistory_history_time" ON "asset_history" ("history_time");
-- Create "campaign_history" table
CREATE TABLE "campaign_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "internal_owner" character varying NULL, "internal_owner_user_id" character varying NULL, "internal_owner_group_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "name" character varying NOT NULL, "description" character varying NULL, "campaign_type" character varying NOT NULL DEFAULT 'QUESTIONNAIRE', "status" character varying NOT NULL DEFAULT 'DRAFT', "is_active" boolean NOT NULL DEFAULT false, "scheduled_at" timestamptz NULL, "launched_at" timestamptz NULL, "completed_at" timestamptz NULL, "due_date" timestamptz NULL, "is_recurring" boolean NOT NULL DEFAULT false, "recurrence_frequency" character varying NULL DEFAULT 'NONE', "recurrence_interval" bigint NULL DEFAULT 1, "recurrence_timezone" character varying NULL, "recurrence_cron" character varying NULL, "last_run_at" timestamptz NULL, "next_run_at" timestamptz NULL, "recurrence_end_at" timestamptz NULL, "recipient_count" bigint NULL DEFAULT 0, "resend_count" bigint NULL DEFAULT 0, "last_resent_at" timestamptz NULL, "entity_id" character varying NULL, "template_id" character varying NULL, "assessment_id" character varying NULL, "metadata" jsonb NULL, "email_template_id" character varying NULL, "integration_id" character varying NULL, "email_branding_id" character varying NULL, "trust_center_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "campaignhistory_history_time" to table: "campaign_history"
CREATE INDEX "campaignhistory_history_time" ON "campaign_history" ("history_time");
-- Create "campaign_target_history" table
CREATE TABLE "campaign_target_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "owner_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "campaign_id" character varying NULL, "contact_id" character varying NULL, "user_id" character varying NULL, "group_id" character varying NULL, "subscriber_id" character varying NULL, "email" character varying NOT NULL, "full_name" character varying NULL, "status" character varying NOT NULL DEFAULT 'NOT_STARTED', "sent_at" timestamptz NULL, "completed_at" timestamptz NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "campaigntargethistory_history_time" to table: "campaign_target_history"
CREATE INDEX "campaigntargethistory_history_time" ON "campaign_target_history" ("history_time");
-- Create "contact_history" table
CREATE TABLE "contact_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "full_name" character varying NULL, "title" character varying NULL, "company" character varying NULL, "email" character varying NULL, "phone_number" character varying NULL, "address" character varying NULL, "status" character varying NOT NULL DEFAULT 'ACTIVE', "external_id" character varying NULL, "integration_id" character varying NULL, "observed_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "contacthistory_history_time" to table: "contact_history"
CREATE INDEX "contacthistory_history_time" ON "contact_history" ("history_time");
-- Create "control_history" table
CREATE TABLE "control_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "external_uuid" character varying NULL, "title" character varying NULL, "description" text NULL, "description_json" jsonb NULL, "aliases" jsonb NULL, "reference_id" character varying NULL, "auditor_reference_id" character varying NULL, "responsible_party_id" character varying NULL, "status" character varying NULL DEFAULT 'NOT_IMPLEMENTED', "implementation_status" character varying NULL DEFAULT 'PLANNED', "implementation_description" text NULL, "public_representation" text NULL, "source" character varying NULL DEFAULT 'USER_DEFINED', "source_name" character varying NULL, "reference_framework" character varying NULL, "reference_framework_revision" character varying NULL, "category" character varying NULL, "category_id" character varying NULL, "subcategory" character varying NULL, "mapped_categories" jsonb NULL, "assessment_objectives" jsonb NULL, "assessment_methods" jsonb NULL, "control_questions" jsonb NULL, "implementation_guidance" jsonb NULL, "example_evidence" jsonb NULL, "references" jsonb NULL, "testing_procedures" jsonb NULL, "evidence_requests" jsonb NULL, "control_owner_id" character varying NULL, "delegate_id" character varying NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "control_kind_name" character varying NULL, "control_kind_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "ref_code" character varying NOT NULL, "standard_id" character varying NULL, "trust_center_visibility" character varying NULL DEFAULT 'NOT_VISIBLE', "is_trust_center_control" boolean NULL DEFAULT false, PRIMARY KEY ("id"));
-- Create index "controlhistory_history_time" to table: "control_history"
CREATE INDEX "controlhistory_history_time" ON "control_history" ("history_time");
-- Create "control_implementation_history" table
CREATE TABLE "control_implementation_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "status" character varying NULL DEFAULT 'DRAFT', "implementation_date" timestamptz NULL, "verified" boolean NULL, "verification_date" timestamptz NULL, "details" text NULL, "details_json" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "controlimplementationhistory_history_time" to table: "control_implementation_history"
CREATE INDEX "controlimplementationhistory_history_time" ON "control_implementation_history" ("history_time");
-- Create "control_objective_history" table
CREATE TABLE "control_objective_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "revision" character varying NULL DEFAULT 'v0.0.1', "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "name" character varying NOT NULL, "desired_outcome" text NULL, "desired_outcome_json" jsonb NULL, "status" character varying NULL DEFAULT 'DRAFT', "source" character varying NULL DEFAULT 'USER_DEFINED', "control_objective_type" character varying NULL, "category" character varying NULL, "subcategory" character varying NULL, PRIMARY KEY ("id"));
-- Create index "controlobjectivehistory_history_time" to table: "control_objective_history"
CREATE INDEX "controlobjectivehistory_history_time" ON "control_objective_history" ("history_time");
-- Create "custom_domain_history" table
CREATE TABLE "custom_domain_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "cname_record" character varying NOT NULL, "mappable_domain_id" character varying NOT NULL, "dns_verification_id" character varying NULL, "trust_center_id" character varying NULL, "domain_type" character varying NOT NULL DEFAULT 'UNKNOWN', PRIMARY KEY ("id"));
-- Create index "customdomainhistory_history_time" to table: "custom_domain_history"
CREATE INDEX "customdomainhistory_history_time" ON "custom_domain_history" ("history_time");
-- Create "discussion_history" table
CREATE TABLE "discussion_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "owner_id" character varying NULL, "external_id" character varying NULL, "is_resolved" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"));
-- Create index "discussionhistory_history_time" to table: "discussion_history"
CREATE INDEX "discussionhistory_history_time" ON "discussion_history" ("history_time");
-- Create "document_data_history" table
CREATE TABLE "document_data_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "template_id" character varying NULL, "data" jsonb NOT NULL, PRIMARY KEY ("id"));
-- Create index "documentdatahistory_history_time" to table: "document_data_history"
CREATE INDEX "documentdatahistory_history_time" ON "document_data_history" ("history_time");
-- Create "email_template_history" table
CREATE TABLE "email_template_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "revision" character varying NULL DEFAULT 'v0.0.1', "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "key" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "format" character varying NULL DEFAULT 'HTML', "locale" character varying NOT NULL DEFAULT 'en-US', "subject_template" character varying NULL, "preheader_template" character varying NULL, "body_template" text NULL, "text_template" text NULL, "jsonconfig" jsonb NULL, "uischema" jsonb NULL, "metadata" jsonb NULL, "active" boolean NOT NULL DEFAULT true, "version" bigint NOT NULL DEFAULT 1, "template_context" character varying NULL, "defaults" jsonb NULL, "integration_id" character varying NULL, "workflow_definition_id" character varying NULL, "workflow_instance_id" character varying NULL, "trust_center_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "emailtemplatehistory_history_time" to table: "email_template_history"
CREATE INDEX "emailtemplatehistory_history_time" ON "email_template_history" ("history_time");
-- Create "entity_history" table
CREATE TABLE "entity_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "internal_owner" character varying NULL, "internal_owner_user_id" character varying NULL, "internal_owner_group_id" character varying NULL, "reviewed_by" character varying NULL, "reviewed_by_user_id" character varying NULL, "reviewed_by_group_id" character varying NULL, "last_reviewed_at" timestamptz NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "entity_relationship_state_name" character varying NULL, "entity_relationship_state_id" character varying NULL, "entity_security_questionnaire_status_name" character varying NULL, "entity_security_questionnaire_status_id" character varying NULL, "entity_source_type_name" character varying NULL, "entity_source_type_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "name" citext NULL, "display_name" character varying NULL, "description" character varying NULL, "domains" jsonb NULL, "aliases" jsonb NULL, "entity_type_id" character varying NULL, "status" character varying NULL DEFAULT 'ACTIVE', "approved_for_use" boolean NULL DEFAULT false, "linked_asset_ids" jsonb NULL, "has_soc2" boolean NULL DEFAULT false, "soc2_period_end" timestamptz NULL, "contract_start_date" timestamptz NULL, "contract_end_date" timestamptz NULL, "auto_renews" boolean NULL DEFAULT false, "termination_notice_days" bigint NULL, "annual_spend" double precision NULL, "spend_currency" character varying NULL DEFAULT 'USD', "billing_model" character varying NULL, "renewal_risk" character varying NULL, "sso_enforced" boolean NULL DEFAULT false, "mfa_supported" boolean NULL DEFAULT false, "mfa_enforced" boolean NULL DEFAULT false, "status_page_url" character varying NULL, "provided_services" jsonb NULL, "links" jsonb NULL, "risk_rating" character varying NULL, "risk_score" bigint NULL, "risk_score_coverage" bigint NULL, "tier" character varying NULL DEFAULT 'LOW', "review_frequency" character varying NULL DEFAULT 'YEARLY', "next_review_at" timestamptz NULL, "contract_renewal_at" timestamptz NULL, "vendor_metadata" jsonb NULL, "logo_remote_url" character varying NULL, "logo_file_id" character varying NULL, "external_id" character varying NULL, "observed_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "entityhistory_history_time" to table: "entity_history"
CREATE INDEX "entityhistory_history_time" ON "entity_history" ("history_time");
-- Create "entity_type_history" table
CREATE TABLE "entity_type_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "name" citext NOT NULL, PRIMARY KEY ("id"));
-- Create index "entitytypehistory_history_time" to table: "entity_type_history"
CREATE INDEX "entitytypehistory_history_time" ON "entity_type_history" ("history_time");
-- Create "evidence_history" table
CREATE TABLE "evidence_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "external_uuid" character varying NULL, "name" character varying NOT NULL, "description" character varying NULL, "collection_procedure" text NULL, "creation_date" timestamptz NOT NULL, "renewal_date" timestamptz NULL, "source" character varying NULL, "is_automated" boolean NULL DEFAULT false, "url" character varying NULL, "status" character varying NULL, "review_frequency" character varying NULL DEFAULT 'YEARLY', PRIMARY KEY ("id"));
-- Create index "evidencehistory_history_time" to table: "evidence_history"
CREATE INDEX "evidencehistory_history_time" ON "evidence_history" ("history_time");
-- Create "file_history" table
CREATE TABLE "file_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "category_name" character varying NULL, "category_id" character varying NULL, "name" character varying NULL, "provided_file_name" character varying NOT NULL, "provided_file_extension" character varying NOT NULL, "provided_file_size" bigint NULL, "persisted_file_size" bigint NULL, "detected_mime_type" character varying NULL, "md5_hash" character varying NULL, "detected_content_type" character varying NOT NULL, "store_key" character varying NULL, "category_type" character varying NULL, "uri" character varying NULL, "storage_scheme" character varying NULL, "storage_volume" character varying NULL, "storage_path" character varying NULL, "file_contents" bytea NULL, "metadata" jsonb NULL, "storage_region" character varying NULL, "storage_provider" character varying NULL, "last_accessed_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "filehistory_history_time" to table: "file_history"
CREATE INDEX "filehistory_history_time" ON "file_history" ("history_time");
-- Create "finding_control_history" table
CREATE TABLE "finding_control_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "owner_id" character varying NULL, "finding_id" character varying NOT NULL, "control_id" character varying NOT NULL, "standard_id" character varying NULL, "external_standard" character varying NULL, "external_standard_version" character varying NULL, "external_control_id" character varying NULL, "source" character varying NULL, "metadata" jsonb NULL, "discovered_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "findingcontrolhistory_history_time" to table: "finding_control_history"
CREATE INDEX "findingcontrolhistory_history_time" ON "finding_control_history" ("history_time");
-- Create "finding_history" table
CREATE TABLE "finding_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "reviewed_by" character varying NULL, "reviewed_by_user_id" character varying NULL, "reviewed_by_group_id" character varying NULL, "assigned_to" character varying NULL, "assigned_to_user_id" character varying NULL, "assigned_to_group_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "finding_status_name" character varying NULL, "finding_status_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "external_id" character varying NULL, "security_level" character varying NULL DEFAULT 'NONE', "external_owner_id" character varying NULL, "source" character varying NULL, "resource_name" character varying NULL, "display_name" character varying NULL, "state" character varying NULL, "category" character varying NULL, "categories" jsonb NULL, "finding_class" character varying NULL, "severity" character varying NULL, "numeric_severity" double precision NULL, "score" double precision NULL, "impact" double precision NULL, "exploitability" double precision NULL, "priority" character varying NULL, "open" boolean NULL DEFAULT true, "blocks_production" boolean NULL, "production" boolean NULL, "public" boolean NULL, "validated" boolean NULL, "assessment_id" character varying NULL, "description" text NULL, "recommendation" text NULL, "recommended_actions" text NULL, "references" jsonb NULL, "steps_to_reproduce" jsonb NULL, "targets" jsonb NULL, "target_details" jsonb NULL, "vector" character varying NULL, "remediation_sla" bigint NULL, "event_time" timestamptz NULL, "reported_at" timestamptz NULL, "source_updated_at" timestamptz NULL, "external_uri" character varying NULL, "metadata" jsonb NULL, "raw_payload" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "findinghistory_history_time" to table: "finding_history"
CREATE INDEX "findinghistory_history_time" ON "finding_history" ("history_time");
-- Create "group_history" table
CREATE TABLE "group_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "name" citext NOT NULL, "description" character varying NULL, "is_managed" boolean NULL DEFAULT false, "gravatar_logo_url" character varying NULL, "logo_url" character varying NULL, "avatar_local_file_id" character varying NULL, "display_name" character varying NOT NULL DEFAULT '', "oscal_role" character varying NULL, "oscal_party_uuid" character varying NULL, "oscal_contact_uuids" jsonb NULL, "scim_external_id" character varying NULL, "scim_display_name" character varying NULL, "scim_active" boolean NULL DEFAULT true, "scim_group_mailing" character varying NULL, PRIMARY KEY ("id"));
-- Create index "grouphistory_history_time" to table: "group_history"
CREATE INDEX "grouphistory_history_time" ON "group_history" ("history_time");
-- Create "group_membership_history" table
CREATE TABLE "group_membership_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "role" character varying NOT NULL DEFAULT 'MEMBER', "group_id" character varying NOT NULL, "user_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "groupmembershiphistory_history_time" to table: "group_membership_history"
CREATE INDEX "groupmembershiphistory_history_time" ON "group_membership_history" ("history_time");
-- Create "group_setting_history" table
CREATE TABLE "group_setting_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "visibility" character varying NOT NULL DEFAULT 'PUBLIC', "join_policy" character varying NOT NULL DEFAULT 'INVITE_OR_APPLICATION', "sync_to_slack" boolean NULL DEFAULT false, "sync_to_github" boolean NULL DEFAULT false, "group_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "groupsettinghistory_history_time" to table: "group_setting_history"
CREATE INDEX "groupsettinghistory_history_time" ON "group_setting_history" ("history_time");
-- Create "hush_history" table
CREATE TABLE "hush_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "name" character varying NOT NULL, "description" character varying NULL, "kind" character varying NULL, "secret_name" character varying NULL, "secret_value" character varying NULL, "credential_set" jsonb NULL, "metadata" jsonb NULL, "last_used_at" timestamptz NULL, "expires_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "hushhistory_history_time" to table: "hush_history"
CREATE INDEX "hushhistory_history_time" ON "hush_history" ("history_time");
-- Create "identity_holder_history" table
CREATE TABLE "identity_holder_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "internal_owner" character varying NULL, "internal_owner_user_id" character varying NULL, "internal_owner_group_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "full_name" character varying NOT NULL, "email" character varying NOT NULL, "alternate_email" character varying NULL, "email_aliases" jsonb NULL, "phone_number" character varying NULL, "is_openlane_user" boolean NULL DEFAULT false, "user_id" character varying NULL, "identity_holder_type" character varying NOT NULL DEFAULT 'UNSPECIFIED', "status" character varying NOT NULL DEFAULT 'ACTIVE', "is_active" boolean NOT NULL DEFAULT true, "title" character varying NULL, "department" character varying NULL, "team" character varying NULL, "location" character varying NULL, "start_date" timestamptz NULL, "end_date" timestamptz NULL, "employer_entity_id" character varying NULL, "external_user_id" character varying NULL, "external_reference_id" character varying NULL, "metadata" jsonb NULL, "avatar_remote_url" character varying NULL, PRIMARY KEY ("id"));
-- Create index "identityholderhistory_history_time" to table: "identity_holder_history"
CREATE INDEX "identityholderhistory_history_time" ON "identity_holder_history" ("history_time");
-- Create "internal_policy_history" table
CREATE TABLE "internal_policy_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "revision" character varying NULL DEFAULT 'v0.0.1', "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "name" character varying NOT NULL, "status" character varying NULL DEFAULT 'DRAFT', "management_mode" character varying NULL DEFAULT 'OPENLANE_MANAGED', "details" text NULL, "details_json" jsonb NULL, "approval_required" boolean NULL DEFAULT true, "review_due" timestamptz NULL, "review_frequency" character varying NULL DEFAULT 'YEARLY', "approver_id" character varying NULL, "delegate_id" character varying NULL, "summary" character varying NULL, "tag_suggestions" jsonb NULL, "dismissed_tag_suggestions" jsonb NULL, "control_suggestions" jsonb NULL, "dismissed_control_suggestions" jsonb NULL, "improvement_suggestions" jsonb NULL, "dismissed_improvement_suggestions" jsonb NULL, "url" character varying NULL, "file_id" character varying NULL, "external_file_id" character varying NULL, "external_contents" character varying NULL, "internal_policy_kind_name" character varying NULL, "internal_policy_kind_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "external_uuid" character varying NULL, PRIMARY KEY ("id"));
-- Create index "internalpolicyhistory_history_time" to table: "internal_policy_history"
CREATE INDEX "internalpolicyhistory_history_time" ON "internal_policy_history" ("history_time");
-- Create "job_template_history" table
CREATE TABLE "job_template_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "title" character varying NOT NULL, "description" character varying NULL, "platform" character varying NOT NULL, "windmill_path" character varying NULL, "download_url" character varying NOT NULL, "configuration" jsonb NULL, "cron" character varying NULL, PRIMARY KEY ("id"));
-- Create index "jobtemplatehistory_history_time" to table: "job_template_history"
CREATE INDEX "jobtemplatehistory_history_time" ON "job_template_history" ("history_time");
-- Create "mappable_domain_history" table
CREATE TABLE "mappable_domain_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "name" character varying NOT NULL, "zone_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "mappabledomainhistory_history_time" to table: "mappable_domain_history"
CREATE INDEX "mappabledomainhistory_history_time" ON "mappable_domain_history" ("history_time");
-- Create "mapped_control_history" table
CREATE TABLE "mapped_control_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "owner_id" character varying NULL, "mapping_type" character varying NOT NULL DEFAULT 'EQUAL', "relation" character varying NULL, "confidence" bigint NULL, "source" character varying NULL DEFAULT 'MANUAL', PRIMARY KEY ("id"));
-- Create index "mappedcontrolhistory_history_time" to table: "mapped_control_history"
CREATE INDEX "mappedcontrolhistory_history_time" ON "mapped_control_history" ("history_time");
-- Create "narrative_history" table
CREATE TABLE "narrative_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "name" character varying NOT NULL, "description" text NULL, "details" text NULL, PRIMARY KEY ("id"));
-- Create index "narrativehistory_history_time" to table: "narrative_history"
CREATE INDEX "narrativehistory_history_time" ON "narrative_history" ("history_time");
-- Create "note_history" table
CREATE TABLE "note_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "owner_id" character varying NULL, "title" character varying NULL, "text" text NOT NULL, "text_json" jsonb NULL, "note_ref" character varying NULL, "discussion_id" character varying NULL, "is_edited" boolean NOT NULL DEFAULT false, "trust_center_id" character varying NULL, "notify_subscribers" boolean NULL DEFAULT false, "notified_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "notehistory_history_time" to table: "note_history"
CREATE INDEX "notehistory_history_time" ON "note_history" ("history_time");
-- Create "notification_preference_history" table
CREATE TABLE "notification_preference_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "owner_id" character varying NULL, "user_id" character varying NOT NULL, "channel" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'ENABLED', "provider" character varying NULL, "destination" character varying NULL, "config" jsonb NULL, "enabled" boolean NOT NULL DEFAULT true, "cadence" character varying NOT NULL DEFAULT 'IMMEDIATE', "priority" character varying NULL, "topic_patterns" jsonb NULL, "topic_overrides" jsonb NULL, "template_id" character varying NULL, "mute_until" timestamptz NULL, "quiet_hours_start" character varying NULL, "quiet_hours_end" character varying NULL, "timezone" character varying NULL, "is_default" boolean NOT NULL DEFAULT false, "verified_at" timestamptz NULL, "last_used_at" timestamptz NULL, "last_error" text NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "notificationpreferencehistory_history_time" to table: "notification_preference_history"
CREATE INDEX "notificationpreferencehistory_history_time" ON "notification_preference_history" ("history_time");
-- Create "notification_template_history" table
CREATE TABLE "notification_template_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "revision" character varying NULL DEFAULT 'v0.0.1', "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "key" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "channel" character varying NULL, "format" character varying NOT NULL DEFAULT 'MARKDOWN', "locale" character varying NOT NULL DEFAULT 'en-US', "topic_pattern" character varying NOT NULL, "integration_id" character varying NULL, "destinations" jsonb NULL, "workflow_definition_id" character varying NULL, "email_template_id" character varying NULL, "title_template" character varying NULL, "subject_template" character varying NULL, "body_template" text NULL, "blocks" jsonb NULL, "jsonconfig" jsonb NULL, "uischema" jsonb NULL, "metadata" jsonb NULL, "active" boolean NOT NULL DEFAULT true, "version" bigint NOT NULL DEFAULT 1, "template_context" character varying NULL, "defaults" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "notificationtemplatehistory_history_time" to table: "notification_template_history"
CREATE INDEX "notificationtemplatehistory_history_time" ON "notification_template_history" ("history_time");
-- Create "org_membership_history" table
CREATE TABLE "org_membership_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "role" character varying NOT NULL DEFAULT 'MEMBER', "organization_id" character varying NOT NULL, "user_id" character varying NOT NULL, "sso_exempt" boolean NULL DEFAULT false, "sso_exempt_reason" character varying NULL, "sso_exempt_granted_by" character varying NULL, "sso_exempt_granted_at" timestamptz NULL, "tfa_enforced" boolean NULL DEFAULT false, "tfa_enforced_reason" character varying NULL, "tfa_enforced_by" character varying NULL, "tfa_enforced_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "orgmembershiphistory_history_time" to table: "org_membership_history"
CREATE INDEX "orgmembershiphistory_history_time" ON "org_membership_history" ("history_time");
-- Create "organization_history" table
CREATE TABLE "organization_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "name" citext NOT NULL, "display_name" character varying NOT NULL DEFAULT '', "description" character varying NULL, "parent_organization_id" character varying NULL, "personal_org" boolean NULL DEFAULT false, "avatar_remote_url" character varying NULL, "avatar_local_file_id" character varying NULL, "avatar_updated_at" timestamptz NULL, "stripe_customer_id" character varying NULL, "slug_name" character varying NULL, PRIMARY KEY ("id"));
-- Create index "organizationhistory_history_time" to table: "organization_history"
CREATE INDEX "organizationhistory_history_time" ON "organization_history" ("history_time");
-- Create "organization_setting_history" table
CREATE TABLE "organization_setting_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "domains" jsonb NULL, "billing_contact" character varying NULL, "billing_email" character varying NULL, "billing_phone" character varying NULL, "billing_address" jsonb NULL, "tax_identifier" character varying NULL, "geo_location" character varying NULL DEFAULT 'AMER', "organization_id" character varying NULL, "billing_notifications_enabled" boolean NOT NULL DEFAULT true, "allowed_email_domains" jsonb NULL, "allow_matching_domains_autojoin" boolean NULL DEFAULT false, "identity_provider" character varying NULL DEFAULT 'NONE', "identity_provider_client_id" character varying NULL, "identity_provider_client_secret" character varying NULL, "identity_provider_metadata_endpoint" character varying NULL, "identity_provider_auth_tested" boolean NOT NULL DEFAULT false, "identity_provider_entity_id" character varying NULL, "oidc_discovery_endpoint" character varying NULL, "saml_signin_url" character varying NULL, "saml_issuer" character varying NULL, "saml_cert" text NULL, "identity_provider_login_enforced" boolean NOT NULL DEFAULT false, "identity_provider_jit_provisioning" boolean NOT NULL DEFAULT true, "jit_allowed_email_domains" jsonb NULL, "multifactor_auth_enforced" boolean NULL DEFAULT false, "sso_exempt_domains" jsonb NULL, "allow_support_access" boolean NULL DEFAULT false, "compliance_webhook_token" character varying NULL, "payment_method_added" boolean NOT NULL DEFAULT false, "pending_deletion_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "organizationsettinghistory_history_time" to table: "organization_setting_history"
CREATE INDEX "organizationsettinghistory_history_time" ON "organization_setting_history" ("history_time");
-- Create "platform_history" table
CREATE TABLE "platform_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "internal_owner" character varying NULL, "internal_owner_user_id" character varying NULL, "internal_owner_group_id" character varying NULL, "business_owner" character varying NULL, "business_owner_user_id" character varying NULL, "business_owner_group_id" character varying NULL, "technical_owner" character varying NULL, "technical_owner_user_id" character varying NULL, "technical_owner_group_id" character varying NULL, "security_owner" character varying NULL, "security_owner_user_id" character varying NULL, "security_owner_group_id" character varying NULL, "platform_kind_name" character varying NULL, "platform_kind_id" character varying NULL, "platform_data_classification_name" character varying NULL, "platform_data_classification_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "access_model_name" character varying NULL, "access_model_id" character varying NULL, "encryption_status_name" character varying NULL, "encryption_status_id" character varying NULL, "security_tier_name" character varying NULL, "security_tier_id" character varying NULL, "criticality_name" character varying NULL, "criticality_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "external_uuid" character varying NULL, "name" character varying NOT NULL, "description" character varying NULL, "business_purpose" character varying NULL, "scope_statement" text NULL, "trust_boundary_description" text NULL, "data_flow_summary" text NULL, "status" character varying NOT NULL DEFAULT 'ACTIVE', "physical_location" character varying NULL, "region" character varying NULL, "contains_pii" boolean NULL DEFAULT false, "source_type" character varying NOT NULL DEFAULT 'MANUAL', "source_identifier" character varying NULL, "cost_center" character varying NULL, "estimated_monthly_cost" double precision NULL, "purchase_date" timestamptz NULL, "platform_owner_id" character varying NULL, "external_reference_id" character varying NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "platformhistory_history_time" to table: "platform_history"
CREATE INDEX "platformhistory_history_time" ON "platform_history" ("history_time");
-- Create "procedure_history" table
CREATE TABLE "procedure_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "revision" character varying NULL DEFAULT 'v0.0.1', "owner_id" character varying NULL, "name" character varying NOT NULL, "status" character varying NULL DEFAULT 'DRAFT', "management_mode" character varying NULL DEFAULT 'OPENLANE_MANAGED', "details" text NULL, "details_json" jsonb NULL, "approval_required" boolean NULL DEFAULT true, "review_due" timestamptz NULL, "review_frequency" character varying NULL DEFAULT 'YEARLY', "approver_id" character varying NULL, "delegate_id" character varying NULL, "summary" character varying NULL, "tag_suggestions" jsonb NULL, "dismissed_tag_suggestions" jsonb NULL, "control_suggestions" jsonb NULL, "dismissed_control_suggestions" jsonb NULL, "improvement_suggestions" jsonb NULL, "dismissed_improvement_suggestions" jsonb NULL, "url" character varying NULL, "file_id" character varying NULL, "external_file_id" character varying NULL, "external_contents" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "procedure_kind_name" character varying NULL, "procedure_kind_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, PRIMARY KEY ("id"));
-- Create index "procedurehistory_history_time" to table: "procedure_history"
CREATE INDEX "procedurehistory_history_time" ON "procedure_history" ("history_time");
-- Create "program_history" table
CREATE TABLE "program_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "program_kind_name" character varying NULL, "program_kind_id" character varying NULL, "external_uuid" character varying NULL, "name" character varying NOT NULL, "description" character varying NULL, "status" character varying NOT NULL DEFAULT 'NOT_STARTED', "framework_name" character varying NULL, "start_date" timestamptz NULL, "end_date" timestamptz NULL, "observation_period_start_date" timestamptz NULL, "observation_period_end_date" timestamptz NULL, "fieldwork_start_date" timestamptz NULL, "fieldwork_end_date" timestamptz NULL, "auditor_ready" boolean NOT NULL DEFAULT false, "auditor_write_comments" boolean NOT NULL DEFAULT false, "auditor_read_comments" boolean NOT NULL DEFAULT false, "audit_firm" character varying NULL, "auditor" character varying NULL, "auditor_email" character varying NULL, "program_owner_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "programhistory_history_time" to table: "program_history"
CREATE INDEX "programhistory_history_time" ON "program_history" ("history_time");
-- Create "program_membership_history" table
CREATE TABLE "program_membership_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "role" character varying NOT NULL DEFAULT 'MEMBER', "program_id" character varying NOT NULL, "user_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "programmembershiphistory_history_time" to table: "program_membership_history"
CREATE INDEX "programmembershiphistory_history_time" ON "program_membership_history" ("history_time");
-- Create "remediation_history" table
CREATE TABLE "remediation_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "external_id" character varying NULL, "external_owner_id" character varying NULL, "title" character varying NULL, "status" character varying NULL DEFAULT 'IN_PROGRESS', "state" character varying NULL, "intent" character varying NULL, "summary" text NULL, "explanation" text NULL, "instructions" text NULL, "owner_reference" character varying NULL, "repository_uri" character varying NULL, "pull_request_uri" character varying NULL, "ticket_reference" character varying NULL, "due_at" timestamptz NULL, "completed_at" timestamptz NULL, "pr_generated_at" timestamptz NULL, "error" text NULL, "source" character varying NULL, "external_uri" character varying NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "remediationhistory_history_time" to table: "remediation_history"
CREATE INDEX "remediationhistory_history_time" ON "remediation_history" ("history_time");
-- Create "review_history" table
CREATE TABLE "review_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "external_id" character varying NULL, "external_owner_id" character varying NULL, "title" character varying NOT NULL, "state" character varying NULL, "status" character varying NULL DEFAULT 'OPEN', "category" character varying NULL, "classification" character varying NULL, "summary" text NULL, "details" text NULL, "reporter" character varying NULL, "approved" boolean NULL DEFAULT false, "reviewed_at" timestamptz NULL, "reported_at" timestamptz NULL, "approved_at" timestamptz NULL, "reviewer_id" character varying NULL, "source" character varying NULL, "external_uri" character varying NULL, "metadata" jsonb NULL, "raw_payload" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "reviewhistory_history_time" to table: "review_history"
CREATE INDEX "reviewhistory_history_time" ON "review_history" ("history_time");
-- Create "risk_history" table
CREATE TABLE "risk_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "risk_kind_name" character varying NULL, "risk_kind_id" character varying NULL, "risk_category_name" character varying NULL, "risk_category_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "external_id" character varying NULL, "integration_id" character varying NULL, "observed_at" timestamptz NULL, "external_uuid" character varying NULL, "name" character varying NOT NULL, "status" character varying NULL, "impact" character varying NULL, "likelihood" character varying NULL DEFAULT 'LIKELY', "score" bigint NULL, "mitigation" text NULL, "mitigation_json" jsonb NULL, "details" text NULL, "details_json" jsonb NULL, "business_costs" text NULL, "business_costs_json" jsonb NULL, "stakeholder_id" character varying NULL, "delegate_id" character varying NULL, "mitigated_at" timestamptz NULL, "review_required" boolean NULL DEFAULT true, "last_reviewed_at" timestamptz NULL, "review_frequency" character varying NULL DEFAULT 'YEARLY', "due_date" timestamptz NULL, "next_review_due_at" timestamptz NULL, "residual_score" bigint NULL, "risk_decision" character varying NULL DEFAULT 'NONE', PRIMARY KEY ("id"));
-- Create index "riskhistory_history_time" to table: "risk_history"
CREATE INDEX "riskhistory_history_time" ON "risk_history" ("history_time");
-- Create "sla_definition_history" table
CREATE TABLE "sla_definition_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "sla_days" bigint NOT NULL, "security_level" character varying NOT NULL DEFAULT 'NONE', PRIMARY KEY ("id"));
-- Create index "sladefinitionhistory_history_time" to table: "sla_definition_history"
CREATE INDEX "sladefinitionhistory_history_time" ON "sla_definition_history" ("history_time");
-- Create "scheduled_job_history" table
CREATE TABLE "scheduled_job_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "owner_id" character varying NULL, "job_id" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, "configuration" jsonb NULL, "cron" character varying NULL, "job_runner_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "scheduledjobhistory_history_time" to table: "scheduled_job_history"
CREATE INDEX "scheduledjobhistory_history_time" ON "scheduled_job_history" ("history_time");
-- Create "standard_history" table
CREATE TABLE "standard_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "revision" character varying NULL DEFAULT 'v0.0.1', "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "name" character varying NOT NULL, "short_name" character varying NULL, "framework" text NULL, "description" text NULL, "governing_body_logo_url" character varying NULL, "governing_body" character varying NULL, "domains" jsonb NULL, "link" character varying NULL, "status" character varying NULL DEFAULT 'ACTIVE', "is_public" boolean NULL DEFAULT false, "free_to_use" boolean NULL DEFAULT false, "standard_type" character varying NULL, "version" character varying NULL, "logo_file_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "standardhistory_history_time" to table: "standard_history"
CREATE INDEX "standardhistory_history_time" ON "standard_history" ("history_time");
-- Create "subcontrol_history" table
CREATE TABLE "subcontrol_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "external_uuid" character varying NULL, "title" character varying NULL, "description" text NULL, "description_json" jsonb NULL, "aliases" jsonb NULL, "reference_id" character varying NULL, "auditor_reference_id" character varying NULL, "responsible_party_id" character varying NULL, "status" character varying NULL DEFAULT 'NOT_IMPLEMENTED', "implementation_status" character varying NULL DEFAULT 'PLANNED', "implementation_description" text NULL, "public_representation" text NULL, "source" character varying NULL DEFAULT 'USER_DEFINED', "source_name" character varying NULL, "reference_framework" character varying NULL, "reference_framework_revision" character varying NULL, "category" character varying NULL, "category_id" character varying NULL, "subcategory" character varying NULL, "mapped_categories" jsonb NULL, "assessment_objectives" jsonb NULL, "assessment_methods" jsonb NULL, "control_questions" jsonb NULL, "implementation_guidance" jsonb NULL, "example_evidence" jsonb NULL, "references" jsonb NULL, "testing_procedures" jsonb NULL, "evidence_requests" jsonb NULL, "control_owner_id" character varying NULL, "delegate_id" character varying NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "subcontrol_kind_name" character varying NULL, "subcontrol_kind_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "ref_code" character varying NOT NULL, "control_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "subcontrolhistory_history_time" to table: "subcontrol_history"
CREATE INDEX "subcontrolhistory_history_time" ON "subcontrol_history" ("history_time");
-- Create "subprocessor_history" table
CREATE TABLE "subprocessor_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "name" character varying NOT NULL, "description" text NULL, "logo_remote_url" character varying NULL, "logo_file_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "subprocessorhistory_history_time" to table: "subprocessor_history"
CREATE INDEX "subprocessorhistory_history_time" ON "subprocessor_history" ("history_time");
-- Create "system_detail_history" table
CREATE TABLE "system_detail_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_name" character varying NOT NULL, "version" character varying NULL, "description" text NULL, "authorization_boundary" text NULL, "sensitivity_level" character varying NULL DEFAULT 'UNKNOWN', "last_reviewed" timestamptz NULL, "revision_history" jsonb NULL, "oscal_metadata_json" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "systemdetailhistory_history_time" to table: "system_detail_history"
CREATE INDEX "systemdetailhistory_history_time" ON "system_detail_history" ("history_time");
-- Create "task_history" table
CREATE TABLE "task_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "task_kind_name" character varying NULL, "task_kind_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "external_uuid" character varying NULL, "title" character varying NOT NULL, "details" text NULL, "details_json" jsonb NULL, "metadata" jsonb NULL, "status" character varying NOT NULL DEFAULT 'OPEN', "due" timestamptz NULL, "completed" timestamptz NULL, "assignee_id" character varying NULL, "assigner_id" character varying NULL, "system_generated" boolean NOT NULL DEFAULT false, "is_template" boolean NOT NULL DEFAULT false, "is_suggested" boolean NOT NULL DEFAULT false, "priority" bigint NOT NULL DEFAULT 0, "source" character varying NULL, "source_key" character varying NULL, "idempotency_key" character varying NULL, "external_reference_url" jsonb NULL, "parent_task_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "taskhistory_history_time" to table: "task_history"
CREATE INDEX "taskhistory_history_time" ON "task_history" ("history_time");
-- Create "template_history" table
CREATE TABLE "template_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "name" character varying NOT NULL, "template_type" character varying NOT NULL DEFAULT 'DOCUMENT', "description" character varying NULL, "kind" character varying NULL DEFAULT 'QUESTIONNAIRE', "jsonconfig" jsonb NOT NULL, "uischema" jsonb NULL, "trust_center_id" character varying NULL, "transform_configuration" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "templatehistory_history_time" to table: "template_history"
CREATE INDEX "templatehistory_history_time" ON "template_history" ("history_time");
-- Create "trust_center_compliance_history" table
CREATE TABLE "trust_center_compliance_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "standard_id" character varying NOT NULL, "trust_center_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "trustcentercompliancehistory_history_time" to table: "trust_center_compliance_history"
CREATE INDEX "trustcentercompliancehistory_history_time" ON "trust_center_compliance_history" ("history_time");
-- Create "trust_center_doc_history" table
CREATE TABLE "trust_center_doc_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "trust_center_doc_kind_name" character varying NULL, "trust_center_doc_kind_id" character varying NULL, "trust_center_id" character varying NULL, "title" character varying NOT NULL, "file_id" character varying NULL, "original_file_id" character varying NULL, "watermarking_enabled" boolean NULL, "watermark_status" character varying NULL DEFAULT 'PENDING', "visibility" character varying NULL DEFAULT 'NOT_VISIBLE', "standard_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "trustcenterdochistory_history_time" to table: "trust_center_doc_history"
CREATE INDEX "trustcenterdochistory_history_time" ON "trust_center_doc_history" ("history_time");
-- Create "trust_center_entity_history" table
CREATE TABLE "trust_center_entity_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "logo_file_id" character varying NULL, "url" character varying NULL, "trust_center_id" character varying NULL, "name" character varying NOT NULL, "entity_type_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "trustcenterentityhistory_history_time" to table: "trust_center_entity_history"
CREATE INDEX "trustcenterentityhistory_history_time" ON "trust_center_entity_history" ("history_time");
-- Create "trust_center_faqs_history" table
CREATE TABLE "trust_center_faqs_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "trust_center_faq_kind_name" character varying NULL, "trust_center_faq_kind_id" character varying NULL, "note_id" character varying NOT NULL, "trust_center_id" character varying NULL, "reference_link" character varying NULL, "display_order" bigint NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create index "trustcenterfaqhistory_history_time" to table: "trust_center_faqs_history"
CREATE INDEX "trustcenterfaqhistory_history_time" ON "trust_center_faqs_history" ("history_time");
-- Create "trust_center_history" table
CREATE TABLE "trust_center_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "slug" character varying NULL, "custom_domain_id" character varying NULL, "preview_domain_id" character varying NULL, "pirsch_domain_id" character varying NULL, "pirsch_identification_code" character varying NULL, "pirsch_access_link" character varying NULL, "preview_status" character varying NULL DEFAULT 'NONE', "subprocessor_url" character varying NULL, PRIMARY KEY ("id"));
-- Create index "trustcenterhistory_history_time" to table: "trust_center_history"
CREATE INDEX "trustcenterhistory_history_time" ON "trust_center_history" ("history_time");
-- Create "trust_center_nda_request_history" table
CREATE TABLE "trust_center_nda_request_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "trust_center_id" character varying NULL, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "email" character varying NOT NULL, "company_name" character varying NULL, "reason" character varying NULL, "access_level" character varying NULL DEFAULT 'FULL', "status" character varying NULL DEFAULT 'REQUESTED', "approved_at" timestamptz NULL, "approved_by_user_id" character varying NULL, "signed_at" timestamptz NULL, "document_data_id" character varying NULL, "file_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "trustcenterndarequesthistory_history_time" to table: "trust_center_nda_request_history"
CREATE INDEX "trustcenterndarequesthistory_history_time" ON "trust_center_nda_request_history" ("history_time");
-- Create "trust_center_setting_history" table
CREATE TABLE "trust_center_setting_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "trust_center_id" character varying NULL, "title" character varying NULL, "company_name" character varying NULL, "company_description" character varying NULL, "overview" text NULL, "logo_remote_url" character varying NULL, "logo_local_file_id" character varying NULL, "favicon_remote_url" character varying NULL, "favicon_local_file_id" character varying NULL, "hero_image_local_file_id" character varying NULL, "theme_mode" character varying NULL DEFAULT 'EASY', "primary_color" character varying NULL, "font" character varying NULL, "foreground_color" character varying NULL, "background_color" character varying NULL, "accent_color" character varying NULL, "secondary_background_color" character varying NULL, "secondary_foreground_color" character varying NULL, "environment" character varying NULL DEFAULT 'LIVE', "remove_branding" boolean NULL DEFAULT false, "company_domain" character varying NULL, "security_contact" character varying NULL, "nda_approval_required" boolean NULL DEFAULT false, "allow_subscribers" boolean NULL DEFAULT true, "notify_subscribers_on_subprocessor_change" boolean NULL DEFAULT false, "subprocessors_notified_at" timestamptz NULL, "nda_approver_group_id" character varying NULL, "status_page_url" character varying NULL, PRIMARY KEY ("id"));
-- Create index "trustcentersettinghistory_history_time" to table: "trust_center_setting_history"
CREATE INDEX "trustcentersettinghistory_history_time" ON "trust_center_setting_history" ("history_time");
-- Create "trust_center_subprocessor_history" table
CREATE TABLE "trust_center_subprocessor_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "trust_center_subprocessor_kind_name" character varying NULL, "trust_center_subprocessor_kind_id" character varying NULL, "subprocessor_id" character varying NOT NULL, "trust_center_id" character varying NULL, "countries" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "trustcentersubprocessorhistory_history_time" to table: "trust_center_subprocessor_history"
CREATE INDEX "trustcentersubprocessorhistory_history_time" ON "trust_center_subprocessor_history" ("history_time");
-- Create "trust_center_watermark_config_history" table
CREATE TABLE "trust_center_watermark_config_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "owner_id" character varying NULL, "trust_center_id" character varying NULL, "is_enabled" boolean NULL DEFAULT true, "logo_id" character varying NULL, "text" character varying NULL, "font_size" double precision NULL DEFAULT 48, "opacity" double precision NULL DEFAULT 0.3, "rotation" double precision NULL DEFAULT 45, "color" character varying NULL DEFAULT '#808080', "font" character varying NULL DEFAULT 'HELVETICA', PRIMARY KEY ("id"));
-- Create index "trustcenterwatermarkconfighistory_history_time" to table: "trust_center_watermark_config_history"
CREATE INDEX "trustcenterwatermarkconfighistory_history_time" ON "trust_center_watermark_config_history" ("history_time");
-- Create "user_history" table
CREATE TABLE "user_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "email" character varying NOT NULL, "first_name" character varying NULL, "last_name" character varying NULL, "display_name" character varying NOT NULL, "avatar_remote_url" character varying NULL, "avatar_local_file_id" character varying NULL, "avatar_updated_at" timestamptz NULL, "last_seen" timestamptz NULL, "last_login_provider" character varying NULL, "password" character varying NULL, "sub" character varying NULL, "auth_provider" character varying NOT NULL DEFAULT 'CREDENTIALS', "role" character varying NULL DEFAULT 'USER', "scim_external_id" character varying NULL, "scim_username" character varying NULL, "scim_active" boolean NULL DEFAULT true, "scim_preferred_language" character varying NULL, "scim_locale" character varying NULL, PRIMARY KEY ("id"));
-- Create index "userhistory_history_time" to table: "user_history"
CREATE INDEX "userhistory_history_time" ON "user_history" ("history_time");
-- Create "user_setting_history" table
CREATE TABLE "user_setting_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "user_id" character varying NULL, "delegate_user_id" character varying NULL, "delegate_start_at" timestamptz NULL, "delegate_end_at" timestamptz NULL, "locked" boolean NOT NULL DEFAULT false, "silenced_at" timestamptz NULL, "suspended_at" timestamptz NULL, "status" character varying NOT NULL DEFAULT 'ACTIVE', "email_confirmed" boolean NOT NULL DEFAULT false, "is_webauthn_allowed" boolean NULL DEFAULT false, "is_tfa_enabled" boolean NULL DEFAULT false, "phone_number" character varying NULL, PRIMARY KEY ("id"));
-- Create index "usersettinghistory_history_time" to table: "user_setting_history"
CREATE INDEX "usersettinghistory_history_time" ON "user_setting_history" ("history_time");
-- Create "vendor_risk_score_history" table
CREATE TABLE "vendor_risk_score_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "question_key" character varying NOT NULL, "question_name" character varying NOT NULL, "question_description" character varying NULL, "question_category" character varying NOT NULL, "answer_type" character varying NOT NULL, "impact" character varying NOT NULL, "likelihood" character varying NOT NULL, "score" double precision NOT NULL DEFAULT 0, "answer" character varying NULL, "notes" character varying NULL, "vendor_scoring_config_id" character varying NULL, "entity_id" character varying NOT NULL, "assessment_response_id" character varying NULL, PRIMARY KEY ("id"));
-- Create index "vendorriskscorehistory_history_time" to table: "vendor_risk_score_history"
CREATE INDEX "vendorriskscorehistory_history_time" ON "vendor_risk_score_history" ("history_time");
-- Create "vendor_scoring_config_history" table
CREATE TABLE "vendor_scoring_config_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "questions" jsonb NOT NULL, "scoring_mode" character varying NOT NULL DEFAULT 'ANSWERED_ONLY', "risk_thresholds" jsonb NOT NULL, PRIMARY KEY ("id"));
-- Create index "vendorscoringconfighistory_history_time" to table: "vendor_scoring_config_history"
CREATE INDEX "vendorscoringconfighistory_history_time" ON "vendor_scoring_config_history" ("history_time");
-- Create "vulnerability_history" table
CREATE TABLE "vulnerability_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "reviewed_by" character varying NULL, "reviewed_by_user_id" character varying NULL, "reviewed_by_group_id" character varying NULL, "assigned_to" character varying NULL, "assigned_to_user_id" character varying NULL, "assigned_to_group_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "vulnerability_status_name" character varying NULL, "vulnerability_status_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "external_owner_id" character varying NULL, "security_level" character varying NULL DEFAULT 'NONE', "external_id" character varying NOT NULL, "cve_id" character varying NULL, "source" character varying NULL, "display_name" character varying NULL, "category" character varying NULL, "severity" character varying NULL, "score" double precision NULL, "impact" double precision NULL, "exploitability" double precision NULL, "priority" character varying NULL, "summary" text NULL, "description" text NULL, "vector" character varying NULL, "remediation_sla" bigint NULL, "open" boolean NULL DEFAULT true, "blocking" boolean NULL DEFAULT false, "production" boolean NULL, "public" boolean NULL, "validated" boolean NULL, "references" jsonb NULL, "impacts" jsonb NULL, "cwe_ids" jsonb NULL, "vulnerable_version_range" character varying NULL, "first_patched_version" character varying NULL, "fix_available" boolean NULL, "package_name" character varying NULL, "package_ecosystem" character varying NULL, "manifest_path" character varying NULL, "dependency_scope" character varying NULL, "published_at" timestamptz NULL, "discovered_at" timestamptz NULL, "source_updated_at" timestamptz NULL, "dismissed_at" timestamptz NULL, "dismissed_reason" character varying NULL, "dismissed_comment" text NULL, "fixed_at" timestamptz NULL, "auto_dismissed_at" timestamptz NULL, "external_uri" character varying NULL, "metadata" jsonb NULL, "raw_payload" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "vulnerabilityhistory_history_time" to table: "vulnerability_history"
CREATE INDEX "vulnerabilityhistory_history_time" ON "vulnerability_history" ("history_time");
-- Create "workflow_assignment_history" table
CREATE TABLE "workflow_assignment_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "workflow_instance_id" character varying NOT NULL, "assignment_key" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'APPROVER', "label" character varying NULL, "required" boolean NOT NULL DEFAULT true, "status" character varying NOT NULL DEFAULT 'PENDING', "metadata" jsonb NULL, "approval_metadata" jsonb NULL, "rejection_metadata" jsonb NULL, "invalidation_metadata" jsonb NULL, "outcome_metadata" jsonb NULL, "decided_at" timestamptz NULL, "actor_user_id" character varying NULL, "actor_group_id" character varying NULL, "notes" text NULL, "due_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "workflowassignmenthistory_history_time" to table: "workflow_assignment_history"
CREATE INDEX "workflowassignmenthistory_history_time" ON "workflow_assignment_history" ("history_time");
-- Create "workflow_assignment_target_history" table
CREATE TABLE "workflow_assignment_target_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "workflow_assignment_id" character varying NOT NULL, "target_type" character varying NOT NULL, "target_user_id" character varying NULL, "target_group_id" character varying NULL, "resolver_key" character varying NULL, PRIMARY KEY ("id"));
-- Create index "workflowassignmenttargethistory_history_time" to table: "workflow_assignment_target_history"
CREATE INDEX "workflowassignmenttargethistory_history_time" ON "workflow_assignment_target_history" ("history_time");
-- Create "workflow_definition_history" table
CREATE TABLE "workflow_definition_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "updated_by_impersonator" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "name" character varying NOT NULL, "description" text NULL, "workflow_kind" character varying NOT NULL, "schema_type" character varying NOT NULL, "revision" bigint NOT NULL DEFAULT 1, "draft" boolean NOT NULL DEFAULT true, "published_at" timestamptz NULL, "cooldown_seconds" bigint NOT NULL DEFAULT 0, "is_default" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, "trigger_operations" jsonb NULL, "trigger_fields" jsonb NULL, "approval_fields" jsonb NULL, "approval_edges" jsonb NULL, "approval_submission_mode" character varying NULL DEFAULT 'AUTO_SUBMIT', "definition_json" jsonb NULL, "tracked_fields" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "workflowdefinitionhistory_history_time" to table: "workflow_definition_history"
CREATE INDEX "workflowdefinitionhistory_history_time" ON "workflow_definition_history" ("history_time");
