# Add 'bug' label to any PR where the head branch name starts with `bug` or has a `bug` section in the name
bug:
  - head-branch: ["^bug", "bug"]
# Add 'enhancement' label to any PR where the head branch name starts with `enhancement` or has a `enhancement` section in the name
enhancement:
  - head-branch: ["^enhancement", "enhancement", "^feature", "feature", "^enhance", "enhance", "^feat", "feat"]
# Add 'breaking-change' label to any PR where the head branch name starts with `breaking-change` or has a `breaking-change` section in the name
breaking-change:
  - head-branch: ["^breaking-change", "breaking-change"]
# Add 'dependencies' label to any PR where the head branch name starts with `dependencies` or has a `dependencies` section in the name
dependencies:
  - head-branch: ["^dependencies", "dependencies", "^deps", "deps", "renovate", "dependabot"]
ci:
  - changed-files:
      - any-glob-to-any-file: .github/**
      - any-glob-to-any-file: .buildkite/**
mixin:
  - changed-files:
      - any-glob-to-any-file: internal/ent/mixin/**
      - any-glob-to-any-file: internal/ent/schema/mixin_*.go
privacy:
  - changed-files:
      - any-glob-to-any-file: internal/ent/privacy/**
dbschema:
  - changed-files:
      - any-glob-to-any-file: internal/ent/schema/**
      - any-glob-to-any-file: internal/ent/historyschema/**
      - any-glob-to-any-file: db/**
graphqlschema:
  - changed-files:
      - any-glob-to-any-file: internal/graphapi/schema/**
migrations:
  - changed-files:
      - any-glob-to-any-file: db/**
local-development:
  - changed-files:
      - any-glob-to-any-file: scripts/**
      - any-glob-to-any-file: Taskfile.yaml
      - any-glob-to-any-file: docker/**
cli:
  - changed-files:
      - any-glob-to-any-file: cli/**
common:
  - changed-files:
      - any-glob-to-any-file: common/**
authorization:
  - changed-files:
      - any-glob-to-any-file: fga/**
httpserve:
  - changed-files:
      - any-glob-to-any-file: internal/httpserve/**
graphapi:
  - changed-files:
      - any-glob-to-any-file: internal/graphapi/**
      - any-glob-to-any-file: internal/graphapi/**/**
codegenerators:
  - changed-files:
      - any-glob-to-any-file: internal/graphapi/generate/gen_schema.go
      - any-glob-to-any-file: internal/graphapi/generate/generate.go
      - any-glob-to-any-file: internal/graphapi/generate/.gqlgen.yml
      - any-glob-to-any-file: internal/graphapi/generate/.gqlgenc.yml
      - any-glob-to-any-file: internal/ent/generate/entc.go
      - any-glob-to-any-file: internal/ent/templates/**
config:
  - changed-files:
      - any-glob-to-any-file: config/**
      - any-glob-to-any-file: jsonschema/**
