run:
  timeout: 15m
  allow-serial-runners: true
  concurrency: 0
  tests: false
linters-settings:
  goimports:
    local-prefixes: github.com/theopenlane/core
  gofumpt:
    extra-rules: true
  gosec:
    exclude-generated: true
  revive:
    ignore-generated-header: true
linters:
  enable:
    # default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # additional linters
    - bodyclose
    - gocritic
    - gocyclo
    - err113
    - gofmt
    - goimports
    - mnd
    - gosec
    - misspell
    - noctx
    - revive
    - stylecheck
    - typecheck
    - whitespace
    - wsl
issues:
  exclude-use-default: true
  exclude-dirs:
    - pkg/testutils/*
    - .buildkite/*
    - .github/*
    - docker/*
    - internal/ent/generated/*
    - jsonschema/templates/*
    - pkg/objects/mocks/*
    - schema/*
    - query/*
    - fga/model/*
    - fga/tests/*
    - docs/*
    - internal/graphapi/generate/*
    - db/migrations/*
    - db/migrations-goose-postgres/*
  exclude-files:
    - internal/graphapi/gen_server.go
    - internal/graphapi/gen_models.go
    - internal/openlaneclient/graphclient.go
    - pkg/openlaneclient/graphclient.go
    - schema.graphql
output:
  show-stats: true
