version: "2"
run:
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
issues:
  new: true
  new-from-rev: HEAD~
linters:
  enable:
    - bodyclose
    - err113
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - mnd
    - noctx
    - revive
    - whitespace
    - wsl
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments # uncomment this after fixing all comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: ".*\\.generated\\.go"
        linters: ["*"]
      - path: "pkg/openlaneclient/graphclient.go"
        linters: ["*"]
      - path: "pkg/openlaneclient/models.go"
        linters: ["*"]
      - path: "pkg/testutils/.*"
        linters: ["*"]
      - path: "internal/ent/generated/.*"
        linters: ["*"]
      - path: "internal/ent/templates/.*"
        linters: ["*"]
      - path: "jsonschema/templates/.*"
        linters: ["*"]
      - path: "pkg/objects/mocks/.*"
        linters: ["*"]
      - path: "internal/graphapi/generate/.*"
        linters: ["*"]
      - path: "internal/graphapi/generated/.*"
        linters: ["*"]
      - path: "internal/graphapi/directives/.*"
        linters: ["*"]
      - path: "internal/graphapi/model/.*"
        linters: ["*"]
      - path: "pkg/entitlements/test/.*"
        linters: ["*"]
      - path: "cmd/cli/cmd/.*"
        linters: ["*"]
      - path: "pkg/sleuth/static/.*"
        linters: ["*"]
      - path: "pkg/entitlements/mocks/.*"
        linters: ["*"]
      - path: "pkg/events/soiree/examples/.*"
        linters: ["*"]
      - path: "pkg/middleware/ratelimiter/examples/.*"
        linters: ["*"]
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    warn-unused: true
    paths:
      - internal/graphapi/model/gen_models.go
      - pkg/openlaneclient/graphclient.go
      - pkg/testutils/*
      - pkg/entitlements/test/*
      - cmd/cli/cmd/*
      - pkg/events/soiree/examples/*
      - pkg/sleuth/dnsx/* # this should be fixed in the future
