version: "2"
run:
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - err113
    - gocritic
    - gosec
    - misspell
    - mnd
    - noctx
    - revive
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments # undisable this after fixing all comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/graphapi/model/gen_models.go
      - pkg/testutils/*
      - ent/generated/*
      - ent/templates/*
      - jsonschema/templates/*
      - pkg/objects/mocks/*
      - internal/graphapi/generate/*
      - internal/graphapi/generated/*
      - pkg/entitlements/test/*
      - cmd/cli/cmd/*
      - pkg/entitlements/mocks/*
      - pkg/events/soiree/examples/*
      - pkg/middleware/ratelimiter/examples/*
      - ent/hush/examples/*
      - pkg/objects/examples/*
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    warn-unused: true
    paths:
      - internal/graphapi/model/gen_models.go
      - pkg/testutils/*
      - pkg/entitlements/test/*
      - cmd/cli/cmd/*
      - pkg/events/soiree/examples/*
      - ent/hush/examples/*
