version: "2"
run:
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - err113
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - mnd
    - noctx
    - revive
    - staticcheck
    - whitespace
    - wsl
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - common-false-positives
      - legacy
    paths:
      - internal/graphapi/model/gen_models.go
      - pkg/openlaneclient/graphclient.go
      - pkg/testutils/*
      - internal/ent/generated/*
      - pkg/objects/mocks/*
      - internal/graphapi/generate/*
      - internal/graphapi/generated/*
      - pkg/entitlements/test/*
      - cmd/cli/cmd/*
      - pkg/sleuth/static/*
      - pkg/entitlements/mocks/*
      - pkg/events/soiree/examples/*
      - pkg/middleware/ratelimiter/examples/*
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/theopenlane/core
  exclusions:
    generated: lax
