version: "2"
run:
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
  build-tags:
    - codegen
linters:
  enable:
    - bodyclose
    - err113
    - gocritic
    - gosec
    - misspell
    - mnd
    - noctx
    - revive
  exclusions:
    generated: lax
    warn-unused: false
    presets:
      - comments # undisable this after fixing all comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/graphapi/testclient
      - internal/graphapi/model/
      - internal/graphapi/historymodel
      - internal/ent/generated
      - internal/ent/authzgenerated
      - internal/ent/historygenerated
      - internal/ent/historyschema
      - internal/httpserve/handlers/test_webfinger
      - pkg/corejobs/internal/cloudflare/mocks
      - pkg/corejobs/internal/olclient/mocks
      - pkg/corejobs/internal/pirsch/mocks
      - pkg/middleware/ratelimit/examples
      - pkg/entitlements/test
      - pkg/entitlements/mocks
      - pkg/objects/mocks
      - pkg/events/soiree/examples
      - pkg/objects/examples
      - pkg/corejobs/test
      - pkg/testutils
      - internal/graphapi/generated
      - internal/graphapi/historygenerated
      - db
      - jsonschema
      - cmd
      - pkg/middleware
      - internal/httpserve/handlers/internal
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
