version: "2"
run:
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - err113
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - mnd
    - noctx
    - revive
    - staticcheck
    - whitespace
    - wsl
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - common-false-positives
      - legacy
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - wsl
          - whitespace
      - path: internal/ent/generated/*.go
        linters:
          - wsl
          - whitespace
      - path: internal/graphapi/generated/*.go
        linters:
          - wsl
          - whitespace
      - path: internal/graphapi/model/*.go
        linters:
          - wsl
          - whitespace
      - path: pkg/objects/mocks/*.go
        linters:
          - wsl
          - whitespace
    paths:
      - internal/graphapi/model/gen_models.go
      - pkg/openlaneclient/graphclient.go
      - schema.graphql
      - pkg/testutils/*
      - .buildkite/*
      - .github/*
      - docker/*
      - internal/ent/generated/*
      - internal/ent/templates/*
      - jsonschema/templates/*
      - pkg/objects/mocks/*
      - schema/*
      - query/*
      - fga/model/*
      - fga/tests/*
      - docs/*
      - internal/graphapi/generate/*
      - internal/graphapi/generated/*
      - db/migrations/*
      - db/migrations-goose-postgres/*
      - pkg/entitlements/test/*
      - cmd/cli/cmd/*
      - pkg/sleuth/static/*
      - pkg/entitlements/mocks/*
      - third_party$
      - builtin$
      - examples$
      - pkg/events/soiree/examples/*
      - pkg/middleware/ratelimiter/examples/*
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/theopenlane/core
  exclusions:
    generated: lax
    paths:
      - internal/graphapi/model/gen_models.go
      - pkg/openlaneclient/graphclient.go
      - schema.graphql
      - pkg/testutils/*
      - .buildkite/*
      - .github/*
      - docker/*
      - internal/ent/generated/*
      - internal/ent/templates/*
      - jsonschema/templates/*
      - pkg/objects/mocks/*
      - schema/*
      - query/*
      - fga/model/*
      - fga/tests/*
      - docs/*
      - internal/graphapi/generate/*
      - internal/graphapi/generated/*
      - db/migrations/*
      - db/migrations-goose-postgres/*
      - pkg/entitlements/test/*
      - cmd/cli/cmd/*
      - pkg/sleuth/static/*
      - pkg/entitlements/mocks/*
      - third_party$
      - builtin$
      - examples$
