version: "2"
run:
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - err113
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - mnd
    - noctx
    - revive
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments # undisable this after fixing all comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/graphapi/model/gen_models.go
      - pkg/openlaneclient/graphclient.go
      - pkg/testutils/*
      - internal/ent/generated/*
      - internal/ent/templates/*
      - jsonschema/templates/*
      - pkg/objects/mocks/*
      - pkg/corejobs/internal/cloudflare/mocks/*
      - pkg/corejobs/internal/olclient/mocks/*
      - internal/graphapi/generate/*
      - internal/graphapi/generated/*
      - pkg/entitlements/test/*
      - cmd/cli/cmd/*
      - pkg/sleuth/static/*
      - pkg/entitlements/mocks/*
      - pkg/events/soiree/examples/*
      - pkg/middleware/ratelimiter/examples/*
      - internal/ent/hush/examples/*
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    warn-unused: true
    paths:
      - internal/graphapi/model/gen_models.go
      - pkg/openlaneclient/graphclient.go
      - pkg/testutils/*
      - pkg/entitlements/test/*
      - cmd/cli/cmd/*
      - pkg/events/soiree/examples/*
      - pkg/sleuth/dnsx/* # this should be fixed in the future
      - internal/ent/hush/examples/*
