version: "2"
run:
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
  skip-dirs:
    - internal/ent/generated
    - internal/graphapi/generated
    - internal/graphapi/model
    - pkg/entitlements/mocks
    - pkg/entitlements/test
    - pkg/objects/mocks
    - pkg/sleuth/static
    - pkg/testutils
    - cmd/cli/cmd
    - pkg/events/soiree/examples
    - pkg/middleware/ratelimiter/examples
linters:
  enable:
    - bodyclose
    - err113
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - mnd
    - noctx
    - revive
    - staticcheck
    - whitespace
    - wsl
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - common-false-positives
      - legacy
    paths:
      - internal/graphapi/model/gen_models.go
      - pkg/openlaneclient/graphclient.go
      - pkg/testutils/*
      - internal/ent/generated/*
      - pkg/objects/mocks/*
      - internal/graphapi/generate/*
      - internal/graphapi/generated/*
      - pkg/entitlements/test/*
      - cmd/cli/cmd/*
      - pkg/sleuth/static/*
      - pkg/entitlements/mocks/*
      - pkg/events/soiree/examples/*
      - pkg/middleware/ratelimiter/examples/*
formatters:
  disable: true
