run:
  timeout: 15m
  allow-serial-runners: true
  concurrency: 0
linters-settings:
  goimports:
    local-prefixes: github.com/theopenlane/core
  gofumpt:
    extra-rules: true
  gosec:
    exclude-generated: true
  revive:
    ignore-generated-header: true
linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gocyclo
    - err113
    - gofmt
    - goimports
    - mnd
    - gosimple
    - govet
    - gosec
    - ineffassign
    - misspell
    - noctx
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unused
    - whitespace
    - wsl
issues:
  fix: true
  exclude-use-default: true
  exclude-dirs:
    - pkg/testutils/*
    - .buildkite/*
    - .github/*
    - docker/*
    - internal/ent/generated/*
    - jsonschema/templates/*
    - pkg/objects/mocks/*
    - schema/*
    - query/*
    - fga/*
    - docs/*
    - internal/graphapi/generate/*
  exclude-files:
    - internal/graphapi/gen_server.go
    - internal/graphapi/gen_models.go
    - internal/openlaneclient/graphclient.go
    - pkg/openlaneclient/graphclient.go
