version: "2"
run:
  modules-download-mode: readonly
  tests: false
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - err113
    - gocritic
    - gosec
    - misspell
    - mnd
    - noctx
    - revive
    - wsl_v5
    - whitespace
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments # undisable this after fixing all comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/graphapi/testclient
      - internal/graphapi/model/
      - internal/graphapi/historymodel
      - internal/ent/generated
      - internal/ent/authzgenerated
      - internal/ent/historygenerated
      - internal/ent/historyschema
      - internal/httpserve/handlers/test_webfinger
      - internal/ent/hush/examples
      - pkg/middleware/ratelimit/examples
      - pkg/entitlements/test
      - pkg/entitlements/mocks
      - pkg/objects/mocks
      - pkg/events/soiree/examples
      - pkg/objects/examples
      - internal/testutils
      - internal/graphapi/generated
      - internal/graphapi/historygenerated
      - internal/httpserve/handlers/internal
formatters:
  enable:
    - gofmt
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
  exclusions:
    generated: lax
    paths:
      - internal/graphapi/generated/gen_models.go
      - internal/graphapi/historygenerated/gen_models.go
      - internal/testutils/*
      - pkg/entitlements/test/*
      - cli/cmd/*
      - pkg/events/soiree/examples/*
      - internal/ent/hush/examples/*
issues:
  fix: true
