version: 2
project_name: openlane
builds:
  - env:
      - CGO_ENABLED=1
    binary: openlane
    flags:
      - -trimpath
      - -tags=netgo
    goos:
      - linux
    main: ./cmd/cli
archives:
  - formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
