project_name: openlane
builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    binary: openlane
    flags:
      - -trimpath
      - -tags=netgo
    ldflags:
      - "-X main.Version={{ .Env.VERSION }}"
      - "-X main.Commit={{ .Env.COMMIT }}"
      - "-X main.CommitDate={{ .Env.COMMIT_DATE }}"
      - "-X main.TreeState={{ .Env.TREE_STATE }}"
      - "-X github.com/theopenlane/core/internal/constants.CLIVersion={{ .Env.VERSION }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1
      - goos: darwin
        goarch: amd64
        goamd64: v1
        env:
          - CGO_ENABLED=1
    main: ./cmd/cli
archives:
  - format: tar.gz # we can use binary, but it seems there's an issue where goreleaser skips the sboms
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
brews:
  - homepage: 'https://github.com/theopenlane/core'
    description: 'openlane is the client CLI for interacting with the openlane server'
    directory: Formula
    license: 'Apache-2.0'
    commit_author:
      name: theopenlane-bender
      email: bender@theopenlane.io
    repository:
      owner: theopenlane
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    test: |
      system "#{bin}/openlane --help"
source:
  enabled: true
changelog:
  sort: asc
  use: github
sboms:
  - artifacts: archive
release:
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  prerelease: auto
  github:
    owner: theopenlane
    name: openlane
# This section defines how and which artifacts we want to sign for the release.
signs:
  - cmd: cosign
    args:
      - "sign-blob"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign >= 2.0.0
    artifacts: archive
    output: true
