version: 2
project_name: openlane
builds:
  - env:
      - CGO_ENABLED=0
    binary: openlane
    flags:
      - -trimpath
      - -tags=netgo
    ldflags:
      - "-X main.Version={{ .Env.VERSION }}"
      - "-X main.Commit={{ .Env.COMMIT }}"
      - "-X main.CommitDate={{ .Env.COMMIT_DATE }}"
      - "-X main.TreeState={{ .Env.TREE_STATE }}"
      - "-X github.com/theopenlane/core/internal/constants.CLIVersion={{ .Env.VERSION }}"
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1
      - goos: darwin
        goarch: amd64
        goamd64: v1
        env:
          - CGO_ENABLED=1
    main: ./cmd/cli
archives:
  - formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
