package graphapi

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql"
	"github.com/theopenlane/core/internal/ent/generated"
	"github.com/theopenlane/core/internal/ent/generated/campaigntarget"
	"github.com/theopenlane/core/internal/graphapi/common"
	"github.com/theopenlane/core/internal/graphapi/model"
	"github.com/theopenlane/core/pkg/logx"
	"github.com/theopenlane/utils/rout"
)

// HasPendingWorkflow is the resolver for the hasPendingWorkflow field.
func (r *campaignTargetResolver) HasPendingWorkflow(ctx context.Context, obj *generated.CampaignTarget) (bool, error) {
	panic(fmt.Errorf("not implemented: HasPendingWorkflow - hasPendingWorkflow"))
}

// ActiveWorkflowInstance is the resolver for the activeWorkflowInstance field.
func (r *campaignTargetResolver) ActiveWorkflowInstance(ctx context.Context, obj *generated.CampaignTarget) (*generated.WorkflowInstance, error) {
	panic(fmt.Errorf("not implemented: ActiveWorkflowInstance - activeWorkflowInstance"))
}

// CreateCampaignTarget is the resolver for the createCampaignTarget field.
func (r *mutationResolver) CreateCampaignTarget(ctx context.Context, input generated.CreateCampaignTargetInput) (*model.CampaignTargetCreatePayload, error) {
	// set the organization in the auth context if its not done for us
	if err := common.SetOrganizationInAuthContext(ctx, input.OwnerID); err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to set organization in auth context")

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	res, err := withTransactionalMutation(ctx).CampaignTarget.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionCreate, Object: "campaigntarget"})
	}

	return &model.CampaignTargetCreatePayload{
		CampaignTarget: res,
	}, nil
}

// CreateBulkCampaignTarget is the resolver for the createBulkCampaignTarget field.
func (r *mutationResolver) CreateBulkCampaignTarget(ctx context.Context, input []*generated.CreateCampaignTargetInput) (*model.CampaignTargetBulkCreatePayload, error) {
	if len(input) == 0 {
		return nil, rout.NewMissingRequiredFieldError("input")
	}

	// set the organization in the auth context if its not done for us
	// this will choose the first input OwnerID when using a personal access token
	if err := common.SetOrganizationInAuthContextBulkRequest(ctx, input); err != nil {
		logx.FromContext(ctx).Err(err).Msg("failed to set organization in auth context")

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	return r.bulkCreateCampaignTarget(ctx, input)
}

// CreateBulkCSVCampaignTarget is the resolver for the createBulkCSVCampaignTarget field.
func (r *mutationResolver) CreateBulkCSVCampaignTarget(ctx context.Context, input graphql.Upload) (*model.CampaignTargetBulkCreatePayload, error) {
	data, err := common.UnmarshalBulkData[generated.CreateCampaignTargetInput](input)
	if err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to unmarshal bulk data")

		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionCreate, Object: "campaigntarget"})
	}

	if len(data) == 0 {
		return nil, rout.NewMissingRequiredFieldError("input")
	}

	// set the organization in the auth context if its not done for us
	// this will choose the first input OwnerID when using a personal access token
	if err := common.SetOrganizationInAuthContextBulkRequest(ctx, data); err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to set organization in auth context")

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	return r.bulkCreateCampaignTarget(ctx, data)
}

// UpdateCampaignTarget is the resolver for the updateCampaignTarget field.
func (r *mutationResolver) UpdateCampaignTarget(ctx context.Context, id string, input generated.UpdateCampaignTargetInput) (*model.CampaignTargetUpdatePayload, error) {
	res, err := withTransactionalMutation(ctx).CampaignTarget.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionUpdate, Object: "campaigntarget"})
	}

	// set the organization in the auth context if its not done for us
	if err := common.SetOrganizationInAuthContext(ctx, &res.OwnerID); err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to set organization in auth context")

		return nil, rout.ErrPermissionDenied
	}

	// setup update request
	req := res.Update().SetInput(input)

	res, err = req.Save(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionUpdate, Object: "campaigntarget"})
	}

	return &model.CampaignTargetUpdatePayload{
		CampaignTarget: res,
	}, nil
}

// DeleteCampaignTarget is the resolver for the deleteCampaignTarget field.
func (r *mutationResolver) DeleteCampaignTarget(ctx context.Context, id string) (*model.CampaignTargetDeletePayload, error) {
	if err := withTransactionalMutation(ctx).CampaignTarget.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionDelete, Object: "campaigntarget"})
	}

	if err := generated.CampaignTargetEdgeCleanup(ctx, id); err != nil {
		return nil, common.NewCascadeDeleteError(ctx, err)
	}

	return &model.CampaignTargetDeletePayload{
		DeletedID: id,
	}, nil
}

// CampaignTarget is the resolver for the campaignTarget field.
func (r *queryResolver) CampaignTarget(ctx context.Context, id string) (*generated.CampaignTarget, error) {
	query, err := withTransactionalMutation(ctx).CampaignTarget.Query().Where(campaigntarget.ID(id)).CollectFields(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionGet, Object: "campaigntarget"})
	}

	res, err := query.Only(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionGet, Object: "campaigntarget"})
	}

	return res, nil
}
