package graphapi

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/theopenlane/core/internal/ent/csvgenerated"
	"github.com/theopenlane/core/internal/ent/generated"
	"github.com/theopenlane/core/internal/ent/generated/program"
	"github.com/theopenlane/core/internal/graphapi/common"
	"github.com/theopenlane/core/internal/graphapi/model"
	"github.com/theopenlane/core/pkg/logx"
	"github.com/theopenlane/utils/rout"
)

// CreateProgram is the resolver for the createProgram field.
func (r *mutationResolver) CreateProgram(ctx context.Context, input generated.CreateProgramInput) (*model.ProgramCreatePayload, error) {
	// set the organization in the auth context if its not done for us
	ctx, err := common.SetOrganizationInAuthContext(ctx, input.OwnerID)
	if err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to set organization in auth context")

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	res, err := withTransactionalMutation(ctx).Program.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionCreate, Object: "program"})
	}

	return &model.ProgramCreatePayload{
		Program: res,
	}, nil
}

// CreateBulkProgram is the resolver for the createBulkProgram field.
func (r *mutationResolver) CreateBulkProgram(ctx context.Context, input []*generated.CreateProgramInput) (*model.ProgramBulkCreatePayload, error) {
	if len(input) == 0 {
		return nil, rout.NewMissingRequiredFieldError("input")
	}

	// set the organization in the auth context if its not done for us
	// this will choose the first input OwnerID when using a personal access token
	ctx, err := common.SetOrganizationInAuthContextBulkRequest(ctx, input)
	if err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to set organization in auth context")

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	return r.bulkCreateProgram(ctx, input)
}

// CreateBulkCSVProgram is the resolver for the createBulkCSVProgram field.
func (r *mutationResolver) CreateBulkCSVProgram(ctx context.Context, input graphql.Upload) (*model.ProgramBulkCreatePayload, error) {
	data, err := common.UnmarshalBulkData[csvgenerated.ProgramCSVInput](input)
	if err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to unmarshal bulk data")

		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionCreate, Object: "program"})
	}

	if len(data) == 0 {
		return nil, rout.NewMissingRequiredFieldError("input")
	}

	// set the organization in the auth context if its not done for us
	// this will choose the first input OwnerID when using a personal access token
	ctx, err = common.SetOrganizationInAuthContextBulkRequest(ctx, data)
	if err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to set organization in auth context")

		if _, ownerErr := common.GetBulkUploadOwnerInput(data); ownerErr != nil {
			return nil, ownerErr
		}

		return nil, rout.ErrPermissionDenied
	}

	if err := resolveCSVReferencesForSchema(ctx, "Program", data); err != nil {
		return nil, err
	}

	inputs := make([]*generated.CreateProgramInput, 0, len(data))
	for i := range data {
		inputs = append(inputs, &data[i].Input)
	}

	return r.bulkCreateProgram(ctx, inputs)
}

// UpdateProgram is the resolver for the updateProgram field.
func (r *mutationResolver) UpdateProgram(ctx context.Context, id string, input generated.UpdateProgramInput) (*model.ProgramUpdatePayload, error) {
	res, err := withTransactionalMutation(ctx).Program.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionUpdate, Object: "program"})
	}

	// set the organization in the auth context if its not done for us
	ctx, err = common.SetOrganizationInAuthContext(ctx, &res.OwnerID)
	if err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to set organization in auth context")

		return nil, rout.ErrPermissionDenied
	}

	// setup update request
	req := res.Update().SetInput(input).AppendTags(input.AppendTags)

	res, err = req.Save(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionUpdate, Object: "program"})
	}

	return &model.ProgramUpdatePayload{
		Program: res,
	}, nil
}

// DeleteProgram is the resolver for the deleteProgram field.
func (r *mutationResolver) DeleteProgram(ctx context.Context, id string) (*model.ProgramDeletePayload, error) {
	if err := withTransactionalMutation(ctx).Program.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionDelete, Object: "program"})
	}

	if err := generated.ProgramEdgeCleanup(ctx, id); err != nil {
		return nil, common.NewCascadeDeleteError(ctx, err)
	}

	return &model.ProgramDeletePayload{
		DeletedID: id,
	}, nil
}

// DeleteBulkProgram is the resolver for the deleteBulkProgram field.
func (r *mutationResolver) DeleteBulkProgram(ctx context.Context, ids []string) (*model.ProgramBulkDeletePayload, error) {
	if len(ids) == 0 {
		return nil, rout.NewMissingRequiredFieldError("ids")
	}

	return r.bulkDeleteProgram(ctx, ids)
}

// UpdateBulkProgram is the resolver for the updateBulkProgram field.
func (r *mutationResolver) UpdateBulkProgram(ctx context.Context, ids []string, input generated.UpdateProgramInput) (*model.ProgramBulkUpdatePayload, error) {
	if len(ids) == 0 {
		return nil, rout.NewMissingRequiredFieldError("ids")
	}

	return r.bulkUpdateProgram(ctx, ids, input)
}

// UpdateBulkCSVProgram is the resolver for the updateBulkCSVProgram field.
func (r *mutationResolver) UpdateBulkCSVProgram(ctx context.Context, input graphql.Upload) (*model.ProgramBulkUpdatePayload, error) {
	data, err := common.UnmarshalBulkData[csvgenerated.ProgramCSVUpdateInput](input)
	if err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to unmarshal bulk data")

		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionUpdate, Object: "program"})
	}

	if len(data) == 0 {
		return nil, rout.NewMissingRequiredFieldError("input")
	}

	if err := resolveCSVReferencesForSchema(ctx, "Program", data); err != nil {
		return nil, err
	}

	return r.bulkUpdateCSVProgram(ctx, data)
}

// Program is the resolver for the program field.
func (r *queryResolver) Program(ctx context.Context, id string) (*generated.Program, error) {
	query, err := withTransactionalMutation(ctx).Program.Query().Where(program.ID(id)).CollectFields(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionGet, Object: "program"})
	}

	res, err := query.Only(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionGet, Object: "program"})
	}

	return res, nil
}
