package graphapi

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"encoding/json"

	"github.com/samber/lo"
	"github.com/theopenlane/core/common/models"
	gqlgenerated "github.com/theopenlane/core/internal/graphapi/generated"
	"github.com/theopenlane/core/internal/graphapi/model"
	emaildef "github.com/theopenlane/core/internal/integrations/definitions/email"
)

// TemplateContexts is the resolver for the templateContexts field.
func (r *queryResolver) TemplateContexts(ctx context.Context) ([]*models.TemplateContextEntry, error) {
	vars := emaildef.TemplateVariables()

	entries := lo.Map(vars, func(v models.TemplateVariable, _ int) *models.TemplateContextEntry {
		return &models.TemplateContextEntry{
			Description: v.Description,
		}
	})

	return entries, nil
}

// Schema is the resolver for the schema field.
func (r *templateContextEntryResolver) Schema(ctx context.Context, obj *models.TemplateContextEntry) (map[string]any, error) {
	if len(obj.Schema) == 0 {
		return nil, nil
	}

	var result map[string]any
	if err := json.Unmarshal(obj.Schema, &result); err != nil {
		return nil, err
	}

	return result, nil
}

// Variables is the resolver for the variables field.
func (r *templateContextEntryResolver) Variables(ctx context.Context, obj *models.TemplateContextEntry) ([]*model.TemplateVariable, error) {
	return lo.Map(obj.Variables, func(v models.TemplateVariable, _ int) *model.TemplateVariable {
		return &model.TemplateVariable{
			Name:        v.Name,
			Description: v.Description,
		}
	}), nil
}

// TemplateContextEntry returns gqlgenerated.TemplateContextEntryResolver implementation.
func (r *Resolver) TemplateContextEntry() gqlgenerated.TemplateContextEntryResolver {
	return &templateContextEntryResolver{r}
}

type templateContextEntryResolver struct{ *Resolver }
