package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/theopenlane/core/internal/ent/generated"
	"github.com/theopenlane/core/internal/ent/generated/trustcentercompliance"
	"github.com/theopenlane/core/internal/graphapi/model"
	"github.com/theopenlane/core/pkg/logx"
	"github.com/theopenlane/utils/rout"
)

// CreateTrustCenterCompliance is the resolver for the createTrustCenterCompliance field.
func (r *mutationResolver) CreateTrustCenterCompliance(ctx context.Context, input generated.CreateTrustCenterComplianceInput) (*model.TrustCenterComplianceCreatePayload, error) {
	if input.TrustCenterID == nil {
		// check if the organization has a trust center and set the id
		trustCenterID, err := withTransactionalMutation(ctx).TrustCenter.Query().OnlyID(ctx)
		if err != nil {
			return nil, parseRequestError(err, action{action: ActionCreate, object: "trustcentercompliance"})
		}

		if trustCenterID == "" {
			return nil, rout.NewMissingRequiredFieldError("trustCenterID")
		}

		logx.FromContext(ctx).Warn().Str("trust center id", trustCenterID).Msg("trustCenterID not provided, using organization's trust center")

		input.TrustCenterID = &trustCenterID

		// set the input in the graphql context
		// this isn't a required field, but its required by the access checks
		// so we need to set it early
		gCtx := graphql.GetFieldContext(ctx)
		gCtx.Args["input"] = input
	}

	res, err := withTransactionalMutation(ctx).TrustCenterCompliance.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionCreate, object: "trustcentercompliance"})
	}

	return &model.TrustCenterComplianceCreatePayload{
		TrustCenterCompliance: res,
	}, nil
}

// CreateBulkTrustCenterCompliance is the resolver for the createBulkTrustCenterCompliance field.
func (r *mutationResolver) CreateBulkTrustCenterCompliance(ctx context.Context, input []*generated.CreateTrustCenterComplianceInput) (*model.TrustCenterComplianceBulkCreatePayload, error) {
	if len(input) == 0 {
		return nil, rout.NewMissingRequiredFieldError("input")
	}

	return r.bulkCreateTrustCenterCompliance(ctx, input)
}

// CreateBulkCSVTrustCenterCompliance is the resolver for the createBulkCSVTrustCenterCompliance field.
func (r *mutationResolver) CreateBulkCSVTrustCenterCompliance(ctx context.Context, input graphql.Upload) (*model.TrustCenterComplianceBulkCreatePayload, error) {
	data, err := unmarshalBulkData[generated.CreateTrustCenterComplianceInput](input)
	if err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to unmarshal bulk data")

		return nil, err
	}

	if len(data) == 0 {
		return nil, rout.NewMissingRequiredFieldError("input")
	}

	return r.bulkCreateTrustCenterCompliance(ctx, data)
}

// UpdateTrustCenterCompliance is the resolver for the updateTrustCenterCompliance field.
func (r *mutationResolver) UpdateTrustCenterCompliance(ctx context.Context, id string, input generated.UpdateTrustCenterComplianceInput) (*model.TrustCenterComplianceUpdatePayload, error) {
	res, err := withTransactionalMutation(ctx).TrustCenterCompliance.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "trustcentercompliance"})
	}

	// setup update request
	req := res.Update().SetInput(input).AppendTags(input.AppendTags)

	res, err = req.Save(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionUpdate, object: "trustcentercompliance"})
	}

	return &model.TrustCenterComplianceUpdatePayload{
		TrustCenterCompliance: res,
	}, nil
}

// DeleteTrustCenterCompliance is the resolver for the deleteTrustCenterCompliance field.
func (r *mutationResolver) DeleteTrustCenterCompliance(ctx context.Context, id string) (*model.TrustCenterComplianceDeletePayload, error) {
	if err := withTransactionalMutation(ctx).TrustCenterCompliance.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, parseRequestError(err, action{action: ActionDelete, object: "trustcentercompliance"})
	}

	if err := generated.TrustCenterComplianceEdgeCleanup(ctx, id); err != nil {
		return nil, newCascadeDeleteError(err)
	}

	return &model.TrustCenterComplianceDeletePayload{
		DeletedID: id,
	}, nil
}

// DeleteBulkTrustCenterCompliance is the resolver for the deleteBulkTrustCenterCompliance field.
func (r *mutationResolver) DeleteBulkTrustCenterCompliance(ctx context.Context, ids []string) (*model.TrustCenterComplianceBulkDeletePayload, error) {
	if len(ids) == 0 {
		return nil, rout.NewMissingRequiredFieldError("ids")
	}

	return r.bulkDeleteTrustCenterCompliance(ctx, ids)
}

// TrustCenterCompliance is the resolver for the trustCenterCompliance field.
func (r *queryResolver) TrustCenterCompliance(ctx context.Context, id string) (*generated.TrustCenterCompliance, error) {
	query, err := withTransactionalMutation(ctx).TrustCenterCompliance.Query().Where(trustcentercompliance.ID(id)).CollectFields(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionGet, object: "trustcentercompliance"})
	}

	res, err := query.Only(ctx)
	if err != nil {
		return nil, parseRequestError(err, action{action: ActionGet, object: "trustcentercompliance"})
	}

	return res, nil
}
