package graphapi

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/theopenlane/core/internal/graphapi/common"
	"github.com/theopenlane/core/internal/graphapi/model"
	"github.com/theopenlane/core/pkg/logx"
	"github.com/theopenlane/utils/rout"
)

// CreateTrustCenterPreviewSetting is the resolver for the createTrustCenterPreviewSetting field.
func (r *mutationResolver) CreateTrustCenterPreviewSetting(ctx context.Context, input model.CreateTrustCenterPreviewSettingInput, logoFile *graphql.Upload, faviconFile *graphql.Upload) (*model.TrustCenterPreviewSettingCreatePayload, error) {
	transactionCtx := withTransactionalMutation(ctx)

	// Get the trust center to verify it exists and get the owner ID
	trustCenter, err := resolveTrustCenterForPreviewSetting(ctx, transactionCtx, input.TrustCenterID)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionCreate, Object: "trustcenterpreviewsetting"})
	}

	// Set the organization in the auth context if its not done for us
	if err := common.SetOrganizationInAuthContext(ctx, &trustCenter.OwnerID); err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to set organization in auth context")

		return nil, rout.ErrPermissionDenied
	}

	res, err := upsertPreviewSetting(ctx, transactionCtx, trustCenter, &input, nil)
	if err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to upsert trust center preview setting")
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionCreate, Object: "trustcenterpreviewsetting"})
	}

	return &model.TrustCenterPreviewSettingCreatePayload{
		TrustCenterSetting: res,
	}, nil
}
