package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/theopenlane/core/internal/ent/generated"
	"github.com/theopenlane/core/internal/ent/generated/workflowassignment"
	"github.com/theopenlane/core/internal/graphapi/model"
	"github.com/theopenlane/core/pkg/logx"
	"github.com/theopenlane/utils/rout"
)

// CreateWorkflowAssignment is the resolver for the createWorkflowAssignment field.
func (r *mutationResolver) CreateWorkflowAssignment(ctx context.Context, input generated.CreateWorkflowAssignmentInput) (*model.WorkflowAssignmentCreatePayload, error) {
	// set the organization in the auth context if its not done for us
	if err := setOrganizationInAuthContext(ctx, input.OwnerID); err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to set organization in auth context")

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	res, err := withTransactionalMutation(ctx).WorkflowAssignment.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, action{action: ActionCreate, object: "workflowassignment"})
	}

	return &model.WorkflowAssignmentCreatePayload{
		WorkflowAssignment: res,
	}, nil
}

// CreateBulkWorkflowAssignment is the resolver for the createBulkWorkflowAssignment field.
func (r *mutationResolver) CreateBulkWorkflowAssignment(ctx context.Context, input []*generated.CreateWorkflowAssignmentInput) (*model.WorkflowAssignmentBulkCreatePayload, error) {
	if len(input) == 0 {
		return nil, rout.NewMissingRequiredFieldError("input")
	}

	// set the organization in the auth context if its not done for us
	// this will choose the first input OwnerID when using a personal access token
	if err := setOrganizationInAuthContextBulkRequest(ctx, input); err != nil {
		logx.FromContext(ctx).Err(err).Msg("failed to set organization in auth context")

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	return r.bulkCreateWorkflowAssignment(ctx, input)
}

// CreateBulkCSVWorkflowAssignment is the resolver for the createBulkCSVWorkflowAssignment field.
func (r *mutationResolver) CreateBulkCSVWorkflowAssignment(ctx context.Context, input graphql.Upload) (*model.WorkflowAssignmentBulkCreatePayload, error) {
	data, err := unmarshalBulkData[generated.CreateWorkflowAssignmentInput](input)
	if err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to unmarshal bulk data")

		return nil, parseRequestError(ctx, err, action{action: ActionCreate, object: "workflowassignment"})
	}

	if len(data) == 0 {
		return nil, rout.NewMissingRequiredFieldError("input")
	}

	// set the organization in the auth context if its not done for us
	// this will choose the first input OwnerID when using a personal access token
	if err := setOrganizationInAuthContextBulkRequest(ctx, data); err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to set organization in auth context")

		return nil, rout.NewMissingRequiredFieldError("owner_id")
	}

	return r.bulkCreateWorkflowAssignment(ctx, data)
}

// UpdateWorkflowAssignment is the resolver for the updateWorkflowAssignment field.
func (r *mutationResolver) UpdateWorkflowAssignment(ctx context.Context, id string, input generated.UpdateWorkflowAssignmentInput) (*model.WorkflowAssignmentUpdatePayload, error) {
	res, err := withTransactionalMutation(ctx).WorkflowAssignment.Get(ctx, id)
	if err != nil {
		return nil, parseRequestError(ctx, err, action{action: ActionUpdate, object: "workflowassignment"})
	}

	// set the organization in the auth context if its not done for us
	if err := setOrganizationInAuthContext(ctx, &res.OwnerID); err != nil {
		logx.FromContext(ctx).Error().Err(err).Msg("failed to set organization in auth context")

		return nil, rout.ErrPermissionDenied
	}

	// setup update request
	req := res.Update().SetInput(input).AppendTags(input.AppendTags)

	res, err = req.Save(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, action{action: ActionUpdate, object: "workflowassignment"})
	}

	return &model.WorkflowAssignmentUpdatePayload{
		WorkflowAssignment: res,
	}, nil
}

// DeleteWorkflowAssignment is the resolver for the deleteWorkflowAssignment field.
func (r *mutationResolver) DeleteWorkflowAssignment(ctx context.Context, id string) (*model.WorkflowAssignmentDeletePayload, error) {
	if err := withTransactionalMutation(ctx).WorkflowAssignment.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, parseRequestError(ctx, err, action{action: ActionDelete, object: "workflowassignment"})
	}

	if err := generated.WorkflowAssignmentEdgeCleanup(ctx, id); err != nil {
		return nil, newCascadeDeleteError(ctx, err)
	}

	return &model.WorkflowAssignmentDeletePayload{
		DeletedID: id,
	}, nil
}

// WorkflowAssignment is the resolver for the workflowAssignment field.
func (r *queryResolver) WorkflowAssignment(ctx context.Context, id string) (*generated.WorkflowAssignment, error) {
	query, err := withTransactionalMutation(ctx).WorkflowAssignment.Query().Where(workflowassignment.ID(id)).CollectFields(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, action{action: ActionGet, object: "workflowassignment"})
	}

	res, err := query.Only(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, action{action: ActionGet, object: "workflowassignment"})
	}

	return res, nil
}
