package graphapi

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"entgo.io/contrib/entgql"
	"github.com/theopenlane/core/internal/ent/generated"
	"github.com/theopenlane/core/internal/graphapi/common"
	"github.com/theopenlane/core/internal/graphapi/model"
	"github.com/theopenlane/gqlgen-plugins/graphutils"
)

// ApproveWorkflowAssignment is the resolver for the approveWorkflowAssignment field.
func (r *mutationResolver) ApproveWorkflowAssignment(ctx context.Context, id string) (*model.WorkflowAssignmentApprovePayload, error) {
	panic(fmt.Errorf("not implemented: ApproveWorkflowAssignment - approveWorkflowAssignment"))
}

// RejectWorkflowAssignment is the resolver for the rejectWorkflowAssignment field.
func (r *mutationResolver) RejectWorkflowAssignment(ctx context.Context, id string, reason *string) (*model.WorkflowAssignmentRejectPayload, error) {
	panic(fmt.Errorf("not implemented: RejectWorkflowAssignment - rejectWorkflowAssignment"))
}

// MyWorkflowAssignments is the resolver for the myWorkflowAssignments field.
func (r *queryResolver) MyWorkflowAssignments(ctx context.Context, after *entgql.Cursor[string], first *int, before *entgql.Cursor[string], last *int, orderBy []*generated.WorkflowAssignmentOrder, where *generated.WorkflowAssignmentWhereInput) (*generated.WorkflowAssignmentConnection, error) {
	// set page limit if nothing was set
	first, last = graphutils.SetFirstLastDefaults(first, last, r.maxResultLimit)

	if orderBy == nil {
		orderBy = []*generated.WorkflowAssignmentOrder{
			{
				Field:     generated.WorkflowAssignmentOrderFieldCreatedAt,
				Direction: entgql.OrderDirectionDesc,
			},
		}
	}

	query, err := withTransactionalMutation(ctx).WorkflowAssignment.Query().CollectFields(ctx)
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionGet, Object: "workflowassignment"})
	}

	res, err := query.Paginate(
		ctx,
		after,
		first,
		before,
		last,
		generated.WithWorkflowAssignmentOrder(orderBy),
		generated.WithWorkflowAssignmentFilter(where.Filter))
	if err != nil {
		return nil, parseRequestError(ctx, err, common.Action{Action: common.ActionGet, Object: "workflowassignment"})
	}

	return res, err
}
