package graphapi

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/theopenlane/core/internal/ent/generated"
	"github.com/theopenlane/core/internal/graphapi/model"
)

// ProposalPreview is the resolver for the proposalPreview field.
func (r *workflowInstanceResolver) ProposalPreview(ctx context.Context, obj *generated.WorkflowInstance) (*model.WorkflowProposalPreview, error) {
	return r.workflowInstanceProposalPreview(ctx, obj)
}
