-- +goose Up
-- modify "assessment_response_history" table
ALTER TABLE "assessment_response_history" ADD COLUMN "campaign_id" character varying NULL, ADD COLUMN "identity_holder_id" character varying NULL, ADD COLUMN "entity_id" character varying NULL, ADD COLUMN "email_delivered_at" timestamptz NULL, ADD COLUMN "email_opened_at" timestamptz NULL, ADD COLUMN "email_clicked_at" timestamptz NULL, ADD COLUMN "email_open_count" bigint NULL DEFAULT 0, ADD COLUMN "email_click_count" bigint NULL DEFAULT 0, ADD COLUMN "last_email_event_at" timestamptz NULL, ADD COLUMN "email_metadata" jsonb NULL;
-- modify "asset_history" table
ALTER TABLE "asset_history" ADD COLUMN "internal_owner" character varying NULL, ADD COLUMN "internal_owner_user_id" character varying NULL, ADD COLUMN "internal_owner_group_id" character varying NULL, ADD COLUMN "asset_subtype_name" character varying NULL, ADD COLUMN "asset_subtype_id" character varying NULL, ADD COLUMN "asset_data_classification_name" character varying NULL, ADD COLUMN "asset_data_classification_id" character varying NULL, ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL, ADD COLUMN "access_model_name" character varying NULL, ADD COLUMN "access_model_id" character varying NULL, ADD COLUMN "encryption_status_name" character varying NULL, ADD COLUMN "encryption_status_id" character varying NULL, ADD COLUMN "security_tier_name" character varying NULL, ADD COLUMN "security_tier_id" character varying NULL, ADD COLUMN "criticality_name" character varying NULL, ADD COLUMN "criticality_id" character varying NULL, ADD COLUMN "physical_location" character varying NULL, ADD COLUMN "region" character varying NULL, ADD COLUMN "contains_pii" boolean NULL DEFAULT false, ADD COLUMN "source_type" character varying NOT NULL DEFAULT 'MANUAL', ADD COLUMN "source_platform_id" character varying NULL, ADD COLUMN "source_identifier" character varying NULL, ADD COLUMN "cost_center" character varying NULL, ADD COLUMN "estimated_monthly_cost" double precision NULL, ADD COLUMN "purchase_date" timestamptz NULL;
-- modify "control_history" table
ALTER TABLE "control_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "directory_account_history" table
ALTER TABLE "directory_account_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "directory_group_history" table
ALTER TABLE "directory_group_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "directory_membership_history" table
ALTER TABLE "directory_membership_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "document_data_history" table
ALTER TABLE "document_data_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "entity_history" table
ALTER TABLE "entity_history" ADD COLUMN "internal_owner" character varying NULL, ADD COLUMN "internal_owner_user_id" character varying NULL, ADD COLUMN "internal_owner_group_id" character varying NULL, ADD COLUMN "reviewed_by" character varying NULL, ADD COLUMN "reviewed_by_user_id" character varying NULL, ADD COLUMN "reviewed_by_group_id" character varying NULL, ADD COLUMN "last_reviewed_at" timestamptz NULL, ADD COLUMN "entity_relationship_state_name" character varying NULL, ADD COLUMN "entity_relationship_state_id" character varying NULL, ADD COLUMN "entity_security_questionnaire_status_name" character varying NULL, ADD COLUMN "entity_security_questionnaire_status_id" character varying NULL, ADD COLUMN "entity_source_type_name" character varying NULL, ADD COLUMN "entity_source_type_id" character varying NULL, ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL, ADD COLUMN "approved_for_use" boolean NULL DEFAULT false, ADD COLUMN "linked_asset_ids" jsonb NULL, ADD COLUMN "has_soc2" boolean NULL DEFAULT false, ADD COLUMN "soc2_period_end" timestamptz NULL, ADD COLUMN "contract_start_date" timestamptz NULL, ADD COLUMN "contract_end_date" timestamptz NULL, ADD COLUMN "auto_renews" boolean NULL DEFAULT false, ADD COLUMN "termination_notice_days" bigint NULL, ADD COLUMN "annual_spend" double precision NULL, ADD COLUMN "spend_currency" character varying NULL DEFAULT 'USD', ADD COLUMN "billing_model" character varying NULL, ADD COLUMN "renewal_risk" character varying NULL, ADD COLUMN "sso_enforced" boolean NULL DEFAULT false, ADD COLUMN "mfa_supported" boolean NULL DEFAULT false, ADD COLUMN "mfa_enforced" boolean NULL DEFAULT false, ADD COLUMN "status_page_url" character varying NULL, ADD COLUMN "provided_services" jsonb NULL, ADD COLUMN "links" jsonb NULL, ADD COLUMN "risk_rating" character varying NULL, ADD COLUMN "risk_score" bigint NULL, ADD COLUMN "tier" character varying NULL, ADD COLUMN "review_frequency" character varying NULL DEFAULT 'YEARLY', ADD COLUMN "next_review_at" timestamptz NULL, ADD COLUMN "contract_renewal_at" timestamptz NULL, ADD COLUMN "vendor_metadata" jsonb NULL;
-- modify "evidence_history" table
ALTER TABLE "evidence_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "file_history" table
ALTER TABLE "file_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "finding_history" table
ALTER TABLE "finding_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "integration_history" table
ALTER TABLE "integration_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "internal_policy_history" table
ALTER TABLE "internal_policy_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "procedure_history" table
ALTER TABLE "procedure_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "remediation_history" table
ALTER TABLE "remediation_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "review_history" table
ALTER TABLE "review_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "risk_history" table
ALTER TABLE "risk_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "scan_history" table
ALTER TABLE "scan_history" ADD COLUMN "reviewed_by" character varying NULL, ADD COLUMN "reviewed_by_user_id" character varying NULL, ADD COLUMN "reviewed_by_group_id" character varying NULL, ADD COLUMN "assigned_to" character varying NULL, ADD COLUMN "assigned_to_user_id" character varying NULL, ADD COLUMN "assigned_to_group_id" character varying NULL, ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL, ADD COLUMN "scan_date" timestamptz NULL, ADD COLUMN "scan_schedule" character varying NULL, ADD COLUMN "next_scan_run_at" timestamptz NULL, ADD COLUMN "performed_by" character varying NULL, ADD COLUMN "performed_by_user_id" character varying NULL, ADD COLUMN "performed_by_group_id" character varying NULL, ADD COLUMN "generated_by_platform_id" character varying NULL, ADD COLUMN "vulnerability_ids" jsonb NULL;
-- modify "task_history" table
ALTER TABLE "task_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "template_history" table
ALTER TABLE "template_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "vulnerability_history" table
ALTER TABLE "vulnerability_history" ADD COLUMN "environment_name" character varying NULL, ADD COLUMN "environment_id" character varying NULL, ADD COLUMN "scope_name" character varying NULL, ADD COLUMN "scope_id" character varying NULL;
-- modify "workflow_instance_history" table
ALTER TABLE "workflow_instance_history" ADD COLUMN "campaign_id" character varying NULL, ADD COLUMN "campaign_target_id" character varying NULL, ADD COLUMN "identity_holder_id" character varying NULL, ADD COLUMN "platform_id" character varying NULL;
-- modify "workflow_object_ref_history" table
ALTER TABLE "workflow_object_ref_history" ADD COLUMN "campaign_id" character varying NULL, ADD COLUMN "campaign_target_id" character varying NULL, ADD COLUMN "identity_holder_id" character varying NULL, ADD COLUMN "platform_id" character varying NULL;
-- create "campaign_history" table
CREATE TABLE "campaign_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "internal_owner" character varying NULL, "internal_owner_user_id" character varying NULL, "internal_owner_group_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "name" character varying NOT NULL, "description" character varying NULL, "campaign_type" character varying NOT NULL DEFAULT 'QUESTIONNAIRE', "status" character varying NOT NULL DEFAULT 'DRAFT', "is_active" boolean NOT NULL DEFAULT false, "scheduled_at" timestamptz NULL, "launched_at" timestamptz NULL, "completed_at" timestamptz NULL, "due_date" timestamptz NULL, "is_recurring" boolean NOT NULL DEFAULT false, "recurrence_frequency" character varying NULL, "recurrence_interval" bigint NULL DEFAULT 1, "recurrence_cron" character varying NULL, "recurrence_timezone" character varying NULL, "last_run_at" timestamptz NULL, "next_run_at" timestamptz NULL, "recurrence_end_at" timestamptz NULL, "recipient_count" bigint NULL DEFAULT 0, "resend_count" bigint NULL DEFAULT 0, "last_resent_at" timestamptz NULL, "template_id" character varying NULL, "entity_id" character varying NULL, "assessment_id" character varying NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- create index "campaignhistory_history_time" to table: "campaign_history"
CREATE INDEX "campaignhistory_history_time" ON "campaign_history" ("history_time");
-- create "campaign_target_history" table
CREATE TABLE "campaign_target_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "owner_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "campaign_id" character varying NOT NULL, "contact_id" character varying NULL, "user_id" character varying NULL, "group_id" character varying NULL, "email" character varying NOT NULL, "full_name" character varying NULL, "status" character varying NOT NULL DEFAULT 'NOT_STARTED', "sent_at" timestamptz NULL, "completed_at" timestamptz NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- create index "campaigntargethistory_history_time" to table: "campaign_target_history"
CREATE INDEX "campaigntargethistory_history_time" ON "campaign_target_history" ("history_time");
-- create "identity_holder_history" table
CREATE TABLE "identity_holder_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "internal_owner" character varying NULL, "internal_owner_user_id" character varying NULL, "internal_owner_group_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "full_name" character varying NOT NULL, "email" character varying NOT NULL, "alternate_email" character varying NULL, "phone_number" character varying NULL, "is_openlane_user" boolean NULL DEFAULT false, "user_id" character varying NULL, "identity_holder_type" character varying NOT NULL DEFAULT 'EMPLOYEE', "status" character varying NOT NULL DEFAULT 'ACTIVE', "is_active" boolean NOT NULL DEFAULT true, "title" character varying NULL, "department" character varying NULL, "team" character varying NULL, "location" character varying NULL, "start_date" timestamptz NULL, "end_date" timestamptz NULL, "employer_entity_id" character varying NULL, "external_user_id" character varying NULL, "external_reference_id" character varying NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- create index "identityholderhistory_history_time" to table: "identity_holder_history"
CREATE INDEX "identityholderhistory_history_time" ON "identity_holder_history" ("history_time");
-- create "platform_history" table
CREATE TABLE "platform_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "internal_owner" character varying NULL, "internal_owner_user_id" character varying NULL, "internal_owner_group_id" character varying NULL, "business_owner" character varying NULL, "business_owner_user_id" character varying NULL, "business_owner_group_id" character varying NULL, "technical_owner" character varying NULL, "technical_owner_user_id" character varying NULL, "technical_owner_group_id" character varying NULL, "security_owner" character varying NULL, "security_owner_user_id" character varying NULL, "security_owner_group_id" character varying NULL, "platform_kind_name" character varying NULL, "platform_kind_id" character varying NULL, "platform_data_classification_name" character varying NULL, "platform_data_classification_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "access_model_name" character varying NULL, "access_model_id" character varying NULL, "encryption_status_name" character varying NULL, "encryption_status_id" character varying NULL, "security_tier_name" character varying NULL, "security_tier_id" character varying NULL, "criticality_name" character varying NULL, "criticality_id" character varying NULL, "workflow_eligible_marker" boolean NULL DEFAULT true, "name" character varying NOT NULL, "description" character varying NULL, "business_purpose" character varying NULL, "scope_statement" text NULL, "trust_boundary_description" text NULL, "data_flow_summary" text NULL, "status" character varying NOT NULL DEFAULT 'ACTIVE', "physical_location" character varying NULL, "region" character varying NULL, "contains_pii" boolean NULL DEFAULT false, "source_type" character varying NOT NULL DEFAULT 'MANUAL', "source_identifier" character varying NULL, "cost_center" character varying NULL, "estimated_monthly_cost" double precision NULL, "purchase_date" timestamptz NULL, "platform_owner_id" character varying NULL, "external_reference_id" character varying NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- create index "platformhistory_history_time" to table: "platform_history"
CREATE INDEX "platformhistory_history_time" ON "platform_history" ("history_time");

-- +goose Down
-- reverse: create index "platformhistory_history_time" to table: "platform_history"
DROP INDEX "platformhistory_history_time";
-- reverse: create "platform_history" table
DROP TABLE "platform_history";
-- reverse: create index "identityholderhistory_history_time" to table: "identity_holder_history"
DROP INDEX "identityholderhistory_history_time";
-- reverse: create "identity_holder_history" table
DROP TABLE "identity_holder_history";
-- reverse: create index "campaigntargethistory_history_time" to table: "campaign_target_history"
DROP INDEX "campaigntargethistory_history_time";
-- reverse: create "campaign_target_history" table
DROP TABLE "campaign_target_history";
-- reverse: create index "campaignhistory_history_time" to table: "campaign_history"
DROP INDEX "campaignhistory_history_time";
-- reverse: create "campaign_history" table
DROP TABLE "campaign_history";
-- reverse: modify "workflow_object_ref_history" table
ALTER TABLE "workflow_object_ref_history" DROP COLUMN "platform_id", DROP COLUMN "identity_holder_id", DROP COLUMN "campaign_target_id", DROP COLUMN "campaign_id";
-- reverse: modify "workflow_instance_history" table
ALTER TABLE "workflow_instance_history" DROP COLUMN "platform_id", DROP COLUMN "identity_holder_id", DROP COLUMN "campaign_target_id", DROP COLUMN "campaign_id";
-- reverse: modify "vulnerability_history" table
ALTER TABLE "vulnerability_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "template_history" table
ALTER TABLE "template_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "task_history" table
ALTER TABLE "task_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "scan_history" table
ALTER TABLE "scan_history" DROP COLUMN "vulnerability_ids", DROP COLUMN "generated_by_platform_id", DROP COLUMN "performed_by_group_id", DROP COLUMN "performed_by_user_id", DROP COLUMN "performed_by", DROP COLUMN "next_scan_run_at", DROP COLUMN "scan_schedule", DROP COLUMN "scan_date", DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name", DROP COLUMN "assigned_to_group_id", DROP COLUMN "assigned_to_user_id", DROP COLUMN "assigned_to", DROP COLUMN "reviewed_by_group_id", DROP COLUMN "reviewed_by_user_id", DROP COLUMN "reviewed_by";
-- reverse: modify "risk_history" table
ALTER TABLE "risk_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "review_history" table
ALTER TABLE "review_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "remediation_history" table
ALTER TABLE "remediation_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "procedure_history" table
ALTER TABLE "procedure_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "internal_policy_history" table
ALTER TABLE "internal_policy_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "integration_history" table
ALTER TABLE "integration_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "finding_history" table
ALTER TABLE "finding_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "file_history" table
ALTER TABLE "file_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "evidence_history" table
ALTER TABLE "evidence_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "entity_history" table
ALTER TABLE "entity_history" DROP COLUMN "vendor_metadata", DROP COLUMN "contract_renewal_at", DROP COLUMN "next_review_at", DROP COLUMN "review_frequency", DROP COLUMN "tier", DROP COLUMN "risk_score", DROP COLUMN "risk_rating", DROP COLUMN "links", DROP COLUMN "provided_services", DROP COLUMN "status_page_url", DROP COLUMN "mfa_enforced", DROP COLUMN "mfa_supported", DROP COLUMN "sso_enforced", DROP COLUMN "renewal_risk", DROP COLUMN "billing_model", DROP COLUMN "spend_currency", DROP COLUMN "annual_spend", DROP COLUMN "termination_notice_days", DROP COLUMN "auto_renews", DROP COLUMN "contract_end_date", DROP COLUMN "contract_start_date", DROP COLUMN "soc2_period_end", DROP COLUMN "has_soc2", DROP COLUMN "linked_asset_ids", DROP COLUMN "approved_for_use", DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name", DROP COLUMN "entity_source_type_id", DROP COLUMN "entity_source_type_name", DROP COLUMN "entity_security_questionnaire_status_id", DROP COLUMN "entity_security_questionnaire_status_name", DROP COLUMN "entity_relationship_state_id", DROP COLUMN "entity_relationship_state_name", DROP COLUMN "last_reviewed_at", DROP COLUMN "reviewed_by_group_id", DROP COLUMN "reviewed_by_user_id", DROP COLUMN "reviewed_by", DROP COLUMN "internal_owner_group_id", DROP COLUMN "internal_owner_user_id", DROP COLUMN "internal_owner";
-- reverse: modify "document_data_history" table
ALTER TABLE "document_data_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "directory_membership_history" table
ALTER TABLE "directory_membership_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "directory_group_history" table
ALTER TABLE "directory_group_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "directory_account_history" table
ALTER TABLE "directory_account_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "control_history" table
ALTER TABLE "control_history" DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name";
-- reverse: modify "asset_history" table
ALTER TABLE "asset_history" DROP COLUMN "purchase_date", DROP COLUMN "estimated_monthly_cost", DROP COLUMN "cost_center", DROP COLUMN "source_identifier", DROP COLUMN "source_platform_id", DROP COLUMN "source_type", DROP COLUMN "contains_pii", DROP COLUMN "region", DROP COLUMN "physical_location", DROP COLUMN "criticality_id", DROP COLUMN "criticality_name", DROP COLUMN "security_tier_id", DROP COLUMN "security_tier_name", DROP COLUMN "encryption_status_id", DROP COLUMN "encryption_status_name", DROP COLUMN "access_model_id", DROP COLUMN "access_model_name", DROP COLUMN "scope_id", DROP COLUMN "scope_name", DROP COLUMN "environment_id", DROP COLUMN "environment_name", DROP COLUMN "asset_data_classification_id", DROP COLUMN "asset_data_classification_name", DROP COLUMN "asset_subtype_id", DROP COLUMN "asset_subtype_name", DROP COLUMN "internal_owner_group_id", DROP COLUMN "internal_owner_user_id", DROP COLUMN "internal_owner";
-- reverse: modify "assessment_response_history" table
ALTER TABLE "assessment_response_history" DROP COLUMN "email_metadata", DROP COLUMN "last_email_event_at", DROP COLUMN "email_click_count", DROP COLUMN "email_open_count", DROP COLUMN "email_clicked_at", DROP COLUMN "email_opened_at", DROP COLUMN "email_delivered_at", DROP COLUMN "entity_id", DROP COLUMN "identity_holder_id", DROP COLUMN "campaign_id";
