-- +goose Up
-- modify "integrations" table
ALTER TABLE "integrations" ADD COLUMN "platform_id" character varying NULL, ADD CONSTRAINT "integrations_platforms_integrations" FOREIGN KEY ("platform_id") REFERENCES "platforms" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- create index "integration_platform_id" to table: "integrations"
CREATE INDEX "integration_platform_id" ON "integrations" ("platform_id");
-- modify "directory_sync_runs" table
ALTER TABLE "directory_sync_runs" DROP CONSTRAINT "directory_sync_runs_integrations_directory_sync_runs", DROP CONSTRAINT "directory_sync_runs_integrations_integration", DROP COLUMN "integration_directory_sync_runs", ADD COLUMN "platform_id" character varying NULL, ADD CONSTRAINT "directory_sync_runs_integrations_directory_sync_runs" FOREIGN KEY ("integration_id") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_sync_runs_platforms_directory_sync_runs" FOREIGN KEY ("platform_id") REFERENCES "platforms" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- create index "directorysyncrun_platform_id_started_at" to table: "directory_sync_runs"
CREATE INDEX "directorysyncrun_platform_id_started_at" ON "directory_sync_runs" ("platform_id", "started_at");
-- modify "directory_accounts" table
ALTER TABLE "directory_accounts" DROP CONSTRAINT "directory_accounts_directory_sync_runs_directory_accounts", DROP CONSTRAINT "directory_accounts_directory_sync_runs_directory_sync_run", DROP CONSTRAINT "directory_accounts_integrations_directory_accounts", DROP CONSTRAINT "directory_accounts_integrations_integration", ALTER COLUMN "integration_id" DROP NOT NULL, ALTER COLUMN "directory_sync_run_id" DROP NOT NULL, DROP COLUMN "directory_sync_run_directory_accounts", DROP COLUMN "integration_directory_accounts", ADD COLUMN "directory_name" character varying NULL, ADD COLUMN "avatar_remote_url" character varying NULL, ADD COLUMN "avatar_updated_at" timestamptz NULL, ADD COLUMN "avatar_local_file_id" character varying NULL, ADD COLUMN "identity_holder_id" character varying NULL, ADD COLUMN "platform_id" character varying NULL, ADD CONSTRAINT "directory_accounts_directory_sync_runs_directory_accounts" FOREIGN KEY ("directory_sync_run_id") REFERENCES "directory_sync_runs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "directory_accounts_integrations_directory_accounts" FOREIGN KEY ("integration_id") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "directory_accounts_files_avatar_file" FOREIGN KEY ("avatar_local_file_id") REFERENCES "files" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "directory_accounts_identity_holders_directory_accounts" FOREIGN KEY ("identity_holder_id") REFERENCES "identity_holders" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "directory_accounts_platforms_directory_accounts" FOREIGN KEY ("platform_id") REFERENCES "platforms" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- create index "directoryaccount_identity_holder_id" to table: "directory_accounts"
CREATE INDEX "directoryaccount_identity_holder_id" ON "directory_accounts" ("identity_holder_id");
-- create index "directoryaccount_identity_holder_id_directory_name" to table: "directory_accounts"
CREATE INDEX "directoryaccount_identity_holder_id_directory_name" ON "directory_accounts" ("identity_holder_id", "directory_name");
-- create index "directoryaccount_platform_id_canonical_email" to table: "directory_accounts"
CREATE INDEX "directoryaccount_platform_id_canonical_email" ON "directory_accounts" ("platform_id", "canonical_email");
-- create index "directoryaccount_platform_id_external_id" to table: "directory_accounts"
CREATE INDEX "directoryaccount_platform_id_external_id" ON "directory_accounts" ("platform_id", "external_id");
-- modify "directory_groups" table
ALTER TABLE "directory_groups" DROP CONSTRAINT "directory_groups_directory_sync_runs_directory_groups", DROP CONSTRAINT "directory_groups_directory_sync_runs_directory_sync_run", DROP CONSTRAINT "directory_groups_integrations_directory_groups", DROP CONSTRAINT "directory_groups_integrations_integration", DROP COLUMN "directory_sync_run_directory_groups", DROP COLUMN "integration_directory_groups", ADD COLUMN "platform_id" character varying NULL, ADD CONSTRAINT "directory_groups_directory_sync_runs_directory_groups" FOREIGN KEY ("directory_sync_run_id") REFERENCES "directory_sync_runs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_groups_integrations_directory_groups" FOREIGN KEY ("integration_id") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_groups_platforms_directory_groups" FOREIGN KEY ("platform_id") REFERENCES "platforms" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- create index "directorygroup_platform_id_email" to table: "directory_groups"
CREATE INDEX "directorygroup_platform_id_email" ON "directory_groups" ("platform_id", "email");
-- create index "directorygroup_platform_id_external_id" to table: "directory_groups"
CREATE INDEX "directorygroup_platform_id_external_id" ON "directory_groups" ("platform_id", "external_id");
-- modify "directory_memberships" table
ALTER TABLE "directory_memberships" DROP CONSTRAINT "directory_memberships_directory_sync_runs_directory_memberships", DROP CONSTRAINT "directory_memberships_directory_sync_runs_directory_sync_run", DROP CONSTRAINT "directory_memberships_integrations_directory_memberships", DROP CONSTRAINT "directory_memberships_integrations_integration", DROP COLUMN "directory_sync_run_directory_memberships", DROP COLUMN "integration_directory_memberships", ADD COLUMN "platform_id" character varying NULL, ADD CONSTRAINT "directory_memberships_directory_sync_runs_directory_memberships" FOREIGN KEY ("directory_sync_run_id") REFERENCES "directory_sync_runs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_memberships_integrations_directory_memberships" FOREIGN KEY ("integration_id") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_memberships_platforms_directory_memberships" FOREIGN KEY ("platform_id") REFERENCES "platforms" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- create index "directorymembership_platform_id_directory_sync_run_id" to table: "directory_memberships"
CREATE INDEX "directorymembership_platform_id_directory_sync_run_id" ON "directory_memberships" ("platform_id", "directory_sync_run_id");
-- create "finding_directory_accounts" table
CREATE TABLE "finding_directory_accounts" ("finding_id" character varying NOT NULL, "directory_account_id" character varying NOT NULL, PRIMARY KEY ("finding_id", "directory_account_id"), CONSTRAINT "finding_directory_accounts_directory_account_id" FOREIGN KEY ("directory_account_id") REFERENCES "directory_accounts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "finding_directory_accounts_finding_id" FOREIGN KEY ("finding_id") REFERENCES "findings" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create "finding_identity_holders" table
CREATE TABLE "finding_identity_holders" ("finding_id" character varying NOT NULL, "identity_holder_id" character varying NOT NULL, PRIMARY KEY ("finding_id", "identity_holder_id"), CONSTRAINT "finding_identity_holders_finding_id" FOREIGN KEY ("finding_id") REFERENCES "findings" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "finding_identity_holders_identity_holder_id" FOREIGN KEY ("identity_holder_id") REFERENCES "identity_holders" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- modify "groups" table
ALTER TABLE "groups" ADD COLUMN "organization_identity_holder_creators" character varying NULL, ADD CONSTRAINT "groups_organizations_identity_holder_creators" FOREIGN KEY ("organization_identity_holder_creators") REFERENCES "organizations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;

-- +goose Down
-- reverse: modify "groups" table
ALTER TABLE "groups" DROP CONSTRAINT "groups_organizations_identity_holder_creators", DROP COLUMN "organization_identity_holder_creators";
-- reverse: create "finding_identity_holders" table
DROP TABLE "finding_identity_holders";
-- reverse: create "finding_directory_accounts" table
DROP TABLE "finding_directory_accounts";
-- reverse: create index "directorymembership_platform_id_directory_sync_run_id" to table: "directory_memberships"
DROP INDEX "directorymembership_platform_id_directory_sync_run_id";
-- reverse: modify "directory_memberships" table
ALTER TABLE "directory_memberships" DROP CONSTRAINT "directory_memberships_platforms_directory_memberships", DROP CONSTRAINT "directory_memberships_integrations_directory_memberships", DROP CONSTRAINT "directory_memberships_directory_sync_runs_directory_memberships", DROP COLUMN "platform_id", ADD COLUMN "integration_directory_memberships" character varying NULL, ADD COLUMN "directory_sync_run_directory_memberships" character varying NULL, ADD CONSTRAINT "directory_memberships_integrations_integration" FOREIGN KEY ("integration_id") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_memberships_integrations_directory_memberships" FOREIGN KEY ("integration_directory_memberships") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "directory_memberships_directory_sync_runs_directory_sync_run" FOREIGN KEY ("directory_sync_run_id") REFERENCES "directory_sync_runs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_memberships_directory_sync_runs_directory_memberships" FOREIGN KEY ("directory_sync_run_directory_memberships") REFERENCES "directory_sync_runs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- reverse: create index "directorygroup_platform_id_external_id" to table: "directory_groups"
DROP INDEX "directorygroup_platform_id_external_id";
-- reverse: create index "directorygroup_platform_id_email" to table: "directory_groups"
DROP INDEX "directorygroup_platform_id_email";
-- reverse: modify "directory_groups" table
ALTER TABLE "directory_groups" DROP CONSTRAINT "directory_groups_platforms_directory_groups", DROP CONSTRAINT "directory_groups_integrations_directory_groups", DROP CONSTRAINT "directory_groups_directory_sync_runs_directory_groups", DROP COLUMN "platform_id", ADD COLUMN "integration_directory_groups" character varying NULL, ADD COLUMN "directory_sync_run_directory_groups" character varying NULL, ADD CONSTRAINT "directory_groups_integrations_integration" FOREIGN KEY ("integration_id") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_groups_integrations_directory_groups" FOREIGN KEY ("integration_directory_groups") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "directory_groups_directory_sync_runs_directory_sync_run" FOREIGN KEY ("directory_sync_run_id") REFERENCES "directory_sync_runs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_groups_directory_sync_runs_directory_groups" FOREIGN KEY ("directory_sync_run_directory_groups") REFERENCES "directory_sync_runs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- reverse: create index "directoryaccount_platform_id_external_id" to table: "directory_accounts"
DROP INDEX "directoryaccount_platform_id_external_id";
-- reverse: create index "directoryaccount_platform_id_canonical_email" to table: "directory_accounts"
DROP INDEX "directoryaccount_platform_id_canonical_email";
-- reverse: create index "directoryaccount_identity_holder_id_directory_name" to table: "directory_accounts"
DROP INDEX "directoryaccount_identity_holder_id_directory_name";
-- reverse: create index "directoryaccount_identity_holder_id" to table: "directory_accounts"
DROP INDEX "directoryaccount_identity_holder_id";
-- reverse: modify "directory_accounts" table
ALTER TABLE "directory_accounts" DROP CONSTRAINT "directory_accounts_platforms_directory_accounts", DROP CONSTRAINT "directory_accounts_identity_holders_directory_accounts", DROP CONSTRAINT "directory_accounts_files_avatar_file", DROP CONSTRAINT "directory_accounts_integrations_directory_accounts", DROP CONSTRAINT "directory_accounts_directory_sync_runs_directory_accounts", DROP COLUMN "platform_id", DROP COLUMN "identity_holder_id", DROP COLUMN "avatar_local_file_id", DROP COLUMN "avatar_updated_at", DROP COLUMN "avatar_remote_url", DROP COLUMN "directory_name", ADD COLUMN "integration_directory_accounts" character varying NULL, ADD COLUMN "directory_sync_run_directory_accounts" character varying NULL, ALTER COLUMN "directory_sync_run_id" SET NOT NULL, ALTER COLUMN "integration_id" SET NOT NULL, ADD CONSTRAINT "directory_accounts_integrations_integration" FOREIGN KEY ("integration_id") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_accounts_integrations_directory_accounts" FOREIGN KEY ("integration_directory_accounts") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "directory_accounts_directory_sync_runs_directory_sync_run" FOREIGN KEY ("directory_sync_run_id") REFERENCES "directory_sync_runs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_accounts_directory_sync_runs_directory_accounts" FOREIGN KEY ("directory_sync_run_directory_accounts") REFERENCES "directory_sync_runs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- reverse: create index "directorysyncrun_platform_id_started_at" to table: "directory_sync_runs"
DROP INDEX "directorysyncrun_platform_id_started_at";
-- reverse: modify "directory_sync_runs" table
ALTER TABLE "directory_sync_runs" DROP CONSTRAINT "directory_sync_runs_platforms_directory_sync_runs", DROP CONSTRAINT "directory_sync_runs_integrations_directory_sync_runs", DROP COLUMN "platform_id", ADD COLUMN "integration_directory_sync_runs" character varying NULL, ADD CONSTRAINT "directory_sync_runs_integrations_integration" FOREIGN KEY ("integration_id") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "directory_sync_runs_integrations_directory_sync_runs" FOREIGN KEY ("integration_directory_sync_runs") REFERENCES "integrations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- reverse: create index "integration_platform_id" to table: "integrations"
DROP INDEX "integration_platform_id";
-- reverse: modify "integrations" table
ALTER TABLE "integrations" DROP CONSTRAINT "integrations_platforms_integrations", DROP COLUMN "platform_id";
