-- +goose Up
-- modify "findings" table
ALTER TABLE "findings" ADD COLUMN "reviewed_by" character varying NULL, ADD COLUMN "assigned_to" character varying NULL, ADD COLUMN "reviewed_by_user_id" character varying NULL, ADD COLUMN "reviewed_by_group_id" character varying NULL, ADD COLUMN "assigned_to_user_id" character varying NULL, ADD COLUMN "assigned_to_group_id" character varying NULL, ADD CONSTRAINT "findings_groups_assigned_to_group" FOREIGN KEY ("assigned_to_group_id") REFERENCES "groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "findings_groups_reviewed_by_group" FOREIGN KEY ("reviewed_by_group_id") REFERENCES "groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "findings_users_assigned_to_user" FOREIGN KEY ("assigned_to_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "findings_users_reviewed_by_user" FOREIGN KEY ("reviewed_by_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- modify "vulnerabilities" table
ALTER TABLE "vulnerabilities" ADD COLUMN "reviewed_by" character varying NULL, ADD COLUMN "assigned_to" character varying NULL, ADD COLUMN "reviewed_by_user_id" character varying NULL, ADD COLUMN "reviewed_by_group_id" character varying NULL, ADD COLUMN "assigned_to_user_id" character varying NULL, ADD COLUMN "assigned_to_group_id" character varying NULL, ADD CONSTRAINT "vulnerabilities_groups_assigned_to_group" FOREIGN KEY ("assigned_to_group_id") REFERENCES "groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "vulnerabilities_groups_reviewed_by_group" FOREIGN KEY ("reviewed_by_group_id") REFERENCES "groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "vulnerabilities_users_assigned_to_user" FOREIGN KEY ("assigned_to_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "vulnerabilities_users_reviewed_by_user" FOREIGN KEY ("reviewed_by_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;

-- +goose Down
-- reverse: modify "vulnerabilities" table
ALTER TABLE "vulnerabilities" DROP CONSTRAINT "vulnerabilities_users_reviewed_by_user", DROP CONSTRAINT "vulnerabilities_users_assigned_to_user", DROP CONSTRAINT "vulnerabilities_groups_reviewed_by_group", DROP CONSTRAINT "vulnerabilities_groups_assigned_to_group", DROP COLUMN "assigned_to_group_id", DROP COLUMN "assigned_to_user_id", DROP COLUMN "reviewed_by_group_id", DROP COLUMN "reviewed_by_user_id", DROP COLUMN "assigned_to", DROP COLUMN "reviewed_by";
-- reverse: modify "findings" table
ALTER TABLE "findings" DROP CONSTRAINT "findings_users_reviewed_by_user", DROP CONSTRAINT "findings_users_assigned_to_user", DROP CONSTRAINT "findings_groups_reviewed_by_group", DROP CONSTRAINT "findings_groups_assigned_to_group", DROP COLUMN "assigned_to_group_id", DROP COLUMN "assigned_to_user_id", DROP COLUMN "reviewed_by_group_id", DROP COLUMN "reviewed_by_user_id", DROP COLUMN "assigned_to", DROP COLUMN "reviewed_by";
