-- +goose Up
-- modify "findings" table
ALTER TABLE "findings" ADD COLUMN "internal_owner" character varying NULL, ADD COLUMN "internal_owner_user_id" character varying NULL, ADD COLUMN "internal_owner_group_id" character varying NULL, ADD COLUMN "internal_owner_identity_holder_id" character varying NULL, ADD CONSTRAINT "findings_groups_internal_owner_group" FOREIGN KEY ("internal_owner_group_id") REFERENCES "groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "findings_identity_holders_internal_owner_identity_holder" FOREIGN KEY ("internal_owner_identity_holder_id") REFERENCES "identity_holders" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "findings_users_internal_owner_user" FOREIGN KEY ("internal_owner_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- modify "risks" table
ALTER TABLE "risks" ADD COLUMN "stakeholder_name" character varying NULL, ADD COLUMN "delegate_name" character varying NULL, ADD COLUMN "stakeholder_user_id" character varying NULL, ADD COLUMN "stakeholder_group_id" character varying NULL, ADD COLUMN "stakeholder_identity_holder_id" character varying NULL, ADD COLUMN "delegate_user_id" character varying NULL, ADD COLUMN "delegate_group_id" character varying NULL, ADD COLUMN "delegate_identity_holder_id" character varying NULL, ADD CONSTRAINT "risks_groups_delegate_group" FOREIGN KEY ("delegate_group_id") REFERENCES "groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "risks_groups_stakeholder_group" FOREIGN KEY ("stakeholder_group_id") REFERENCES "groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "risks_identity_holders_delegate_identity_holder" FOREIGN KEY ("delegate_identity_holder_id") REFERENCES "identity_holders" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "risks_identity_holders_stakeholder_identity_holder" FOREIGN KEY ("stakeholder_identity_holder_id") REFERENCES "identity_holders" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "risks_users_delegate_user" FOREIGN KEY ("delegate_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "risks_users_stakeholder_user" FOREIGN KEY ("stakeholder_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- modify "vulnerabilities" table
ALTER TABLE "vulnerabilities" ADD COLUMN "internal_owner" character varying NULL, ADD COLUMN "internal_owner_user_id" character varying NULL, ADD COLUMN "internal_owner_group_id" character varying NULL, ADD COLUMN "internal_owner_identity_holder_id" character varying NULL, ADD CONSTRAINT "vulnerabilities_groups_internal_owner_group" FOREIGN KEY ("internal_owner_group_id") REFERENCES "groups" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "vulnerabilities_identity_holders_internal_owner_identity_holder" FOREIGN KEY ("internal_owner_identity_holder_id") REFERENCES "identity_holders" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "vulnerabilities_users_internal_owner_user" FOREIGN KEY ("internal_owner_user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;

-- +goose Down
-- reverse: modify "vulnerabilities" table
ALTER TABLE "vulnerabilities" DROP CONSTRAINT "vulnerabilities_users_internal_owner_user", DROP CONSTRAINT "vulnerabilities_identity_holders_internal_owner_identity_holder", DROP CONSTRAINT "vulnerabilities_groups_internal_owner_group", DROP COLUMN "internal_owner_identity_holder_id", DROP COLUMN "internal_owner_group_id", DROP COLUMN "internal_owner_user_id", DROP COLUMN "internal_owner";
-- reverse: modify "risks" table
ALTER TABLE "risks" DROP CONSTRAINT "risks_users_stakeholder_user", DROP CONSTRAINT "risks_users_delegate_user", DROP CONSTRAINT "risks_identity_holders_stakeholder_identity_holder", DROP CONSTRAINT "risks_identity_holders_delegate_identity_holder", DROP CONSTRAINT "risks_groups_stakeholder_group", DROP CONSTRAINT "risks_groups_delegate_group", DROP COLUMN "delegate_identity_holder_id", DROP COLUMN "delegate_group_id", DROP COLUMN "delegate_user_id", DROP COLUMN "stakeholder_identity_holder_id", DROP COLUMN "stakeholder_group_id", DROP COLUMN "stakeholder_user_id", DROP COLUMN "delegate_name", DROP COLUMN "stakeholder_name";
-- reverse: modify "findings" table
ALTER TABLE "findings" DROP CONSTRAINT "findings_users_internal_owner_user", DROP CONSTRAINT "findings_identity_holders_internal_owner_identity_holder", DROP CONSTRAINT "findings_groups_internal_owner_group", DROP COLUMN "internal_owner_identity_holder_id", DROP COLUMN "internal_owner_group_id", DROP COLUMN "internal_owner_user_id", DROP COLUMN "internal_owner";
