-- +goose Up
-- drop "check_result_history" table
DROP TABLE "check_result_history";
-- drop "directory_account_history" table
DROP TABLE "directory_account_history";
-- drop "directory_group_history" table
DROP TABLE "directory_group_history";
-- drop "directory_membership_history" table
DROP TABLE "directory_membership_history";
-- drop "dns_verification_history" table
DROP TABLE "dns_verification_history";
-- drop "integration_history" table
DROP TABLE "integration_history";
-- drop "org_subscription_history" table
DROP TABLE "org_subscription_history";
-- drop "scan_history" table
DROP TABLE "scan_history";
-- drop "workflow_event_history" table
DROP TABLE "workflow_event_history";
-- drop "workflow_instance_history" table
DROP TABLE "workflow_instance_history";
-- drop "workflow_object_ref_history" table
DROP TABLE "workflow_object_ref_history";

-- +goose Down
-- reverse: drop "workflow_object_ref_history" table
CREATE TABLE "workflow_object_ref_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "display_id" character varying NOT NULL, "owner_id" character varying NULL, "workflow_instance_id" character varying NOT NULL, "control_id" character varying NULL, "task_id" character varying NULL, "internal_policy_id" character varying NULL, "finding_id" character varying NULL, "directory_account_id" character varying NULL, "directory_group_id" character varying NULL, "directory_membership_id" character varying NULL, "evidence_id" character varying NULL, "subcontrol_id" character varying NULL, "action_plan_id" character varying NULL, "procedure_id" character varying NULL, "campaign_id" character varying NULL, "campaign_target_id" character varying NULL, "identity_holder_id" character varying NULL, "platform_id" character varying NULL, "updated_by_impersonator" character varying NULL, "vulnerability_id" character varying NULL, "risk_id" character varying NULL, "assessment_id" character varying NULL, "assessment_response_id" character varying NULL, "remediation_id" character varying NULL, PRIMARY KEY ("id"));
CREATE INDEX "workflowobjectrefhistory_history_time" ON "workflow_object_ref_history" ("history_time");
-- reverse: drop "workflow_instance_history" table
CREATE TABLE "workflow_instance_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "workflow_definition_id" character varying NOT NULL, "workflow_proposal_id" character varying NULL, "state" character varying NOT NULL DEFAULT 'RUNNING', "context" jsonb NULL, "last_evaluated_at" timestamptz NULL, "definition_snapshot" jsonb NULL, "current_action_index" bigint NOT NULL DEFAULT 0, "control_id" character varying NULL, "internal_policy_id" character varying NULL, "evidence_id" character varying NULL, "subcontrol_id" character varying NULL, "action_plan_id" character varying NULL, "procedure_id" character varying NULL, "campaign_id" character varying NULL, "campaign_target_id" character varying NULL, "identity_holder_id" character varying NULL, "platform_id" character varying NULL, "updated_by_impersonator" character varying NULL, "assessment_id" character varying NULL, "assessment_response_id" character varying NULL, "finding_id" character varying NULL, "integration_id" character varying NULL, "remediation_id" character varying NULL, "risk_id" character varying NULL, "task_id" character varying NULL, "vulnerability_id" character varying NULL, PRIMARY KEY ("id"));
CREATE INDEX "workflowinstancehistory_history_time" ON "workflow_instance_history" ("history_time");
-- reverse: drop "workflow_event_history" table
CREATE TABLE "workflow_event_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "workflow_instance_id" character varying NOT NULL, "event_type" character varying NOT NULL, "payload" jsonb NULL, "updated_by_impersonator" character varying NULL, PRIMARY KEY ("id"));
CREATE INDEX "workfloweventhistory_history_time" ON "workflow_event_history" ("history_time");
-- reverse: drop "scan_history" table
CREATE TABLE "scan_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "target" character varying NOT NULL, "scan_type" character varying NOT NULL DEFAULT 'DOMAIN', "metadata" jsonb NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "reviewed_by" character varying NULL, "reviewed_by_user_id" character varying NULL, "reviewed_by_group_id" character varying NULL, "assigned_to" character varying NULL, "assigned_to_user_id" character varying NULL, "assigned_to_group_id" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "scan_date" timestamptz NULL, "scan_schedule" character varying NULL, "next_scan_run_at" timestamptz NULL, "performed_by" character varying NULL, "performed_by_user_id" character varying NULL, "performed_by_group_id" character varying NULL, "generated_by_platform_id" character varying NULL, "discovered_vulnerability_ids" jsonb NULL, "updated_by_impersonator" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, PRIMARY KEY ("id"));
CREATE INDEX "scanhistory_history_time" ON "scan_history" ("history_time");
-- reverse: drop "org_subscription_history" table
CREATE TABLE "org_subscription_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "stripe_subscription_id" character varying NULL, "stripe_subscription_status" character varying NULL, "active" boolean NOT NULL DEFAULT true, "expires_at" timestamptz NULL, "trial_expires_at" timestamptz NULL, "days_until_due" character varying NULL, "updated_by_impersonator" character varying NULL, PRIMARY KEY ("id"));
CREATE INDEX "orgsubscriptionhistory_history_time" ON "org_subscription_history" ("history_time");
-- reverse: drop "integration_history" table
CREATE TABLE "integration_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "system_owned" boolean NULL DEFAULT false, "internal_notes" character varying NULL, "system_internal_id" character varying NULL, "name" character varying NOT NULL, "description" character varying NULL, "kind" character varying NULL, "integration_type" character varying NULL, "metadata" jsonb NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "provider_metadata" jsonb NULL, "config" jsonb NULL, "provider_state" jsonb NULL, "platform_id" character varying NULL, "definition_id" character varying NULL, "definition_version" character varying NULL, "definition_slug" character varying NULL, "family" character varying NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "provider_metadata_snapshot" jsonb NULL, "installation_metadata" jsonb NULL, "primary_directory" boolean NOT NULL DEFAULT false, "campaign_email" boolean NOT NULL DEFAULT false, "updated_by_impersonator" character varying NULL, PRIMARY KEY ("id"));
CREATE INDEX "integrationhistory_history_time" ON "integration_history" ("history_time");
-- reverse: drop "dns_verification_history" table
CREATE TABLE "dns_verification_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "cloudflare_hostname_id" character varying NOT NULL, "dns_txt_record" character varying NOT NULL, "dns_txt_value" character varying NOT NULL, "dns_verification_status" character varying NOT NULL DEFAULT 'PENDING', "dns_verification_status_reason" character varying NULL, "acme_challenge_path" character varying NULL, "expected_acme_challenge_value" character varying NULL, "acme_challenge_status" character varying NOT NULL DEFAULT 'INITIALIZING', "acme_challenge_status_reason" character varying NULL, "updated_by_impersonator" character varying NULL, PRIMARY KEY ("id"));
CREATE INDEX "dnsverificationhistory_history_time" ON "dns_verification_history" ("history_time");
-- reverse: drop "directory_membership_history" table
CREATE TABLE "directory_membership_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "display_id" character varying NOT NULL, "owner_id" character varying NULL, "integration_id" character varying NOT NULL, "directory_sync_run_id" character varying NOT NULL, "directory_account_id" character varying NOT NULL, "directory_group_id" character varying NOT NULL, "role" character varying NULL DEFAULT 'MEMBER', "source" character varying NULL, "first_seen_at" timestamptz NULL, "last_seen_at" timestamptz NULL, "observed_at" timestamptz NOT NULL, "last_confirmed_run_id" character varying NULL, "metadata" jsonb NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "platform_id" character varying NULL, "directory_instance_id" character varying NULL, "added_at" timestamptz NULL, "removed_at" timestamptz NULL, "directory_name" character varying NULL, "updated_by_impersonator" character varying NULL, PRIMARY KEY ("id"));
CREATE INDEX "directorymembershiphistory_history_time" ON "directory_membership_history" ("history_time");
-- reverse: drop "directory_group_history" table
CREATE TABLE "directory_group_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "integration_id" character varying NOT NULL, "directory_sync_run_id" character varying NOT NULL, "external_id" character varying NOT NULL, "email" character varying NULL, "display_name" character varying NULL, "description" character varying NULL, "classification" character varying NOT NULL DEFAULT 'TEAM', "status" character varying NOT NULL DEFAULT 'ACTIVE', "external_sharing_allowed" boolean NULL DEFAULT false, "member_count" bigint NULL, "observed_at" timestamptz NOT NULL, "profile_hash" character varying NOT NULL DEFAULT '', "profile" jsonb NULL, "raw_profile_file_id" character varying NULL, "source_version" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "platform_id" character varying NULL, "directory_instance_id" character varying NULL, "first_seen_at" timestamptz NULL, "last_seen_at" timestamptz NULL, "added_at" timestamptz NULL, "removed_at" timestamptz NULL, "metadata" jsonb NULL, "directory_name" character varying NULL, "updated_by_impersonator" character varying NULL, PRIMARY KEY ("id"));
CREATE INDEX "directorygrouphistory_history_time" ON "directory_group_history" ("history_time");
-- reverse: drop "directory_account_history" table
CREATE TABLE "directory_account_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "display_id" character varying NOT NULL, "tags" jsonb NULL, "owner_id" character varying NULL, "integration_id" character varying NULL, "directory_sync_run_id" character varying NULL, "external_id" character varying NOT NULL, "secondary_key" character varying NULL, "canonical_email" character varying NULL, "display_name" character varying NULL, "given_name" character varying NULL, "family_name" character varying NULL, "job_title" character varying NULL, "department" character varying NULL, "organization_unit" character varying NULL, "account_type" character varying NULL DEFAULT 'USER', "status" character varying NOT NULL DEFAULT 'ACTIVE', "mfa_state" character varying NOT NULL DEFAULT 'UNKNOWN', "last_seen_ip" character varying NULL, "last_login_at" timestamptz NULL, "observed_at" timestamptz NOT NULL, "profile_hash" character varying NOT NULL DEFAULT '', "profile" jsonb NULL, "raw_profile_file_id" character varying NULL, "source_version" character varying NULL, "environment_name" character varying NULL, "environment_id" character varying NULL, "scope_name" character varying NULL, "scope_id" character varying NULL, "platform_id" character varying NULL, "identity_holder_id" character varying NULL, "directory_name" character varying NULL, "avatar_remote_url" character varying NULL, "avatar_local_file_id" character varying NULL, "avatar_updated_at" timestamptz NULL, "directory_instance_id" character varying NULL, "first_seen_at" timestamptz NULL, "last_seen_at" timestamptz NULL, "added_at" timestamptz NULL, "removed_at" timestamptz NULL, "metadata" jsonb NULL, "primary_source" boolean NOT NULL DEFAULT false, "email_aliases" jsonb NULL, "phone_number" character varying NULL, "updated_by_impersonator" character varying NULL, PRIMARY KEY ("id"));
CREATE INDEX "directoryaccounthistory_history_time" ON "directory_account_history" ("history_time");
-- reverse: drop "check_result_history" table
CREATE TABLE "check_result_history" ("id" character varying NOT NULL, "history_time" timestamptz NOT NULL, "ref" character varying NULL, "operation" character varying NOT NULL, "created_at" timestamptz NULL, "updated_at" timestamptz NULL, "created_by" character varying NULL, "updated_by" character varying NULL, "deleted_at" timestamptz NULL, "deleted_by" character varying NULL, "tags" jsonb NULL, "status" character varying NOT NULL DEFAULT 'UNKNOWN', "source" character varying NOT NULL, "last_observed_at" timestamptz NULL, "external_uri" character varying NULL, "details" text NULL, "parent_external_id" character varying NULL, "integration_id" character varying NULL, "updated_by_impersonator" character varying NULL, PRIMARY KEY ("id"));
CREATE INDEX "checkresulthistory_history_time" ON "check_result_history" ("history_time");
