all: false
dir: "{{.InterfaceDir}}/mocks"
filename: mocks.go
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: mocks
recursive: false
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  github.com/theopenlane/core/pkg/corejobs/internal/cloudflare:
    config:
      all: true
  github.com/theopenlane/core/pkg/openlaneclient:
    config:
      dir: olclient/mocks
      include-interface-regex: "OpenlaneGraphClient"
  github.com/theopenlane/core/pkg/corejobs/internal/pirsch:
    config:
      all: true
