{
 "title": "OpenFGA Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "p90 Request Duration by Method",
   "type": "timeseries",
   "description": "The 90th percentile request duration of an RPC, grouped by 'grpc_service' and 'grpc_method'.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, grpc_method, grpc_service) (rate(grpc_server_handling_seconds_bucket{job=\"openfga\", grpc_type=\"unary\", grpc_service=\"openfga.v1.OpenFGAService\"}[2m])))",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "p50 Request Duration by Method",
   "type": "timeseries",
   "description": "The 50th percentile request duration of an RPC, grouped by 'grpc_service' and 'grpc_method'.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, grpc_method, grpc_service) (rate(grpc_server_handling_seconds_bucket{job=\"openfga\", grpc_type=\"unary\", grpc_service=\"openfga.v1.OpenFGAService\"}[2m])))",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Check Cache Hit Ratio",
   "type": "timeseries",
   "description": "Percentage of hits to the in-memory Check API cache",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(increase(openfga_check_cache_hit_count_total{service=\"openfga\"}[1m]))\n  /\nsum(increase(openfga_check_cache_count_total{service=\"openfga\"}[1m])))* 100",
     "legendFormat": "Check Cache hit ratio"
    }
   ]
  },
  {
   "title": "Status Code Count per Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "sum by(grpc_code, grpc_method) (rate(grpc_server_handled_total{grpc_service=\"openfga.v1.OpenFGAService\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS per Method",
   "type": "timeseries",
   "description": "The number of requests per second (aggregated over a 1m interval) per method.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"openfga\",grpc_service=\"openfga.v1.OpenFGAService\"}[1m])) by (grpc_method)\n",
     "legendFormat": "openfga.v1.OpenFGAService/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "p99 Request Duration by Method",
   "type": "timeseries",
   "description": "The 99th percentile request duration of an RPC, grouped by 'grpc_service' and 'grpc_method'.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, grpc_method, grpc_service) (rate(grpc_server_handling_seconds_bucket{job=\"openfga\", grpc_type=\"unary\", grpc_service=\"openfga.v1.OpenFGAService\"}[2m])))",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "SQL metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "go_sql_open_connections{db_name=\"openfga\"}",
     "legendFormat": "SQL Open Connections"
    },
    {
     "expr": "go_sql_max_open_connections{db_name=\"openfga\"}",
     "legendFormat": "SQL Max Open Connections"
    },
    {
     "expr": "go_sql_in_use_connections{db_name=\"openfga\"}",
     "legendFormat": "SQL In Use Connections"
    }
   ]
  },
  { "title": "Go Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "The number of goroutines reported by the Go runtime.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"openfga\"}",
     "legendFormat": "Goroutines (Count)"
    },
    {
     "expr": "irate(go_goroutines{job=\"openfga\"}[2m])",
     "legendFormat": "Goroutine (Derivative)"
    }
   ]
  },
  {
   "title": "Go GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"openfga\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"openfga\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"openfga\", quantile=\"1\"}",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"openfga\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Allocation Rate (malloc/sec)",
   "type": "timeseries",
   "description": "The number of heap allocations (mallocs) as a rate (malloc/sec).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"openfga\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Allocation Rate (bytes/sec)",
   "type": "timeseries",
   "description": "Shows the number of heap allocations (as a byte/sec rate).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"openfga\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}