global:
  scrape_interval: 15s
  external_labels:
    monitor: 'monitoring'
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:17609
          - localhost:2112
          - host.docker.internal:17609
          - host.docker.internal:2112
          - host.docker.internal:9187
  - job_name: postgres-exporter
    static_configs:
      - targets: ["host.docker.internal:9187"]
