//go:build !enthistorycodegen

// Code generated by ent, DO NOT EDIT.

package historygenerated

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/theopenlane/core/internal/ent/historygenerated/assessmentresponsehistory"
	"github.com/theopenlane/core/common/enums"
	"github.com/theopenlane/entx/history"
)

// AssessmentResponseHistoryCreate is the builder for creating a AssessmentResponseHistory entity.
type AssessmentResponseHistoryCreate struct {
	config
	mutation *AssessmentResponseHistoryMutation
	hooks    []Hook
}

// SetHistoryTime sets the "history_time" field.
func (_c *AssessmentResponseHistoryCreate) SetHistoryTime(v time.Time) *AssessmentResponseHistoryCreate {
	_c.mutation.SetHistoryTime(v)
	return _c
}

// SetNillableHistoryTime sets the "history_time" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableHistoryTime(v *time.Time) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetHistoryTime(*v)
	}
	return _c
}

// SetRef sets the "ref" field.
func (_c *AssessmentResponseHistoryCreate) SetRef(v string) *AssessmentResponseHistoryCreate {
	_c.mutation.SetRef(v)
	return _c
}

// SetNillableRef sets the "ref" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableRef(v *string) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetRef(*v)
	}
	return _c
}

// SetOperation sets the "operation" field.
func (_c *AssessmentResponseHistoryCreate) SetOperation(v history.OpType) *AssessmentResponseHistoryCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AssessmentResponseHistoryCreate) SetCreatedAt(v time.Time) *AssessmentResponseHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableCreatedAt(v *time.Time) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AssessmentResponseHistoryCreate) SetUpdatedAt(v time.Time) *AssessmentResponseHistoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableUpdatedAt(v *time.Time) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AssessmentResponseHistoryCreate) SetCreatedBy(v string) *AssessmentResponseHistoryCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableCreatedBy(v *string) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *AssessmentResponseHistoryCreate) SetUpdatedBy(v string) *AssessmentResponseHistoryCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableUpdatedBy(v *string) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AssessmentResponseHistoryCreate) SetDeletedAt(v time.Time) *AssessmentResponseHistoryCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableDeletedAt(v *time.Time) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *AssessmentResponseHistoryCreate) SetDeletedBy(v string) *AssessmentResponseHistoryCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableDeletedBy(v *string) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *AssessmentResponseHistoryCreate) SetOwnerID(v string) *AssessmentResponseHistoryCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableOwnerID(v *string) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetOwnerID(*v)
	}
	return _c
}

// SetAssessmentID sets the "assessment_id" field.
func (_c *AssessmentResponseHistoryCreate) SetAssessmentID(v string) *AssessmentResponseHistoryCreate {
	_c.mutation.SetAssessmentID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *AssessmentResponseHistoryCreate) SetEmail(v string) *AssessmentResponseHistoryCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetSendAttempts sets the "send_attempts" field.
func (_c *AssessmentResponseHistoryCreate) SetSendAttempts(v int) *AssessmentResponseHistoryCreate {
	_c.mutation.SetSendAttempts(v)
	return _c
}

// SetNillableSendAttempts sets the "send_attempts" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableSendAttempts(v *int) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetSendAttempts(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AssessmentResponseHistoryCreate) SetStatus(v enums.AssessmentResponseStatus) *AssessmentResponseHistoryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableStatus(v *enums.AssessmentResponseStatus) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *AssessmentResponseHistoryCreate) SetAssignedAt(v time.Time) *AssessmentResponseHistoryCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableAssignedAt(v *time.Time) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *AssessmentResponseHistoryCreate) SetStartedAt(v time.Time) *AssessmentResponseHistoryCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableStartedAt(v *time.Time) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *AssessmentResponseHistoryCreate) SetCompletedAt(v time.Time) *AssessmentResponseHistoryCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableCompletedAt(v *time.Time) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetDueDate sets the "due_date" field.
func (_c *AssessmentResponseHistoryCreate) SetDueDate(v time.Time) *AssessmentResponseHistoryCreate {
	_c.mutation.SetDueDate(v)
	return _c
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableDueDate(v *time.Time) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetDueDate(*v)
	}
	return _c
}

// SetDocumentDataID sets the "document_data_id" field.
func (_c *AssessmentResponseHistoryCreate) SetDocumentDataID(v string) *AssessmentResponseHistoryCreate {
	_c.mutation.SetDocumentDataID(v)
	return _c
}

// SetNillableDocumentDataID sets the "document_data_id" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableDocumentDataID(v *string) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetDocumentDataID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AssessmentResponseHistoryCreate) SetID(v string) *AssessmentResponseHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AssessmentResponseHistoryCreate) SetNillableID(v *string) *AssessmentResponseHistoryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AssessmentResponseHistoryMutation object of the builder.
func (_c *AssessmentResponseHistoryCreate) Mutation() *AssessmentResponseHistoryMutation {
	return _c.mutation
}

// Save creates the AssessmentResponseHistory in the database.
func (_c *AssessmentResponseHistoryCreate) Save(ctx context.Context) (*AssessmentResponseHistory, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AssessmentResponseHistoryCreate) SaveX(ctx context.Context) *AssessmentResponseHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssessmentResponseHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssessmentResponseHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AssessmentResponseHistoryCreate) defaults() error {
	if _, ok := _c.mutation.HistoryTime(); !ok {
		if assessmentresponsehistory.DefaultHistoryTime == nil {
			return fmt.Errorf("historygenerated: uninitialized assessmentresponsehistory.DefaultHistoryTime (forgotten import historygenerated/runtime?)")
		}
		v := assessmentresponsehistory.DefaultHistoryTime()
		_c.mutation.SetHistoryTime(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if assessmentresponsehistory.DefaultCreatedAt == nil {
			return fmt.Errorf("historygenerated: uninitialized assessmentresponsehistory.DefaultCreatedAt (forgotten import historygenerated/runtime?)")
		}
		v := assessmentresponsehistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if assessmentresponsehistory.DefaultUpdatedAt == nil {
			return fmt.Errorf("historygenerated: uninitialized assessmentresponsehistory.DefaultUpdatedAt (forgotten import historygenerated/runtime?)")
		}
		v := assessmentresponsehistory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SendAttempts(); !ok {
		v := assessmentresponsehistory.DefaultSendAttempts
		_c.mutation.SetSendAttempts(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := assessmentresponsehistory.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		if assessmentresponsehistory.DefaultAssignedAt == nil {
			return fmt.Errorf("historygenerated: uninitialized assessmentresponsehistory.DefaultAssignedAt (forgotten import historygenerated/runtime?)")
		}
		v := assessmentresponsehistory.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := assessmentresponsehistory.DefaultStartedAt
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if assessmentresponsehistory.DefaultID == nil {
			return fmt.Errorf("historygenerated: uninitialized assessmentresponsehistory.DefaultID (forgotten import historygenerated/runtime?)")
		}
		v := assessmentresponsehistory.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AssessmentResponseHistoryCreate) check() error {
	if _, ok := _c.mutation.HistoryTime(); !ok {
		return &ValidationError{Name: "history_time", err: errors.New(`historygenerated: missing required field "AssessmentResponseHistory.history_time"`)}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`historygenerated: missing required field "AssessmentResponseHistory.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := assessmentresponsehistory.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`historygenerated: validator failed for field "AssessmentResponseHistory.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AssessmentID(); !ok {
		return &ValidationError{Name: "assessment_id", err: errors.New(`historygenerated: missing required field "AssessmentResponseHistory.assessment_id"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`historygenerated: missing required field "AssessmentResponseHistory.email"`)}
	}
	if _, ok := _c.mutation.SendAttempts(); !ok {
		return &ValidationError{Name: "send_attempts", err: errors.New(`historygenerated: missing required field "AssessmentResponseHistory.send_attempts"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`historygenerated: missing required field "AssessmentResponseHistory.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := assessmentresponsehistory.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`historygenerated: validator failed for field "AssessmentResponseHistory.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`historygenerated: missing required field "AssessmentResponseHistory.assigned_at"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`historygenerated: missing required field "AssessmentResponseHistory.started_at"`)}
	}
	return nil
}

func (_c *AssessmentResponseHistoryCreate) sqlSave(ctx context.Context) (*AssessmentResponseHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AssessmentResponseHistory.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AssessmentResponseHistoryCreate) createSpec() (*AssessmentResponseHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &AssessmentResponseHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(assessmentresponsehistory.Table, sqlgraph.NewFieldSpec(assessmentresponsehistory.FieldID, field.TypeString))
	)
	_spec.Schema = _c.schemaConfig.AssessmentResponseHistory
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.HistoryTime(); ok {
		_spec.SetField(assessmentresponsehistory.FieldHistoryTime, field.TypeTime, value)
		_node.HistoryTime = value
	}
	if value, ok := _c.mutation.Ref(); ok {
		_spec.SetField(assessmentresponsehistory.FieldRef, field.TypeString, value)
		_node.Ref = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(assessmentresponsehistory.FieldOperation, field.TypeEnum, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(assessmentresponsehistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(assessmentresponsehistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(assessmentresponsehistory.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(assessmentresponsehistory.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(assessmentresponsehistory.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(assessmentresponsehistory.FieldDeletedBy, field.TypeString, value)
		_node.DeletedBy = value
	}
	if value, ok := _c.mutation.OwnerID(); ok {
		_spec.SetField(assessmentresponsehistory.FieldOwnerID, field.TypeString, value)
		_node.OwnerID = value
	}
	if value, ok := _c.mutation.AssessmentID(); ok {
		_spec.SetField(assessmentresponsehistory.FieldAssessmentID, field.TypeString, value)
		_node.AssessmentID = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(assessmentresponsehistory.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.SendAttempts(); ok {
		_spec.SetField(assessmentresponsehistory.FieldSendAttempts, field.TypeInt, value)
		_node.SendAttempts = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(assessmentresponsehistory.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(assessmentresponsehistory.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(assessmentresponsehistory.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(assessmentresponsehistory.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if value, ok := _c.mutation.DueDate(); ok {
		_spec.SetField(assessmentresponsehistory.FieldDueDate, field.TypeTime, value)
		_node.DueDate = value
	}
	if value, ok := _c.mutation.DocumentDataID(); ok {
		_spec.SetField(assessmentresponsehistory.FieldDocumentDataID, field.TypeString, value)
		_node.DocumentDataID = value
	}
	return _node, _spec
}

// AssessmentResponseHistoryCreateBulk is the builder for creating many AssessmentResponseHistory entities in bulk.
type AssessmentResponseHistoryCreateBulk struct {
	config
	err      error
	builders []*AssessmentResponseHistoryCreate
}

// Save creates the AssessmentResponseHistory entities in the database.
func (_c *AssessmentResponseHistoryCreateBulk) Save(ctx context.Context) ([]*AssessmentResponseHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AssessmentResponseHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssessmentResponseHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AssessmentResponseHistoryCreateBulk) SaveX(ctx context.Context) []*AssessmentResponseHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AssessmentResponseHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AssessmentResponseHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
