//go:build !enthistorycodegen

// Code generated by ent, DO NOT EDIT.

package historygenerated

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/theopenlane/core/internal/ent/historygenerated/campaigntargethistory"
	"github.com/theopenlane/core/internal/ent/historygenerated/predicate"
)

// CampaignTargetHistoryUpdate is the builder for updating CampaignTargetHistory entities.
type CampaignTargetHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *CampaignTargetHistoryMutation
}

// Where appends a list predicates to the CampaignTargetHistoryUpdate builder.
func (_u *CampaignTargetHistoryUpdate) Where(ps ...predicate.CampaignTargetHistory) *CampaignTargetHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the CampaignTargetHistoryMutation object of the builder.
func (_u *CampaignTargetHistoryUpdate) Mutation() *CampaignTargetHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CampaignTargetHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CampaignTargetHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CampaignTargetHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CampaignTargetHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CampaignTargetHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(campaigntargethistory.Table, campaigntargethistory.Columns, sqlgraph.NewFieldSpec(campaigntargethistory.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RefCleared() {
		_spec.ClearField(campaigntargethistory.FieldRef, field.TypeString)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(campaigntargethistory.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(campaigntargethistory.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(campaigntargethistory.FieldCreatedBy, field.TypeString)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(campaigntargethistory.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.UpdatedByImpersonatorCleared() {
		_spec.ClearField(campaigntargethistory.FieldUpdatedByImpersonator, field.TypeString)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(campaigntargethistory.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(campaigntargethistory.FieldDeletedBy, field.TypeString)
	}
	if _u.mutation.OwnerIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldOwnerID, field.TypeString)
	}
	if _u.mutation.WorkflowEligibleMarkerCleared() {
		_spec.ClearField(campaigntargethistory.FieldWorkflowEligibleMarker, field.TypeBool)
	}
	if _u.mutation.CampaignIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldCampaignID, field.TypeString)
	}
	if _u.mutation.ContactIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldContactID, field.TypeString)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldUserID, field.TypeString)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldGroupID, field.TypeString)
	}
	if _u.mutation.SubscriberIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldSubscriberID, field.TypeString)
	}
	if _u.mutation.FullNameCleared() {
		_spec.ClearField(campaigntargethistory.FieldFullName, field.TypeString)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(campaigntargethistory.FieldSentAt, field.TypeTime)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(campaigntargethistory.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(campaigntargethistory.FieldMetadata, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{campaigntargethistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CampaignTargetHistoryUpdateOne is the builder for updating a single CampaignTargetHistory entity.
type CampaignTargetHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CampaignTargetHistoryMutation
}

// Mutation returns the CampaignTargetHistoryMutation object of the builder.
func (_u *CampaignTargetHistoryUpdateOne) Mutation() *CampaignTargetHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the CampaignTargetHistoryUpdate builder.
func (_u *CampaignTargetHistoryUpdateOne) Where(ps ...predicate.CampaignTargetHistory) *CampaignTargetHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CampaignTargetHistoryUpdateOne) Select(field string, fields ...string) *CampaignTargetHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CampaignTargetHistory entity.
func (_u *CampaignTargetHistoryUpdateOne) Save(ctx context.Context) (*CampaignTargetHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CampaignTargetHistoryUpdateOne) SaveX(ctx context.Context) *CampaignTargetHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CampaignTargetHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CampaignTargetHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CampaignTargetHistoryUpdateOne) sqlSave(ctx context.Context) (_node *CampaignTargetHistory, err error) {
	_spec := sqlgraph.NewUpdateSpec(campaigntargethistory.Table, campaigntargethistory.Columns, sqlgraph.NewFieldSpec(campaigntargethistory.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`historygenerated: missing "CampaignTargetHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, campaigntargethistory.FieldID)
		for _, f := range fields {
			if !campaigntargethistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("historygenerated: invalid field %q for query", f)}
			}
			if f != campaigntargethistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RefCleared() {
		_spec.ClearField(campaigntargethistory.FieldRef, field.TypeString)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(campaigntargethistory.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(campaigntargethistory.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(campaigntargethistory.FieldCreatedBy, field.TypeString)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(campaigntargethistory.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.UpdatedByImpersonatorCleared() {
		_spec.ClearField(campaigntargethistory.FieldUpdatedByImpersonator, field.TypeString)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(campaigntargethistory.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(campaigntargethistory.FieldDeletedBy, field.TypeString)
	}
	if _u.mutation.OwnerIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldOwnerID, field.TypeString)
	}
	if _u.mutation.WorkflowEligibleMarkerCleared() {
		_spec.ClearField(campaigntargethistory.FieldWorkflowEligibleMarker, field.TypeBool)
	}
	if _u.mutation.CampaignIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldCampaignID, field.TypeString)
	}
	if _u.mutation.ContactIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldContactID, field.TypeString)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldUserID, field.TypeString)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldGroupID, field.TypeString)
	}
	if _u.mutation.SubscriberIDCleared() {
		_spec.ClearField(campaigntargethistory.FieldSubscriberID, field.TypeString)
	}
	if _u.mutation.FullNameCleared() {
		_spec.ClearField(campaigntargethistory.FieldFullName, field.TypeString)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(campaigntargethistory.FieldSentAt, field.TypeTime)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(campaigntargethistory.FieldCompletedAt, field.TypeTime)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(campaigntargethistory.FieldMetadata, field.TypeJSON)
	}
	_node = &CampaignTargetHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{campaigntargethistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
