//go:build !enthistorycodegen

// Code generated by ent, DO NOT EDIT.

package historygenerated

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/theopenlane/core/common/enums"
	"github.com/theopenlane/core/internal/ent/historygenerated/emailtemplatehistory"
	"github.com/theopenlane/entx/history"
)

// EmailTemplateHistory is the model entity for the EmailTemplateHistory schema.
type EmailTemplateHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// HistoryTime holds the value of the "history_time" field.
	HistoryTime time.Time `json:"history_time,omitempty"`
	// Ref holds the value of the "ref" field.
	Ref string `json:"ref,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation history.OpType `json:"operation,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// DeletedBy holds the value of the "deleted_by" field.
	DeletedBy string `json:"deleted_by,omitempty"`
	// the ID of the organization owner of the object
	OwnerID string `json:"owner_id,omitempty"`
	// indicates if the record is owned by the the openlane system and not by an organization
	SystemOwned bool `json:"system_owned,omitempty"`
	// internal notes about the object creation, this field is only available to system admins
	InternalNotes *string `json:"internal_notes,omitempty"`
	// an internal identifier for the mapping, this field is only available to system admins
	SystemInternalID *string `json:"system_internal_id,omitempty"`
	// stable identifier for the template
	Key string `json:"key,omitempty"`
	// display name for the template
	Name string `json:"name,omitempty"`
	// description of the template
	Description string `json:"description,omitempty"`
	// template format for rendering
	Format enums.NotificationTemplateFormat `json:"format,omitempty"`
	// locale for the template, e.g. en-US
	Locale string `json:"locale,omitempty"`
	// subject template for email notifications
	SubjectTemplate string `json:"subject_template,omitempty"`
	// preheader/preview text template for email notifications
	PreheaderTemplate string `json:"preheader_template,omitempty"`
	// body template for the email
	BodyTemplate string `json:"body_template,omitempty"`
	// plain text fallback template for the email
	TextTemplate string `json:"text_template,omitempty"`
	// jsonschema for template data requirements
	Jsonconfig map[string]interface{} `json:"jsonconfig,omitempty"`
	// uischema for a template builder
	Uischema map[string]interface{} `json:"uischema,omitempty"`
	// additional template metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// whether the template is active
	Active bool `json:"active,omitempty"`
	// template version
	Version int `json:"version,omitempty"`
	// email branding configuration to apply for this template
	EmailBrandingID string `json:"email_branding_id,omitempty"`
	// integration used to deliver emails for this template
	IntegrationID string `json:"integration_id,omitempty"`
	// workflow definition associated with this template
	WorkflowDefinitionID string `json:"workflow_definition_id,omitempty"`
	// workflow instance associated with this template
	WorkflowInstanceID string `json:"workflow_instance_id,omitempty"`
	selectValues       sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EmailTemplateHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case emailtemplatehistory.FieldJsonconfig, emailtemplatehistory.FieldUischema, emailtemplatehistory.FieldMetadata:
			values[i] = new([]byte)
		case emailtemplatehistory.FieldOperation:
			values[i] = new(history.OpType)
		case emailtemplatehistory.FieldSystemOwned, emailtemplatehistory.FieldActive:
			values[i] = new(sql.NullBool)
		case emailtemplatehistory.FieldVersion:
			values[i] = new(sql.NullInt64)
		case emailtemplatehistory.FieldID, emailtemplatehistory.FieldRef, emailtemplatehistory.FieldCreatedBy, emailtemplatehistory.FieldUpdatedBy, emailtemplatehistory.FieldDeletedBy, emailtemplatehistory.FieldOwnerID, emailtemplatehistory.FieldInternalNotes, emailtemplatehistory.FieldSystemInternalID, emailtemplatehistory.FieldKey, emailtemplatehistory.FieldName, emailtemplatehistory.FieldDescription, emailtemplatehistory.FieldFormat, emailtemplatehistory.FieldLocale, emailtemplatehistory.FieldSubjectTemplate, emailtemplatehistory.FieldPreheaderTemplate, emailtemplatehistory.FieldBodyTemplate, emailtemplatehistory.FieldTextTemplate, emailtemplatehistory.FieldEmailBrandingID, emailtemplatehistory.FieldIntegrationID, emailtemplatehistory.FieldWorkflowDefinitionID, emailtemplatehistory.FieldWorkflowInstanceID:
			values[i] = new(sql.NullString)
		case emailtemplatehistory.FieldHistoryTime, emailtemplatehistory.FieldCreatedAt, emailtemplatehistory.FieldUpdatedAt, emailtemplatehistory.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EmailTemplateHistory fields.
func (_m *EmailTemplateHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emailtemplatehistory.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case emailtemplatehistory.FieldHistoryTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field history_time", values[i])
			} else if value.Valid {
				_m.HistoryTime = value.Time
			}
		case emailtemplatehistory.FieldRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ref", values[i])
			} else if value.Valid {
				_m.Ref = value.String
			}
		case emailtemplatehistory.FieldOperation:
			if value, ok := values[i].(*history.OpType); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value != nil {
				_m.Operation = *value
			}
		case emailtemplatehistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case emailtemplatehistory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case emailtemplatehistory.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case emailtemplatehistory.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case emailtemplatehistory.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case emailtemplatehistory.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = value.String
			}
		case emailtemplatehistory.FieldOwnerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				_m.OwnerID = value.String
			}
		case emailtemplatehistory.FieldSystemOwned:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field system_owned", values[i])
			} else if value.Valid {
				_m.SystemOwned = value.Bool
			}
		case emailtemplatehistory.FieldInternalNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field internal_notes", values[i])
			} else if value.Valid {
				_m.InternalNotes = new(string)
				*_m.InternalNotes = value.String
			}
		case emailtemplatehistory.FieldSystemInternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system_internal_id", values[i])
			} else if value.Valid {
				_m.SystemInternalID = new(string)
				*_m.SystemInternalID = value.String
			}
		case emailtemplatehistory.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case emailtemplatehistory.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case emailtemplatehistory.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case emailtemplatehistory.FieldFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field format", values[i])
			} else if value.Valid {
				_m.Format = enums.NotificationTemplateFormat(value.String)
			}
		case emailtemplatehistory.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				_m.Locale = value.String
			}
		case emailtemplatehistory.FieldSubjectTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_template", values[i])
			} else if value.Valid {
				_m.SubjectTemplate = value.String
			}
		case emailtemplatehistory.FieldPreheaderTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preheader_template", values[i])
			} else if value.Valid {
				_m.PreheaderTemplate = value.String
			}
		case emailtemplatehistory.FieldBodyTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body_template", values[i])
			} else if value.Valid {
				_m.BodyTemplate = value.String
			}
		case emailtemplatehistory.FieldTextTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text_template", values[i])
			} else if value.Valid {
				_m.TextTemplate = value.String
			}
		case emailtemplatehistory.FieldJsonconfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field jsonconfig", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Jsonconfig); err != nil {
					return fmt.Errorf("unmarshal field jsonconfig: %w", err)
				}
			}
		case emailtemplatehistory.FieldUischema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field uischema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Uischema); err != nil {
					return fmt.Errorf("unmarshal field uischema: %w", err)
				}
			}
		case emailtemplatehistory.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case emailtemplatehistory.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case emailtemplatehistory.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case emailtemplatehistory.FieldEmailBrandingID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email_branding_id", values[i])
			} else if value.Valid {
				_m.EmailBrandingID = value.String
			}
		case emailtemplatehistory.FieldIntegrationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field integration_id", values[i])
			} else if value.Valid {
				_m.IntegrationID = value.String
			}
		case emailtemplatehistory.FieldWorkflowDefinitionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_definition_id", values[i])
			} else if value.Valid {
				_m.WorkflowDefinitionID = value.String
			}
		case emailtemplatehistory.FieldWorkflowInstanceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_instance_id", values[i])
			} else if value.Valid {
				_m.WorkflowInstanceID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EmailTemplateHistory.
// This includes values selected through modifiers, order, etc.
func (_m *EmailTemplateHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this EmailTemplateHistory.
// Note that you need to call EmailTemplateHistory.Unwrap() before calling this method if this EmailTemplateHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EmailTemplateHistory) Update() *EmailTemplateHistoryUpdateOne {
	return NewEmailTemplateHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EmailTemplateHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EmailTemplateHistory) Unwrap() *EmailTemplateHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("historygenerated: EmailTemplateHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EmailTemplateHistory) String() string {
	var builder strings.Builder
	builder.WriteString("EmailTemplateHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("history_time=")
	builder.WriteString(_m.HistoryTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ref=")
	builder.WriteString(_m.Ref)
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(fmt.Sprintf("%v", _m.Operation))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_by=")
	builder.WriteString(_m.DeletedBy)
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(_m.OwnerID)
	builder.WriteString(", ")
	builder.WriteString("system_owned=")
	builder.WriteString(fmt.Sprintf("%v", _m.SystemOwned))
	builder.WriteString(", ")
	if v := _m.InternalNotes; v != nil {
		builder.WriteString("internal_notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SystemInternalID; v != nil {
		builder.WriteString("system_internal_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("format=")
	builder.WriteString(fmt.Sprintf("%v", _m.Format))
	builder.WriteString(", ")
	builder.WriteString("locale=")
	builder.WriteString(_m.Locale)
	builder.WriteString(", ")
	builder.WriteString("subject_template=")
	builder.WriteString(_m.SubjectTemplate)
	builder.WriteString(", ")
	builder.WriteString("preheader_template=")
	builder.WriteString(_m.PreheaderTemplate)
	builder.WriteString(", ")
	builder.WriteString("body_template=")
	builder.WriteString(_m.BodyTemplate)
	builder.WriteString(", ")
	builder.WriteString("text_template=")
	builder.WriteString(_m.TextTemplate)
	builder.WriteString(", ")
	builder.WriteString("jsonconfig=")
	builder.WriteString(fmt.Sprintf("%v", _m.Jsonconfig))
	builder.WriteString(", ")
	builder.WriteString("uischema=")
	builder.WriteString(fmt.Sprintf("%v", _m.Uischema))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("email_branding_id=")
	builder.WriteString(_m.EmailBrandingID)
	builder.WriteString(", ")
	builder.WriteString("integration_id=")
	builder.WriteString(_m.IntegrationID)
	builder.WriteString(", ")
	builder.WriteString("workflow_definition_id=")
	builder.WriteString(_m.WorkflowDefinitionID)
	builder.WriteString(", ")
	builder.WriteString("workflow_instance_id=")
	builder.WriteString(_m.WorkflowInstanceID)
	builder.WriteByte(')')
	return builder.String()
}

// EmailTemplateHistories is a parsable slice of EmailTemplateHistory.
type EmailTemplateHistories []*EmailTemplateHistory
