//go:build !enthistorycodegen

// Code generated by ent, DO NOT EDIT.

package historygenerated

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/theopenlane/core/internal/ent/historygenerated/predicate"

	"github.com/theopenlane/core/internal/ent/historygenerated/internal"
	"github.com/theopenlane/core/internal/ent/historygenerated/notificationtemplatehistory"
)

// NotificationTemplateHistoryDelete is the builder for deleting a NotificationTemplateHistory entity.
type NotificationTemplateHistoryDelete struct {
	config
	hooks    []Hook
	mutation *NotificationTemplateHistoryMutation
}

// Where appends a list predicates to the NotificationTemplateHistoryDelete builder.
func (_d *NotificationTemplateHistoryDelete) Where(ps ...predicate.NotificationTemplateHistory) *NotificationTemplateHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NotificationTemplateHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotificationTemplateHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NotificationTemplateHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(notificationtemplatehistory.Table, sqlgraph.NewFieldSpec(notificationtemplatehistory.FieldID, field.TypeString))
	_spec.Node.Schema = _d.schemaConfig.NotificationTemplateHistory
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NotificationTemplateHistoryDeleteOne is the builder for deleting a single NotificationTemplateHistory entity.
type NotificationTemplateHistoryDeleteOne struct {
	_d *NotificationTemplateHistoryDelete
}

// Where appends a list predicates to the NotificationTemplateHistoryDelete builder.
func (_d *NotificationTemplateHistoryDeleteOne) Where(ps ...predicate.NotificationTemplateHistory) *NotificationTemplateHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NotificationTemplateHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notificationtemplatehistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NotificationTemplateHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
