// Code generated by ent, DO NOT EDIT.

package historygenerated

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/theopenlane/core/internal/ent/historygenerated/predicate"
	"github.com/theopenlane/core/internal/ent/historygenerated/programhistory"
	"github.com/theopenlane/core/pkg/logx"

	"github.com/theopenlane/core/internal/ent/historygenerated/internal"
)

// ProgramHistoryQuery is the builder for querying ProgramHistory entities.
type ProgramHistoryQuery struct {
	config
	ctx        *QueryContext
	order      []programhistory.OrderOption
	inters     []Interceptor
	predicates []predicate.ProgramHistory
	loadTotal  []func(context.Context, []*ProgramHistory) error
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProgramHistoryQuery builder.
func (_q *ProgramHistoryQuery) Where(ps ...predicate.ProgramHistory) *ProgramHistoryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProgramHistoryQuery) Limit(limit int) *ProgramHistoryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProgramHistoryQuery) Offset(offset int) *ProgramHistoryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProgramHistoryQuery) Unique(unique bool) *ProgramHistoryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProgramHistoryQuery) Order(o ...programhistory.OrderOption) *ProgramHistoryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first ProgramHistory entity from the query.
// Returns a *NotFoundError when no ProgramHistory was found.
func (_q *ProgramHistoryQuery) First(ctx context.Context) (*ProgramHistory, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{programhistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProgramHistoryQuery) FirstX(ctx context.Context) *ProgramHistory {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProgramHistory ID from the query.
// Returns a *NotFoundError when no ProgramHistory ID was found.
func (_q *ProgramHistoryQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{programhistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ProgramHistoryQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProgramHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProgramHistory entity is found.
// Returns a *NotFoundError when no ProgramHistory entities are found.
func (_q *ProgramHistoryQuery) Only(ctx context.Context) (*ProgramHistory, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{programhistory.Label}
	default:
		return nil, &NotSingularError{programhistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProgramHistoryQuery) OnlyX(ctx context.Context) *ProgramHistory {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProgramHistory ID in the query.
// Returns a *NotSingularError when more than one ProgramHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ProgramHistoryQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{programhistory.Label}
	default:
		err = &NotSingularError{programhistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ProgramHistoryQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProgramHistories.
func (_q *ProgramHistoryQuery) All(ctx context.Context) ([]*ProgramHistory, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProgramHistory, *ProgramHistoryQuery]()
	return withInterceptors[[]*ProgramHistory](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProgramHistoryQuery) AllX(ctx context.Context) []*ProgramHistory {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProgramHistory IDs.
func (_q *ProgramHistoryQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(programhistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ProgramHistoryQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ProgramHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProgramHistoryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProgramHistoryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProgramHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("historygenerated: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProgramHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProgramHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProgramHistoryQuery) Clone() *ProgramHistoryQuery {
	if _q == nil {
		return nil
	}
	return &ProgramHistoryQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]programhistory.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.ProgramHistory{}, _q.predicates...),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		HistoryTime time.Time `json:"history_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProgramHistory.Query().
//		GroupBy(programhistory.FieldHistoryTime).
//		Aggregate(historygenerated.Count()).
//		Scan(ctx, &v)
func (_q *ProgramHistoryQuery) GroupBy(field string, fields ...string) *ProgramHistoryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProgramHistoryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = programhistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		HistoryTime time.Time `json:"history_time,omitempty"`
//	}
//
//	client.ProgramHistory.Query().
//		Select(programhistory.FieldHistoryTime).
//		Scan(ctx, &v)
func (_q *ProgramHistoryQuery) Select(fields ...string) *ProgramHistorySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProgramHistorySelect{ProgramHistoryQuery: _q}
	sbuild.label = programhistory.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProgramHistorySelect configured with the given aggregations.
func (_q *ProgramHistoryQuery) Aggregate(fns ...AggregateFunc) *ProgramHistorySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProgramHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("historygenerated: uninitialized interceptor (forgotten import historygenerated/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !programhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("historygenerated: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if programhistory.Policy == nil {
		return errors.New("historygenerated: uninitialized programhistory.Policy (forgotten import historygenerated/runtime?)")
	}
	if err := programhistory.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *ProgramHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProgramHistory, error) {
	var (
		nodes = []*ProgramHistory{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProgramHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProgramHistory{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = _q.schemaConfig.ProgramHistory
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProgramHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Schema = _q.schemaConfig.ProgramHistory
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProgramHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(programhistory.Table, programhistory.Columns, sqlgraph.NewFieldSpec(programhistory.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, programhistory.FieldID)
		for i := range fields {
			if fields[i] != programhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProgramHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(programhistory.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = programhistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(_q.schemaConfig.ProgramHistory)
	ctx = internal.NewSchemaConfigContext(ctx, _q.schemaConfig)
	selector.WithContext(ctx)
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *ProgramHistoryQuery) Modify(modifiers ...func(s *sql.Selector)) *ProgramHistorySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// CountIDs returns the count of ids with FGA batch filtering applied
func (phq *ProgramHistoryQuery) CountIDs(ctx context.Context) (int, error) {
	logx.FromContext(ctx).Debug().Str("query_type", "ProgramHistory").Str("operation", "count_ids").Msg("CountIDs: starting")

	ctx = setContextOp(ctx, phq.ctx, ent.OpQueryIDs)

	ids, err := phq.IDs(ctx)
	if err != nil {
		logx.FromContext(ctx).Error().Err(err).Str("query_type", "ProgramHistory").Str("operation", "count_ids").Msg("CountIDs: IDs() failed")

		return 0, err
	}

	logx.FromContext(ctx).Debug().Str("query_type", "ProgramHistory").Str("operation", "count_ids").Int("count", len(ids)).Msg("CountIDs: completed")

	return len(ids), nil
}

// ProgramHistoryGroupBy is the group-by builder for ProgramHistory entities.
type ProgramHistoryGroupBy struct {
	selector
	build *ProgramHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProgramHistoryGroupBy) Aggregate(fns ...AggregateFunc) *ProgramHistoryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProgramHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProgramHistoryQuery, *ProgramHistoryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProgramHistoryGroupBy) sqlScan(ctx context.Context, root *ProgramHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProgramHistorySelect is the builder for selecting fields of ProgramHistory entities.
type ProgramHistorySelect struct {
	*ProgramHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProgramHistorySelect) Aggregate(fns ...AggregateFunc) *ProgramHistorySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProgramHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProgramHistoryQuery, *ProgramHistorySelect](ctx, _s.ProgramHistoryQuery, _s, _s.inters, v)
}

func (_s *ProgramHistorySelect) sqlScan(ctx context.Context, root *ProgramHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *ProgramHistorySelect) Modify(modifiers ...func(s *sql.Selector)) *ProgramHistorySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
