//go:build !enthistorycodegen

// Code generated by ent, DO NOT EDIT.

package historygenerated

// The schema-stitching logic is generated in github.com/theopenlane/core/internal/ent/historygenerated/runtime/runtime.go
