//go:build !enthistorycodegen

// Code generated by ent, DO NOT EDIT.

package historygenerated

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/theopenlane/core/internal/ent/historygenerated/predicate"

	"github.com/theopenlane/core/internal/ent/historygenerated/internal"
	"github.com/theopenlane/core/internal/ent/historygenerated/sladefinitionhistory"
)

// SLADefinitionHistoryDelete is the builder for deleting a SLADefinitionHistory entity.
type SLADefinitionHistoryDelete struct {
	config
	hooks    []Hook
	mutation *SLADefinitionHistoryMutation
}

// Where appends a list predicates to the SLADefinitionHistoryDelete builder.
func (_d *SLADefinitionHistoryDelete) Where(ps ...predicate.SLADefinitionHistory) *SLADefinitionHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SLADefinitionHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SLADefinitionHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SLADefinitionHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sladefinitionhistory.Table, sqlgraph.NewFieldSpec(sladefinitionhistory.FieldID, field.TypeString))
	_spec.Node.Schema = _d.schemaConfig.SLADefinitionHistory
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SLADefinitionHistoryDeleteOne is the builder for deleting a single SLADefinitionHistory entity.
type SLADefinitionHistoryDeleteOne struct {
	_d *SLADefinitionHistoryDelete
}

// Where appends a list predicates to the SLADefinitionHistoryDelete builder.
func (_d *SLADefinitionHistoryDeleteOne) Where(ps ...predicate.SLADefinitionHistory) *SLADefinitionHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SLADefinitionHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sladefinitionhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SLADefinitionHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
