//go:build !enthistorycodegen

// Code generated by ent, DO NOT EDIT.

package historygenerated

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/theopenlane/core/v2/internal/ent/historygenerated/predicate"
	"github.com/theopenlane/core/v2/internal/ent/historygenerated/vendorscoringconfighistory"
)

// VendorScoringConfigHistoryUpdate is the builder for updating VendorScoringConfigHistory entities.
type VendorScoringConfigHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *VendorScoringConfigHistoryMutation
}

// Where appends a list predicates to the VendorScoringConfigHistoryUpdate builder.
func (_u *VendorScoringConfigHistoryUpdate) Where(ps ...predicate.VendorScoringConfigHistory) *VendorScoringConfigHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the VendorScoringConfigHistoryMutation object of the builder.
func (_u *VendorScoringConfigHistoryUpdate) Mutation() *VendorScoringConfigHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VendorScoringConfigHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VendorScoringConfigHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VendorScoringConfigHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VendorScoringConfigHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *VendorScoringConfigHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(vendorscoringconfighistory.Table, vendorscoringconfighistory.Columns, sqlgraph.NewFieldSpec(vendorscoringconfighistory.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RefCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldRef, field.TypeString)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldCreatedBy, field.TypeString)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.UpdatedByImpersonatorCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldUpdatedByImpersonator, field.TypeString)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldDeletedBy, field.TypeString)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldTags, field.TypeJSON)
	}
	if _u.mutation.OwnerIDCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldOwnerID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vendorscoringconfighistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VendorScoringConfigHistoryUpdateOne is the builder for updating a single VendorScoringConfigHistory entity.
type VendorScoringConfigHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VendorScoringConfigHistoryMutation
}

// Mutation returns the VendorScoringConfigHistoryMutation object of the builder.
func (_u *VendorScoringConfigHistoryUpdateOne) Mutation() *VendorScoringConfigHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the VendorScoringConfigHistoryUpdate builder.
func (_u *VendorScoringConfigHistoryUpdateOne) Where(ps ...predicate.VendorScoringConfigHistory) *VendorScoringConfigHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VendorScoringConfigHistoryUpdateOne) Select(field string, fields ...string) *VendorScoringConfigHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VendorScoringConfigHistory entity.
func (_u *VendorScoringConfigHistoryUpdateOne) Save(ctx context.Context) (*VendorScoringConfigHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VendorScoringConfigHistoryUpdateOne) SaveX(ctx context.Context) *VendorScoringConfigHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VendorScoringConfigHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VendorScoringConfigHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *VendorScoringConfigHistoryUpdateOne) sqlSave(ctx context.Context) (_node *VendorScoringConfigHistory, err error) {
	_spec := sqlgraph.NewUpdateSpec(vendorscoringconfighistory.Table, vendorscoringconfighistory.Columns, sqlgraph.NewFieldSpec(vendorscoringconfighistory.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`historygenerated: missing "VendorScoringConfigHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vendorscoringconfighistory.FieldID)
		for _, f := range fields {
			if !vendorscoringconfighistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("historygenerated: invalid field %q for query", f)}
			}
			if f != vendorscoringconfighistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RefCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldRef, field.TypeString)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldCreatedAt, field.TypeTime)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldCreatedBy, field.TypeString)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.UpdatedByImpersonatorCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldUpdatedByImpersonator, field.TypeString)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldDeletedBy, field.TypeString)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldTags, field.TypeJSON)
	}
	if _u.mutation.OwnerIDCleared() {
		_spec.ClearField(vendorscoringconfighistory.FieldOwnerID, field.TypeString)
	}
	_node = &VendorScoringConfigHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vendorscoringconfighistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
