services:
  api:
    image: ghcr.io/theopenlane/core:latest
    command:
      - serve
      - --debug
      - --pretty
      - --config=/config/.config.yaml
    volumes:
      - type: bind
        source: ${PWD}/config/.config.docker.yaml
        target: /config/.config.yaml
        read_only: true
    ports:
      - "17608:17608"
    restart: unless-stopped
    networks:
      - default
