services:
  postgres:
    volumes:
      - ./configs/keycloak/init.sql:/docker-entrypoint-initdb.d/init_keycloak.sql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    env_file:
      - ${PWD}/docker/configs/keycloak/.env-example
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8180
    ports:
      - 8180:8180
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
