services:
  proxy:
    image: envoyproxy/envoy:contrib-v1.30-latest
    ports:
      - "${PORT_PROXY:-10000}:10000"
      - "${PORT_ADMIN:-8001}:8001"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  kafka-server:
    image: docker.io/bitnami/kafka:3.9
    ports:
      - "9092:9092"
    environment:
      - ALLOW_INTERNAL_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-server:9093
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,INTERNAL://kafka-server:9092,EXTERNAL://kafka-server:10000
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-server:9092,EXTERNAL://proxy:10000
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    tty: true
    volumes:
      - "kafka_data:/bitnami"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: openlane
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-server:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 11001
      KAFKA_CLUSTERS_0_METRICS_TYPE: PROMETHEUS

volumes:
  kafka_data:
    driver: local
