version: "3"

tasks:
  default:
    silent: false
    cmds:
      - task --list

  genjsonschema:
    desc: generates the jsonschema for the catalog
    cmds:
      - go run genjsonschema/catalog_schema.go

  genyaml:
    desc: generates the go code output from the catalog yaml
    cmds:
      - go run genyaml/yamlgen.go

  all:
    desc: runs all the generation tasks
    cmds:
      - task: genjsonschema
      - task: genyaml

  all:sandbox:
    desc: runs all the generation tasks for the sandbox catalog
    env:
      OPENLANE_CATALOG_SANDBOX: "true"
    cmds:
      - task: genjsonschema
      - task: genyaml
