version: "3"

tasks:
  default:
    silent: false
    cmds:
      - task --list

  genjsonschema:
    desc: generates the jsonschema for the catalog
    cmds:
      - go run genjsonschema/catalog_schema.go

  genyaml:
    desc: generates the go code output from the catalog yaml
    vars:
      OPENLANE_CATALOG_SANDBOX: "{{ .OPENLANE_CATALOG_SANDBOX | default false }}"
    cmds:
      - go run genyaml/yamlgen.go

  all:
    desc: runs all the generation tasks
    vars:
      OPENLANE_CATALOG_SANDBOX: "{{ .OPENLANE_CATALOG_SANDBOX | default false }}"
    cmds:
      - task: genjsonschema
      - task: genyaml
