version: "3"

tasks:
  default:
    silent: false
    cmds:
      - task --list

  genjsonschema:
    desc: generates the jsonschema for the catalog
    cmds:
      - go run genjsonschema/catalog_schema.go

  genyaml:
    desc: generates the go code output from the catalog yaml
    vars:
      USE_SANDBOX: "{{ .CORE_ENTCONFIG_MODULES_USESANDBOX }}"
      OPENLANE_CATALOG_SANDBOX: "{{if .USE_SANDBOX}}{{.USE_SANDBOX}}{{else}}{{.OPENLANE_CATALOG_SANDBOX | default false}}{{end}}"
    cmds:
      - go run genyaml/yamlgen.go

  all:
    desc: runs all the generation tasks
    vars:
      USE_SANDBOX: "{{ .CORE_ENTCONFIG_MODULES_USESANDBOX }}"
      OPENLANE_CATALOG_SANDBOX: "{{if .USE_SANDBOX}}{{.USE_SANDBOX}}{{else}}{{.OPENLANE_CATALOG_SANDBOX | default false}}{{end}}"
    cmds:
      - task: genjsonschema
      - task: genyaml
