// Code generated by gencatalog.go; DO NOT EDIT.

package gencatalog

import catalog "github.com/theopenlane/core/pkg/catalog"

var DefaultCatalog = catalog.Catalog{
	Addons: map[string]catalog.Feature{
		"domain_scanning": catalog.Feature{
			Audience: "private",
			Billing: catalog.Billing{Prices: []catalog.Price{catalog.Price{
				Interval:   "month",
				LookupKey:  "domain_scan_month",
				Nickname:   "domain_scan_month",
				UnitAmount: int64(100),
			}, catalog.Price{
				Interval:   "year",
				LookupKey:  "domain_scan_annual",
				Nickname:   "domain_scan_annual",
				UnitAmount: int64(1000),
			}}},
			Description: "Domain and Vulnerability Scanning",
			DisplayName: "Scanning",
		},
		"extra_evidence_storage": catalog.Feature{
			Audience: "public",
			Billing: catalog.Billing{Prices: []catalog.Price{catalog.Price{
				Interval:   "month",
				LookupKey:  "evidence_storage_100gb",
				Metadata:   map[string]string{"increment_gb": "100"},
				Nickname:   "evidence_storage_100gb",
				UnitAmount: int64(10),
			}}},
			Description: "Additional evidence storage for compliance",
			DisplayName: "Additional Evidence Storage (100GB)",
			Usage:       &catalog.Usage{EvidenceStorageGB: int64(100)},
		},
		"policy-management": catalog.Feature{
			Audience: "beta",
			Billing: catalog.Billing{Prices: []catalog.Price{catalog.Price{
				Interval:   "month",
				LookupKey:  "price_policy_monthly",
				Nickname:   "price_policy_monthly",
				UnitAmount: int64(10),
			}, catalog.Price{
				Interval:   "month",
				LookupKey:  "price_policy_annual",
				Nickname:   "price_policy_annual",
				UnitAmount: int64(100),
			}}},
			Description: "Policy and Procedure Management",
			DisplayName: "Policy & Procedure Management",
		},
		"risk-management": catalog.Feature{
			Audience: "beta",
			Billing: catalog.Billing{Prices: []catalog.Price{catalog.Price{
				Interval:   "month",
				LookupKey:  "price_risk_monthly",
				Nickname:   "price_risk_monthly",
				UnitAmount: int64(10),
			}, catalog.Price{
				Interval:   "year",
				LookupKey:  "price_risk_annual",
				Nickname:   "price_risk_annual",
				UnitAmount: int64(100),
			}}},
			Description: "Risk Management",
			DisplayName: "Risk Management",
		},
	},
	Modules: map[string]catalog.Feature{
		"base": catalog.Feature{
			Audience: "public",
			Billing: catalog.Billing{Prices: []catalog.Price{catalog.Price{
				Interval:   "year",
				LookupKey:  "base_free",
				Nickname:   "base_free",
				PriceID:    "price_1RdciXR7q8Ny5Jw059Kw4ChM",
				UnitAmount: int64(0),
			}}},
			Description: "Core system access",
			DisplayName: "Base Module",
		},
		"compliance": catalog.Feature{
			Audience: "public",
			Billing: catalog.Billing{Prices: []catalog.Price{catalog.Price{
				Interval:   "month",
				LookupKey:  "price_compliance_month",
				Metadata:   map[string]string{"tier": "base"},
				Nickname:   "price_compliance_month",
				PriceID:    "price_1RbjHUR7q8Ny5Jw09vtTo1rQ",
				UnitAmount: int64(450),
			}, catalog.Price{
				Interval:   "year",
				LookupKey:  "price_compliance_annual",
				Metadata:   map[string]string{"tier": "base"},
				Nickname:   "price_compliance_annual",
				PriceID:    "price_1RdciXR7q8Ny5Jw0hfaLuSef",
				UnitAmount: int64(5000),
			}}},
			Description: "Core compliance automation",
			DisplayName: "Compliance Module",
			Usage:       &catalog.Usage{EvidenceStorageGB: int64(250)},
		},
		"entity-management": catalog.Feature{
			Audience: "private",
			Billing: catalog.Billing{Prices: []catalog.Price{catalog.Price{
				Interval:   "month",
				LookupKey:  "price_vendor_monthly",
				Nickname:   "price_vendor_monthly",
				UnitAmount: int64(200),
			}, catalog.Price{
				Interval:   "year",
				LookupKey:  "price_vendor_annual",
				Nickname:   "price_vendor_annual",
				UnitAmount: int64(2000),
			}}},
			Description: "Vendor Risk Management",
			DisplayName: "Vendor Management",
		},
		"trust_center": catalog.Feature{
			Audience: "beta",
			Billing: catalog.Billing{Prices: []catalog.Price{catalog.Price{
				Interval:   "month",
				LookupKey:  "price_trust_center_monthly",
				Nickname:   "price_trust_center_monthly",
				PriceID:    "price_1RaiEgR7q8Ny5Jw0bGDA8we8",
				UnitAmount: int64(300),
			}, catalog.Price{
				Interval:   "year",
				LookupKey:  "price_trust_center_annual",
				Nickname:   "price_trust_center_annual",
				PriceID:    "price_1RaiFmR7q8Ny5Jw0PvAVtiGX",
				UnitAmount: int64(3000),
			}}},
			Description: "Public security portal",
			DisplayName: "Trust Center",
		},
		"vulnerability-management": catalog.Feature{
			Audience: "private",
			Billing: catalog.Billing{Prices: []catalog.Price{catalog.Price{
				Interval:   "month",
				LookupKey:  "price_vulnerability_monthly",
				Nickname:   "price_vulnerability_monthly",
				UnitAmount: int64(100),
			}, catalog.Price{
				Interval:   "year",
				LookupKey:  "price_vulnerability_annual",
				Nickname:   "price_vulnerability_annual",
				UnitAmount: int64(1000),
			}}},
			Description: "vulnerability management",
			DisplayName: "Vulnerability Management",
		},
	},
	SHA:     "ae5bcf31543244e0bc0b0a14a4374ae2f199eebe805de0ad58f20d36b5d5649b",
	Version: "v0.0.2",
}
