authz:
  enabled: true
  hostUrl: http://localhost:8080
  createNewModel: true
  storeName: openlane-e2e-database
  ignoreDuplicateKeyError: true
  credentials:
    apiToken: QKwHEmWX99RnFh28eSRJ3GWlfb2FQkL7toh1GJpzch1mMkVeMg

objectStorage:
  enabled: true
  devMode: false
  ensureAvailable: false
  credentialSync:
    enabled: true
  maxMemoryMB: 50
  maxSizeMB: 100
  keys:
    - "uploadFile"
  providers:
    s3:
      enabled: false
      bucket: ""
      endpoint: ""
      region: ""
      credentials: {}
    cloudflareR2:
      enabled: false
      bucket: ""
      endpoint: ""
      region: ""
      credentials: {}
    gcs:
      enabled: false
      bucket: ""
      endpoint: ""
      region: ""
      credentials: {}
    disk:
      enabled: false
      bucket: ""
      endpoint: ""
      region: ""
      credentials: {}
    database:
      enabled: true
      bucket: database-provider
      endpoint: ""
      region: ""
      credentials: {}
