// Code generated by ent. DO NOT EDIT.
// This file is generated to provide type-safe workflow domains for approval scopes.
package workflowgenerated

import (
	"fmt"
	"sort"
	"strings"

	"github.com/theopenlane/core/common/enums"
)

// WorkflowDomain represents a canonical approval domain for workflow proposals.
// A domain is the combination of an object type and the fields requiring approval.
type WorkflowDomain struct {
	// ObjectType is the workflow object type this domain applies to
	ObjectType enums.WorkflowObjectType
	// Fields is the sorted list of field names in this domain
	Fields []string
}

// Key returns the canonical domain key including object type prefix.
// Format: "ObjectType:field1,field2,field3" (fields are sorted).
func (d WorkflowDomain) Key() string {
	if len(d.Fields) == 0 {
		return string(d.ObjectType)
	}
	fields := make([]string, len(d.Fields))
	copy(fields, d.Fields)
	sort.Strings(fields)
	return string(d.ObjectType) + ":" + strings.Join(fields, ",")
}

// WorkflowEligibleFields maps object types to their workflow-eligible field names.
// Use this to validate that fields in a domain are valid for the object type.
var WorkflowEligibleFields = map[enums.WorkflowObjectType]map[string]struct{}{
	enums.WorkflowObjectTypeActionPlan: {
		"status":                   {},
		"details":                  {},
		"details_json":             {},
		"workflow_eligible_marker": {},
	},
	enums.WorkflowObjectTypeCampaign: {
		"workflow_eligible_marker": {},
		"status":                   {},
		"is_active":                {},
		"scheduled_at":             {},
		"due_date":                 {},
		"is_recurring":             {},
		"recurrence_frequency":     {},
		"recipient_count":          {},
		"resend_count":             {},
	},
	enums.WorkflowObjectTypeCampaignTarget: {
		"workflow_eligible_marker": {},
		"status":                   {},
		"sent_at":                  {},
		"completed_at":             {},
	},
	enums.WorkflowObjectTypeControl: {
		"title":                        {},
		"reference_id":                 {},
		"auditor_reference_id":         {},
		"responsible_party_id":         {},
		"status":                       {},
		"reference_framework":          {},
		"reference_framework_revision": {},
		"category":                     {},
		"category_id":                  {},
		"subcategory":                  {},
		"control_owner_id":             {},
		"workflow_eligible_marker":     {},
	},
	enums.WorkflowObjectTypeEvidence: {
		"workflow_eligible_marker": {},
	},
	enums.WorkflowObjectTypeIdentityHolder: {
		"workflow_eligible_marker": {},
		"status":                   {},
		"is_active":                {},
		"start_date":               {},
		"end_date":                 {},
	},
	enums.WorkflowObjectTypeInternalPolicy: {
		"status":                   {},
		"details":                  {},
		"details_json":             {},
		"workflow_eligible_marker": {},
	},
	enums.WorkflowObjectTypePlatform: {
		"workflow_eligible_marker": {},
		"business_purpose":         {},
		"scope_statement":          {},
		"status":                   {},
		"contains_pii":             {},
	},
	enums.WorkflowObjectTypeProcedure: {
		"status":                   {},
		"details":                  {},
		"details_json":             {},
		"workflow_eligible_marker": {},
	},
	enums.WorkflowObjectTypeSubcontrol: {
		"title":                        {},
		"reference_id":                 {},
		"auditor_reference_id":         {},
		"responsible_party_id":         {},
		"status":                       {},
		"reference_framework":          {},
		"reference_framework_revision": {},
		"category":                     {},
		"category_id":                  {},
		"subcategory":                  {},
		"control_owner_id":             {},
		"workflow_eligible_marker":     {},
	},
}

// ErrInvalidObjectType is returned when an object type is not workflow-eligible
var ErrInvalidObjectType = fmt.Errorf("object type is not workflow-eligible")

// ErrInvalidDomainField is returned when a field is not workflow-eligible for the object type
var ErrInvalidDomainField = fmt.Errorf("field is not workflow-eligible for object type")

// ErrEmptyDomainFields is returned when no fields are provided for a domain
var ErrEmptyDomainFields = fmt.Errorf("domain requires at least one field")

// NewWorkflowDomain creates a validated domain for an object type and fields.
// Fields are automatically sorted to ensure canonical ordering.
// Returns an error if the object type or any field is not workflow-eligible.
func NewWorkflowDomain(objectType enums.WorkflowObjectType, fields []string) (WorkflowDomain, error) {
	if len(fields) == 0 {
		return WorkflowDomain{}, ErrEmptyDomainFields
	}

	eligible, ok := WorkflowEligibleFields[objectType]
	if !ok {
		return WorkflowDomain{}, fmt.Errorf("%w: %s", ErrInvalidObjectType, objectType)
	}

	sorted := make([]string, len(fields))
	copy(sorted, fields)
	sort.Strings(sorted)

	for _, field := range sorted {
		if _, ok := eligible[field]; !ok {
			return WorkflowDomain{}, fmt.Errorf("%w: %s.%s", ErrInvalidDomainField, objectType, field)
		}
	}

	return WorkflowDomain{
		ObjectType: objectType,
		Fields:     sorted,
	}, nil
}
