CREATE DATABASE openfga;

GRANT ALL PRIVILEGES ON DATABASE openfga TO postgres;

CREATE DATABASE core;

GRANT ALL PRIVILEGES ON DATABASE core TO postgres;

CREATE DATABASE jobs;

GRANT ALL PRIVILEGES ON DATABASE jobs TO postgres;

CREATE DATABASE windmill;

GRANT ALL PRIVILEGES ON DATABASE windmill TO postgres;
