version: '3'

includes:
  docker:
    taskfile: ../docker/Taskfile.yaml
    dir: ../docker
    aliases: [compose]

tasks:
  create:
    desc: creates an atlas migration if one is needed based on the ent schema definitions
    cmds:
      - |
        echo "If there is no schema to generate, this will not create a file (hint: name it your branch name if you're not sure) - enter the name of the migration:"
        read migration;
        go run create_migrations.go ${migration};

  lint:
    desc: lints the pushed migration files
    ignore_error: true
    cmds:
      - atlas migrate lint --dir "file://migrations" --env dev

  lint:open:
    desc: lints the pushed migration files and open the lint report in the browser
    ignore_error: true
    cmds:
      - atlas migrate lint --dir "file://migrations" --env dev -w

  resethash:
    desc: re-sets the checksum created by the atlas package so that a complete migration can be re-created if deleted
    cmds:
      - atlas migrate hash --dir="file://migrations"
      - atlas migrate hash --dir="file://migrations-goose-postgres"

  newschema:
    desc: generate a new ent schema from template
    silent: true
    cmds:
      - go run -mod=readonly entgo.io/ent/cmd/ent new --template ../ent/base/entinit.tmpl --target ../ent/schema {{.CLI_ARGS}}
