version: '3'

vars:
  BIN: bin/simple-example

tasks:
  default:
    desc: Build and run the simple example
    cmds:
      - task: run

  build:
    desc: Build the simple example binary
    cmds:
      - mkdir -p bin
      - go build -tags examples -o {{.BIN}} .

  run:
    desc: Execute the simple example
    deps:
      - build
    cmds:
      - ./{{.BIN}}

  clean:
    desc: Remove build artifacts and temporary files
    cmds:
      - rm -rf bin
      - rm -rf tmp
