//go:build !enthistorycodegen

// Code generated by ent, DO NOT EDIT.

package workflowinstancehistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/theopenlane/core/internal/ent/historygenerated/predicate"
	"github.com/theopenlane/common/enums"
	"github.com/theopenlane/entx/history"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContainsFold(FieldID, id))
}

// HistoryTime applies equality check predicate on the "history_time" field. It's identical to HistoryTimeEQ.
func HistoryTime(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldHistoryTime, v))
}

// Ref applies equality check predicate on the "ref" field. It's identical to RefEQ.
func Ref(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldRef, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldDeletedBy, v))
}

// DisplayID applies equality check predicate on the "display_id" field. It's identical to DisplayIDEQ.
func DisplayID(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldDisplayID, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldOwnerID, v))
}

// WorkflowDefinitionID applies equality check predicate on the "workflow_definition_id" field. It's identical to WorkflowDefinitionIDEQ.
func WorkflowDefinitionID(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldWorkflowDefinitionID, v))
}

// LastEvaluatedAt applies equality check predicate on the "last_evaluated_at" field. It's identical to LastEvaluatedAtEQ.
func LastEvaluatedAt(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldLastEvaluatedAt, v))
}

// ControlID applies equality check predicate on the "control_id" field. It's identical to ControlIDEQ.
func ControlID(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldControlID, v))
}

// InternalPolicyID applies equality check predicate on the "internal_policy_id" field. It's identical to InternalPolicyIDEQ.
func InternalPolicyID(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldInternalPolicyID, v))
}

// EvidenceID applies equality check predicate on the "evidence_id" field. It's identical to EvidenceIDEQ.
func EvidenceID(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldEvidenceID, v))
}

// HistoryTimeEQ applies the EQ predicate on the "history_time" field.
func HistoryTimeEQ(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldHistoryTime, v))
}

// HistoryTimeNEQ applies the NEQ predicate on the "history_time" field.
func HistoryTimeNEQ(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldHistoryTime, v))
}

// HistoryTimeIn applies the In predicate on the "history_time" field.
func HistoryTimeIn(vs ...time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldHistoryTime, vs...))
}

// HistoryTimeNotIn applies the NotIn predicate on the "history_time" field.
func HistoryTimeNotIn(vs ...time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldHistoryTime, vs...))
}

// HistoryTimeGT applies the GT predicate on the "history_time" field.
func HistoryTimeGT(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldHistoryTime, v))
}

// HistoryTimeGTE applies the GTE predicate on the "history_time" field.
func HistoryTimeGTE(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldHistoryTime, v))
}

// HistoryTimeLT applies the LT predicate on the "history_time" field.
func HistoryTimeLT(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldHistoryTime, v))
}

// HistoryTimeLTE applies the LTE predicate on the "history_time" field.
func HistoryTimeLTE(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldHistoryTime, v))
}

// RefEQ applies the EQ predicate on the "ref" field.
func RefEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldRef, v))
}

// RefNEQ applies the NEQ predicate on the "ref" field.
func RefNEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldRef, v))
}

// RefIn applies the In predicate on the "ref" field.
func RefIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldRef, vs...))
}

// RefNotIn applies the NotIn predicate on the "ref" field.
func RefNotIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldRef, vs...))
}

// RefGT applies the GT predicate on the "ref" field.
func RefGT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldRef, v))
}

// RefGTE applies the GTE predicate on the "ref" field.
func RefGTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldRef, v))
}

// RefLT applies the LT predicate on the "ref" field.
func RefLT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldRef, v))
}

// RefLTE applies the LTE predicate on the "ref" field.
func RefLTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldRef, v))
}

// RefContains applies the Contains predicate on the "ref" field.
func RefContains(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContains(FieldRef, v))
}

// RefHasPrefix applies the HasPrefix predicate on the "ref" field.
func RefHasPrefix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasPrefix(FieldRef, v))
}

// RefHasSuffix applies the HasSuffix predicate on the "ref" field.
func RefHasSuffix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasSuffix(FieldRef, v))
}

// RefIsNil applies the IsNil predicate on the "ref" field.
func RefIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldRef))
}

// RefNotNil applies the NotNil predicate on the "ref" field.
func RefNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldRef))
}

// RefEqualFold applies the EqualFold predicate on the "ref" field.
func RefEqualFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEqualFold(FieldRef, v))
}

// RefContainsFold applies the ContainsFold predicate on the "ref" field.
func RefContainsFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContainsFold(FieldRef, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v history.OpType) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v history.OpType) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...history.OpType) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...history.OpType) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldOperation, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldUpdatedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldDeletedAt))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByContains applies the Contains predicate on the "deleted_by" field.
func DeletedByContains(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContains(FieldDeletedBy, v))
}

// DeletedByHasPrefix applies the HasPrefix predicate on the "deleted_by" field.
func DeletedByHasPrefix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasPrefix(FieldDeletedBy, v))
}

// DeletedByHasSuffix applies the HasSuffix predicate on the "deleted_by" field.
func DeletedByHasSuffix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasSuffix(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldDeletedBy))
}

// DeletedByEqualFold applies the EqualFold predicate on the "deleted_by" field.
func DeletedByEqualFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEqualFold(FieldDeletedBy, v))
}

// DeletedByContainsFold applies the ContainsFold predicate on the "deleted_by" field.
func DeletedByContainsFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContainsFold(FieldDeletedBy, v))
}

// DisplayIDEQ applies the EQ predicate on the "display_id" field.
func DisplayIDEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldDisplayID, v))
}

// DisplayIDNEQ applies the NEQ predicate on the "display_id" field.
func DisplayIDNEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldDisplayID, v))
}

// DisplayIDIn applies the In predicate on the "display_id" field.
func DisplayIDIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldDisplayID, vs...))
}

// DisplayIDNotIn applies the NotIn predicate on the "display_id" field.
func DisplayIDNotIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldDisplayID, vs...))
}

// DisplayIDGT applies the GT predicate on the "display_id" field.
func DisplayIDGT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldDisplayID, v))
}

// DisplayIDGTE applies the GTE predicate on the "display_id" field.
func DisplayIDGTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldDisplayID, v))
}

// DisplayIDLT applies the LT predicate on the "display_id" field.
func DisplayIDLT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldDisplayID, v))
}

// DisplayIDLTE applies the LTE predicate on the "display_id" field.
func DisplayIDLTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldDisplayID, v))
}

// DisplayIDContains applies the Contains predicate on the "display_id" field.
func DisplayIDContains(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContains(FieldDisplayID, v))
}

// DisplayIDHasPrefix applies the HasPrefix predicate on the "display_id" field.
func DisplayIDHasPrefix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasPrefix(FieldDisplayID, v))
}

// DisplayIDHasSuffix applies the HasSuffix predicate on the "display_id" field.
func DisplayIDHasSuffix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasSuffix(FieldDisplayID, v))
}

// DisplayIDEqualFold applies the EqualFold predicate on the "display_id" field.
func DisplayIDEqualFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEqualFold(FieldDisplayID, v))
}

// DisplayIDContainsFold applies the ContainsFold predicate on the "display_id" field.
func DisplayIDContainsFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContainsFold(FieldDisplayID, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldTags))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldOwnerID, v))
}

// OwnerIDContains applies the Contains predicate on the "owner_id" field.
func OwnerIDContains(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContains(FieldOwnerID, v))
}

// OwnerIDHasPrefix applies the HasPrefix predicate on the "owner_id" field.
func OwnerIDHasPrefix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasPrefix(FieldOwnerID, v))
}

// OwnerIDHasSuffix applies the HasSuffix predicate on the "owner_id" field.
func OwnerIDHasSuffix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasSuffix(FieldOwnerID, v))
}

// OwnerIDIsNil applies the IsNil predicate on the "owner_id" field.
func OwnerIDIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldOwnerID))
}

// OwnerIDNotNil applies the NotNil predicate on the "owner_id" field.
func OwnerIDNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldOwnerID))
}

// OwnerIDEqualFold applies the EqualFold predicate on the "owner_id" field.
func OwnerIDEqualFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEqualFold(FieldOwnerID, v))
}

// OwnerIDContainsFold applies the ContainsFold predicate on the "owner_id" field.
func OwnerIDContainsFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContainsFold(FieldOwnerID, v))
}

// WorkflowDefinitionIDEQ applies the EQ predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDNEQ applies the NEQ predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDNEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDIn applies the In predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldWorkflowDefinitionID, vs...))
}

// WorkflowDefinitionIDNotIn applies the NotIn predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDNotIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldWorkflowDefinitionID, vs...))
}

// WorkflowDefinitionIDGT applies the GT predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDGT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDGTE applies the GTE predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDGTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDLT applies the LT predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDLT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDLTE applies the LTE predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDLTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDContains applies the Contains predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDContains(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContains(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDHasPrefix applies the HasPrefix predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDHasPrefix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasPrefix(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDHasSuffix applies the HasSuffix predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDHasSuffix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasSuffix(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDEqualFold applies the EqualFold predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDEqualFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEqualFold(FieldWorkflowDefinitionID, v))
}

// WorkflowDefinitionIDContainsFold applies the ContainsFold predicate on the "workflow_definition_id" field.
func WorkflowDefinitionIDContainsFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContainsFold(FieldWorkflowDefinitionID, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v enums.WorkflowInstanceState) predicate.WorkflowInstanceHistory {
	vc := v
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldState, vc))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v enums.WorkflowInstanceState) predicate.WorkflowInstanceHistory {
	vc := v
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldState, vc))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...enums.WorkflowInstanceState) predicate.WorkflowInstanceHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldState, v...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...enums.WorkflowInstanceState) predicate.WorkflowInstanceHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldState, v...))
}

// ContextIsNil applies the IsNil predicate on the "context" field.
func ContextIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldContext))
}

// ContextNotNil applies the NotNil predicate on the "context" field.
func ContextNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldContext))
}

// LastEvaluatedAtEQ applies the EQ predicate on the "last_evaluated_at" field.
func LastEvaluatedAtEQ(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtNEQ applies the NEQ predicate on the "last_evaluated_at" field.
func LastEvaluatedAtNEQ(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtIn applies the In predicate on the "last_evaluated_at" field.
func LastEvaluatedAtIn(vs ...time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldLastEvaluatedAt, vs...))
}

// LastEvaluatedAtNotIn applies the NotIn predicate on the "last_evaluated_at" field.
func LastEvaluatedAtNotIn(vs ...time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldLastEvaluatedAt, vs...))
}

// LastEvaluatedAtGT applies the GT predicate on the "last_evaluated_at" field.
func LastEvaluatedAtGT(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtGTE applies the GTE predicate on the "last_evaluated_at" field.
func LastEvaluatedAtGTE(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtLT applies the LT predicate on the "last_evaluated_at" field.
func LastEvaluatedAtLT(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtLTE applies the LTE predicate on the "last_evaluated_at" field.
func LastEvaluatedAtLTE(v time.Time) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtIsNil applies the IsNil predicate on the "last_evaluated_at" field.
func LastEvaluatedAtIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldLastEvaluatedAt))
}

// LastEvaluatedAtNotNil applies the NotNil predicate on the "last_evaluated_at" field.
func LastEvaluatedAtNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldLastEvaluatedAt))
}

// DefinitionSnapshotIsNil applies the IsNil predicate on the "definition_snapshot" field.
func DefinitionSnapshotIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldDefinitionSnapshot))
}

// DefinitionSnapshotNotNil applies the NotNil predicate on the "definition_snapshot" field.
func DefinitionSnapshotNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldDefinitionSnapshot))
}

// ControlIDEQ applies the EQ predicate on the "control_id" field.
func ControlIDEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldControlID, v))
}

// ControlIDNEQ applies the NEQ predicate on the "control_id" field.
func ControlIDNEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldControlID, v))
}

// ControlIDIn applies the In predicate on the "control_id" field.
func ControlIDIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldControlID, vs...))
}

// ControlIDNotIn applies the NotIn predicate on the "control_id" field.
func ControlIDNotIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldControlID, vs...))
}

// ControlIDGT applies the GT predicate on the "control_id" field.
func ControlIDGT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldControlID, v))
}

// ControlIDGTE applies the GTE predicate on the "control_id" field.
func ControlIDGTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldControlID, v))
}

// ControlIDLT applies the LT predicate on the "control_id" field.
func ControlIDLT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldControlID, v))
}

// ControlIDLTE applies the LTE predicate on the "control_id" field.
func ControlIDLTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldControlID, v))
}

// ControlIDContains applies the Contains predicate on the "control_id" field.
func ControlIDContains(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContains(FieldControlID, v))
}

// ControlIDHasPrefix applies the HasPrefix predicate on the "control_id" field.
func ControlIDHasPrefix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasPrefix(FieldControlID, v))
}

// ControlIDHasSuffix applies the HasSuffix predicate on the "control_id" field.
func ControlIDHasSuffix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasSuffix(FieldControlID, v))
}

// ControlIDIsNil applies the IsNil predicate on the "control_id" field.
func ControlIDIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldControlID))
}

// ControlIDNotNil applies the NotNil predicate on the "control_id" field.
func ControlIDNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldControlID))
}

// ControlIDEqualFold applies the EqualFold predicate on the "control_id" field.
func ControlIDEqualFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEqualFold(FieldControlID, v))
}

// ControlIDContainsFold applies the ContainsFold predicate on the "control_id" field.
func ControlIDContainsFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContainsFold(FieldControlID, v))
}

// InternalPolicyIDEQ applies the EQ predicate on the "internal_policy_id" field.
func InternalPolicyIDEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldInternalPolicyID, v))
}

// InternalPolicyIDNEQ applies the NEQ predicate on the "internal_policy_id" field.
func InternalPolicyIDNEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldInternalPolicyID, v))
}

// InternalPolicyIDIn applies the In predicate on the "internal_policy_id" field.
func InternalPolicyIDIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldInternalPolicyID, vs...))
}

// InternalPolicyIDNotIn applies the NotIn predicate on the "internal_policy_id" field.
func InternalPolicyIDNotIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldInternalPolicyID, vs...))
}

// InternalPolicyIDGT applies the GT predicate on the "internal_policy_id" field.
func InternalPolicyIDGT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldInternalPolicyID, v))
}

// InternalPolicyIDGTE applies the GTE predicate on the "internal_policy_id" field.
func InternalPolicyIDGTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldInternalPolicyID, v))
}

// InternalPolicyIDLT applies the LT predicate on the "internal_policy_id" field.
func InternalPolicyIDLT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldInternalPolicyID, v))
}

// InternalPolicyIDLTE applies the LTE predicate on the "internal_policy_id" field.
func InternalPolicyIDLTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldInternalPolicyID, v))
}

// InternalPolicyIDContains applies the Contains predicate on the "internal_policy_id" field.
func InternalPolicyIDContains(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContains(FieldInternalPolicyID, v))
}

// InternalPolicyIDHasPrefix applies the HasPrefix predicate on the "internal_policy_id" field.
func InternalPolicyIDHasPrefix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasPrefix(FieldInternalPolicyID, v))
}

// InternalPolicyIDHasSuffix applies the HasSuffix predicate on the "internal_policy_id" field.
func InternalPolicyIDHasSuffix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasSuffix(FieldInternalPolicyID, v))
}

// InternalPolicyIDIsNil applies the IsNil predicate on the "internal_policy_id" field.
func InternalPolicyIDIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldInternalPolicyID))
}

// InternalPolicyIDNotNil applies the NotNil predicate on the "internal_policy_id" field.
func InternalPolicyIDNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldInternalPolicyID))
}

// InternalPolicyIDEqualFold applies the EqualFold predicate on the "internal_policy_id" field.
func InternalPolicyIDEqualFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEqualFold(FieldInternalPolicyID, v))
}

// InternalPolicyIDContainsFold applies the ContainsFold predicate on the "internal_policy_id" field.
func InternalPolicyIDContainsFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContainsFold(FieldInternalPolicyID, v))
}

// EvidenceIDEQ applies the EQ predicate on the "evidence_id" field.
func EvidenceIDEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEQ(FieldEvidenceID, v))
}

// EvidenceIDNEQ applies the NEQ predicate on the "evidence_id" field.
func EvidenceIDNEQ(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNEQ(FieldEvidenceID, v))
}

// EvidenceIDIn applies the In predicate on the "evidence_id" field.
func EvidenceIDIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIn(FieldEvidenceID, vs...))
}

// EvidenceIDNotIn applies the NotIn predicate on the "evidence_id" field.
func EvidenceIDNotIn(vs ...string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotIn(FieldEvidenceID, vs...))
}

// EvidenceIDGT applies the GT predicate on the "evidence_id" field.
func EvidenceIDGT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGT(FieldEvidenceID, v))
}

// EvidenceIDGTE applies the GTE predicate on the "evidence_id" field.
func EvidenceIDGTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldGTE(FieldEvidenceID, v))
}

// EvidenceIDLT applies the LT predicate on the "evidence_id" field.
func EvidenceIDLT(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLT(FieldEvidenceID, v))
}

// EvidenceIDLTE applies the LTE predicate on the "evidence_id" field.
func EvidenceIDLTE(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldLTE(FieldEvidenceID, v))
}

// EvidenceIDContains applies the Contains predicate on the "evidence_id" field.
func EvidenceIDContains(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContains(FieldEvidenceID, v))
}

// EvidenceIDHasPrefix applies the HasPrefix predicate on the "evidence_id" field.
func EvidenceIDHasPrefix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasPrefix(FieldEvidenceID, v))
}

// EvidenceIDHasSuffix applies the HasSuffix predicate on the "evidence_id" field.
func EvidenceIDHasSuffix(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldHasSuffix(FieldEvidenceID, v))
}

// EvidenceIDIsNil applies the IsNil predicate on the "evidence_id" field.
func EvidenceIDIsNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldIsNull(FieldEvidenceID))
}

// EvidenceIDNotNil applies the NotNil predicate on the "evidence_id" field.
func EvidenceIDNotNil() predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldNotNull(FieldEvidenceID))
}

// EvidenceIDEqualFold applies the EqualFold predicate on the "evidence_id" field.
func EvidenceIDEqualFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldEqualFold(FieldEvidenceID, v))
}

// EvidenceIDContainsFold applies the ContainsFold predicate on the "evidence_id" field.
func EvidenceIDContainsFold(v string) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.FieldContainsFold(FieldEvidenceID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkflowInstanceHistory) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkflowInstanceHistory) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkflowInstanceHistory) predicate.WorkflowInstanceHistory {
	return predicate.WorkflowInstanceHistory(sql.NotPredicates(p))
}
