// Code generated by entx.history, DO NOT EDIT.
package historyschema

import (
	"time"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	entschema "entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"

	"github.com/theopenlane/core/internal/ent/interceptors"
	"github.com/theopenlane/core/internal/ent/privacy/policy"
	"github.com/theopenlane/core/internal/ent/schema"
	"github.com/theopenlane/entx"
	"github.com/theopenlane/entx/history"
	"github.com/theopenlane/iam/entfga"
)

// GroupMembershipHistory holds the schema definition for the GroupMembershipHistory entity.
type GroupMembershipHistory struct {
	ent.Schema
}

// Annotations of the GroupMembershipHistory.
func (GroupMembershipHistory) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entx.SchemaGenSkip(true),
		entsql.Annotation{
			Table: "group_membership_history",
		},
		history.Annotations{
			IsHistory: true,
			Exclude:   true,
		},
		entgql.QueryField(),
		entgql.RelayConnection(),
		entfga.Annotations{
			ObjectType:   "group",
			IDField:      "GroupID",
			IncludeHooks: false,
		},
	}
}

// Fields of the GroupMembershipHistory.
func (GroupMembershipHistory) Fields() []ent.Field {
	historyFields := []ent.Field{
		field.Time("history_time").
			Annotations(
				entgql.OrderField("history_time"),
			).
			Default(time.Now).
			Immutable(),
		field.String("ref").
			Immutable().
			Optional(),
		field.Enum("operation").
			GoType(history.OpType("")).
			Immutable(),
	}

	// get the fields from the mixins
	// we only want to include mixin fields, not edges
	// so this prevents FKs back to the main tables
	mixins := schema.GroupMembership{}.Mixin()
	for _, mixin := range mixins {
		for _, field := range mixin.Fields() {
			// make sure the mixed in fields do not have unique constraints
			field.Descriptor().Unique = false

			// make sure the mixed in fields do not have validators
			field.Descriptor().Validators = nil

			// append the mixed in field to the history fields
			historyFields = append(historyFields, field)
		}
	}

	original := schema.GroupMembership{}
	for _, field := range original.Fields() {
		// make sure the fields do not have unique constraints
		field.Descriptor().Unique = false

		// make sure the mixed in fields do not have validators
		field.Descriptor().Validators = nil

		// append the field to the history fields
		historyFields = append(historyFields, field)
	}

	return historyFields
}

// Indexes of the GroupMembershipHistory
func (GroupMembershipHistory) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("history_time"),
	}
}

// Policy of the GroupMembershipHistory.
// ensure history.AllowIfHistoryRequest() is already added to the base policy
func (GroupMembershipHistory) Policy() ent.Policy {
	return policy.NewPolicy(
		policy.WithMutationRules(
			history.AllowIfHistoryRequest(),
		),
	)
}

// Interceptors of the GroupMembershipHistory
func (GroupMembershipHistory) Interceptors() []ent.Interceptor {
	return []ent.Interceptor{
		interceptors.HistoryAccess("audit_log_viewer", false, false, "group"),
	}
}
