model:
  package: testclient
  filename: internal/graphapi/testclient/models.go
client:
  package: testclient
  filename: internal/graphapi/testclient/graphclient.go
models:
  Int:
    model: github.com/99designs/gqlgen/graphql.Int64
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.String
  JSON:
    model:
      - github.com/theopenlane/entx.RawMessage
  Address:
    model:
      - github.com/theopenlane/common/models.Address
  Price:
    model:
      - github.com/theopenlane/common/models.Price
  AssessmentObjective:
    model:
      - github.com/theopenlane/common/models.AssessmentObjective
  AssessmentMethod:
    model:
      - github.com/theopenlane/common/models.AssessmentMethod
  Reference:
    model:
      - github.com/theopenlane/common/models.Reference
  ImplementationGuidance:
    model:
      - github.com/theopenlane/common/models.ImplementationGuidance
  ExampleEvidence:
    model:
      - github.com/theopenlane/common/models.ExampleEvidence
  TestingProcedures:
    model:
      - github.com/theopenlane/common/models.TestingProcedures
  EvidenceRequests:
    model:
      - github.com/theopenlane/common/models.EvidenceRequests
  VersionBump:
    model:
      - github.com/theopenlane/common/models.VersionBump
  DateTime:
    model: github.com/theopenlane/common/models.DateTime
  AAGUID:
    model: github.com/theopenlane/common/models.AAGUID
  JobConfiguration:
    model: github.com/theopenlane/common/models.JobConfiguration
  JobCadence:
    model: github.com/theopenlane/common/models.JobCadence
  Change:
    model: github.com/theopenlane/common/models.Change
  AuditLogOrderField:
    model: github.com/theopenlane/common/models.AuditLogOrderField
  CredentialSet:
    model:
      - github.com/theopenlane/common/models.CredentialSet
  WorkflowDefinitionDocument:
    model:
      - github.com/theopenlane/common/models.WorkflowDefinitionDocument
  WorkflowDefinitionSchema:
    model:
      - github.com/theopenlane/common/models.WorkflowDefinitionSchema
  WorkflowInstanceContext:
    model:
      - github.com/theopenlane/common/models.WorkflowInstanceContext
  WorkflowEventPayload:
    model:
      - github.com/theopenlane/common/models.WorkflowEventPayload
  Map:
    model:
      - github.com/99designs/gqlgen/graphql.Map
  Any:
    model:
      - github.com/99designs/gqlgen/graphql.Any
schema: ["internal/graphapi/clientschema/schema.graphql"]
query: ["internal/graphapi/query/*.graphql"]
generate:
  clientV2: true
  clientInterfaceName: "TestGraphClient"
  query: false
  mutation: false
