model:
  package: openlaneclient
  filename: pkg/openlaneclient/models.go
client:
  package: openlaneclient
  filename: pkg/openlaneclient/graphclient.go
models:
  Int:
    model: github.com/99designs/gqlgen/graphql.Int64
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.String
  JSON:
    model:
      - github.com/theopenlane/entx.RawMessage
      - github.com/theopenlane/core/internal/ent/customtypes.JSONObject
  Address:
    model:
      - github.com/theopenlane/core/pkg/models.Address
  Price:
    model:
      - github.com/theopenlane/core/pkg/models.Price
  AssessmentObjective:
    model:
      - github.com/theopenlane/core/pkg/models.AssessmentObjective
  AssessmentMethod:
    model:
      - github.com/theopenlane/core/pkg/models.AssessmentMethod
  Reference:
    model:
      - github.com/theopenlane/core/pkg/models.Reference
  ImplementationGuidance:
    model:
      - github.com/theopenlane/core/pkg/models.ImplementationGuidance
  ExampleEvidence:
    model:
      - github.com/theopenlane/core/pkg/models.ExampleEvidence
  VersionBump:
    model:
      - github.com/theopenlane/core/pkg/models.VersionBump
schema: ["internal/graphapi/clientschema/schema.graphql"]
query: ["internal/graphapi/query/*.graphql"]
generate:
  clientV2: true
  clientInterfaceName: "OpenlaneGraphClient"
  query: false
  mutation: false
