model:
  package: openlaneclient
  filename: pkg/openlaneclient/models.go
client:
  package: openlaneclient
  filename: pkg/openlaneclient/graphclient.go
models:
  Int:
    model: github.com/99designs/gqlgen/graphql.Int64
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.String
  JSON:
    model:
      - github.com/theopenlane/entx.RawMessage
      - github.com/theopenlane/core/internal/ent/customtypes.JSONObject
schema: ["internal/graphapi/clientschema/schema.graphql"]
query: ["internal/graphapi/query/*.graphql"]
generate:
  clientV2: true
  clientInterfaceName: "OpenlaneGraphClient"
  query: false
  mutation: false
