//go:build !enthistorycodegen

// Code generated by ent, DO NOT EDIT.

package vendorriskscorehistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/theopenlane/core/common/enums"
	"github.com/theopenlane/core/internal/ent/historygenerated/predicate"
	"github.com/theopenlane/entx/history"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldID, id))
}

// HistoryTime applies equality check predicate on the "history_time" field. It's identical to HistoryTimeEQ.
func HistoryTime(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldHistoryTime, v))
}

// Ref applies equality check predicate on the "ref" field. It's identical to RefEQ.
func Ref(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldRef, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldDeletedBy, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldOwnerID, v))
}

// QuestionKey applies equality check predicate on the "question_key" field. It's identical to QuestionKeyEQ.
func QuestionKey(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldQuestionKey, v))
}

// QuestionName applies equality check predicate on the "question_name" field. It's identical to QuestionNameEQ.
func QuestionName(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldQuestionName, v))
}

// QuestionDescription applies equality check predicate on the "question_description" field. It's identical to QuestionDescriptionEQ.
func QuestionDescription(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldQuestionDescription, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v float64) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldScore, v))
}

// Answer applies equality check predicate on the "answer" field. It's identical to AnswerEQ.
func Answer(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldAnswer, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldNotes, v))
}

// VendorScoringConfigID applies equality check predicate on the "vendor_scoring_config_id" field. It's identical to VendorScoringConfigIDEQ.
func VendorScoringConfigID(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldVendorScoringConfigID, v))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldEntityID, v))
}

// AssessmentResponseID applies equality check predicate on the "assessment_response_id" field. It's identical to AssessmentResponseIDEQ.
func AssessmentResponseID(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldAssessmentResponseID, v))
}

// HistoryTimeEQ applies the EQ predicate on the "history_time" field.
func HistoryTimeEQ(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldHistoryTime, v))
}

// HistoryTimeNEQ applies the NEQ predicate on the "history_time" field.
func HistoryTimeNEQ(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldHistoryTime, v))
}

// HistoryTimeIn applies the In predicate on the "history_time" field.
func HistoryTimeIn(vs ...time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldHistoryTime, vs...))
}

// HistoryTimeNotIn applies the NotIn predicate on the "history_time" field.
func HistoryTimeNotIn(vs ...time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldHistoryTime, vs...))
}

// HistoryTimeGT applies the GT predicate on the "history_time" field.
func HistoryTimeGT(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldHistoryTime, v))
}

// HistoryTimeGTE applies the GTE predicate on the "history_time" field.
func HistoryTimeGTE(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldHistoryTime, v))
}

// HistoryTimeLT applies the LT predicate on the "history_time" field.
func HistoryTimeLT(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldHistoryTime, v))
}

// HistoryTimeLTE applies the LTE predicate on the "history_time" field.
func HistoryTimeLTE(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldHistoryTime, v))
}

// RefEQ applies the EQ predicate on the "ref" field.
func RefEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldRef, v))
}

// RefNEQ applies the NEQ predicate on the "ref" field.
func RefNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldRef, v))
}

// RefIn applies the In predicate on the "ref" field.
func RefIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldRef, vs...))
}

// RefNotIn applies the NotIn predicate on the "ref" field.
func RefNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldRef, vs...))
}

// RefGT applies the GT predicate on the "ref" field.
func RefGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldRef, v))
}

// RefGTE applies the GTE predicate on the "ref" field.
func RefGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldRef, v))
}

// RefLT applies the LT predicate on the "ref" field.
func RefLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldRef, v))
}

// RefLTE applies the LTE predicate on the "ref" field.
func RefLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldRef, v))
}

// RefContains applies the Contains predicate on the "ref" field.
func RefContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldRef, v))
}

// RefHasPrefix applies the HasPrefix predicate on the "ref" field.
func RefHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldRef, v))
}

// RefHasSuffix applies the HasSuffix predicate on the "ref" field.
func RefHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldRef, v))
}

// RefIsNil applies the IsNil predicate on the "ref" field.
func RefIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldRef))
}

// RefNotNil applies the NotNil predicate on the "ref" field.
func RefNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldRef))
}

// RefEqualFold applies the EqualFold predicate on the "ref" field.
func RefEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldRef, v))
}

// RefContainsFold applies the ContainsFold predicate on the "ref" field.
func RefContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldRef, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v history.OpType) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v history.OpType) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...history.OpType) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...history.OpType) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldOperation, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldUpdatedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldDeletedAt))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByContains applies the Contains predicate on the "deleted_by" field.
func DeletedByContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldDeletedBy, v))
}

// DeletedByHasPrefix applies the HasPrefix predicate on the "deleted_by" field.
func DeletedByHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldDeletedBy, v))
}

// DeletedByHasSuffix applies the HasSuffix predicate on the "deleted_by" field.
func DeletedByHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldDeletedBy))
}

// DeletedByEqualFold applies the EqualFold predicate on the "deleted_by" field.
func DeletedByEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldDeletedBy, v))
}

// DeletedByContainsFold applies the ContainsFold predicate on the "deleted_by" field.
func DeletedByContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldDeletedBy, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldTags))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldOwnerID, v))
}

// OwnerIDContains applies the Contains predicate on the "owner_id" field.
func OwnerIDContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldOwnerID, v))
}

// OwnerIDHasPrefix applies the HasPrefix predicate on the "owner_id" field.
func OwnerIDHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldOwnerID, v))
}

// OwnerIDHasSuffix applies the HasSuffix predicate on the "owner_id" field.
func OwnerIDHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldOwnerID, v))
}

// OwnerIDIsNil applies the IsNil predicate on the "owner_id" field.
func OwnerIDIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldOwnerID))
}

// OwnerIDNotNil applies the NotNil predicate on the "owner_id" field.
func OwnerIDNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldOwnerID))
}

// OwnerIDEqualFold applies the EqualFold predicate on the "owner_id" field.
func OwnerIDEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldOwnerID, v))
}

// OwnerIDContainsFold applies the ContainsFold predicate on the "owner_id" field.
func OwnerIDContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldOwnerID, v))
}

// QuestionKeyEQ applies the EQ predicate on the "question_key" field.
func QuestionKeyEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldQuestionKey, v))
}

// QuestionKeyNEQ applies the NEQ predicate on the "question_key" field.
func QuestionKeyNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldQuestionKey, v))
}

// QuestionKeyIn applies the In predicate on the "question_key" field.
func QuestionKeyIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldQuestionKey, vs...))
}

// QuestionKeyNotIn applies the NotIn predicate on the "question_key" field.
func QuestionKeyNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldQuestionKey, vs...))
}

// QuestionKeyGT applies the GT predicate on the "question_key" field.
func QuestionKeyGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldQuestionKey, v))
}

// QuestionKeyGTE applies the GTE predicate on the "question_key" field.
func QuestionKeyGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldQuestionKey, v))
}

// QuestionKeyLT applies the LT predicate on the "question_key" field.
func QuestionKeyLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldQuestionKey, v))
}

// QuestionKeyLTE applies the LTE predicate on the "question_key" field.
func QuestionKeyLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldQuestionKey, v))
}

// QuestionKeyContains applies the Contains predicate on the "question_key" field.
func QuestionKeyContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldQuestionKey, v))
}

// QuestionKeyHasPrefix applies the HasPrefix predicate on the "question_key" field.
func QuestionKeyHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldQuestionKey, v))
}

// QuestionKeyHasSuffix applies the HasSuffix predicate on the "question_key" field.
func QuestionKeyHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldQuestionKey, v))
}

// QuestionKeyEqualFold applies the EqualFold predicate on the "question_key" field.
func QuestionKeyEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldQuestionKey, v))
}

// QuestionKeyContainsFold applies the ContainsFold predicate on the "question_key" field.
func QuestionKeyContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldQuestionKey, v))
}

// QuestionNameEQ applies the EQ predicate on the "question_name" field.
func QuestionNameEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldQuestionName, v))
}

// QuestionNameNEQ applies the NEQ predicate on the "question_name" field.
func QuestionNameNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldQuestionName, v))
}

// QuestionNameIn applies the In predicate on the "question_name" field.
func QuestionNameIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldQuestionName, vs...))
}

// QuestionNameNotIn applies the NotIn predicate on the "question_name" field.
func QuestionNameNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldQuestionName, vs...))
}

// QuestionNameGT applies the GT predicate on the "question_name" field.
func QuestionNameGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldQuestionName, v))
}

// QuestionNameGTE applies the GTE predicate on the "question_name" field.
func QuestionNameGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldQuestionName, v))
}

// QuestionNameLT applies the LT predicate on the "question_name" field.
func QuestionNameLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldQuestionName, v))
}

// QuestionNameLTE applies the LTE predicate on the "question_name" field.
func QuestionNameLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldQuestionName, v))
}

// QuestionNameContains applies the Contains predicate on the "question_name" field.
func QuestionNameContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldQuestionName, v))
}

// QuestionNameHasPrefix applies the HasPrefix predicate on the "question_name" field.
func QuestionNameHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldQuestionName, v))
}

// QuestionNameHasSuffix applies the HasSuffix predicate on the "question_name" field.
func QuestionNameHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldQuestionName, v))
}

// QuestionNameEqualFold applies the EqualFold predicate on the "question_name" field.
func QuestionNameEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldQuestionName, v))
}

// QuestionNameContainsFold applies the ContainsFold predicate on the "question_name" field.
func QuestionNameContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldQuestionName, v))
}

// QuestionDescriptionEQ applies the EQ predicate on the "question_description" field.
func QuestionDescriptionEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldQuestionDescription, v))
}

// QuestionDescriptionNEQ applies the NEQ predicate on the "question_description" field.
func QuestionDescriptionNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldQuestionDescription, v))
}

// QuestionDescriptionIn applies the In predicate on the "question_description" field.
func QuestionDescriptionIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldQuestionDescription, vs...))
}

// QuestionDescriptionNotIn applies the NotIn predicate on the "question_description" field.
func QuestionDescriptionNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldQuestionDescription, vs...))
}

// QuestionDescriptionGT applies the GT predicate on the "question_description" field.
func QuestionDescriptionGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldQuestionDescription, v))
}

// QuestionDescriptionGTE applies the GTE predicate on the "question_description" field.
func QuestionDescriptionGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldQuestionDescription, v))
}

// QuestionDescriptionLT applies the LT predicate on the "question_description" field.
func QuestionDescriptionLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldQuestionDescription, v))
}

// QuestionDescriptionLTE applies the LTE predicate on the "question_description" field.
func QuestionDescriptionLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldQuestionDescription, v))
}

// QuestionDescriptionContains applies the Contains predicate on the "question_description" field.
func QuestionDescriptionContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldQuestionDescription, v))
}

// QuestionDescriptionHasPrefix applies the HasPrefix predicate on the "question_description" field.
func QuestionDescriptionHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldQuestionDescription, v))
}

// QuestionDescriptionHasSuffix applies the HasSuffix predicate on the "question_description" field.
func QuestionDescriptionHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldQuestionDescription, v))
}

// QuestionDescriptionIsNil applies the IsNil predicate on the "question_description" field.
func QuestionDescriptionIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldQuestionDescription))
}

// QuestionDescriptionNotNil applies the NotNil predicate on the "question_description" field.
func QuestionDescriptionNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldQuestionDescription))
}

// QuestionDescriptionEqualFold applies the EqualFold predicate on the "question_description" field.
func QuestionDescriptionEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldQuestionDescription, v))
}

// QuestionDescriptionContainsFold applies the ContainsFold predicate on the "question_description" field.
func QuestionDescriptionContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldQuestionDescription, v))
}

// QuestionCategoryEQ applies the EQ predicate on the "question_category" field.
func QuestionCategoryEQ(v enums.VendorScoringCategory) predicate.VendorRiskScoreHistory {
	vc := v
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldQuestionCategory, vc))
}

// QuestionCategoryNEQ applies the NEQ predicate on the "question_category" field.
func QuestionCategoryNEQ(v enums.VendorScoringCategory) predicate.VendorRiskScoreHistory {
	vc := v
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldQuestionCategory, vc))
}

// QuestionCategoryIn applies the In predicate on the "question_category" field.
func QuestionCategoryIn(vs ...enums.VendorScoringCategory) predicate.VendorRiskScoreHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldQuestionCategory, v...))
}

// QuestionCategoryNotIn applies the NotIn predicate on the "question_category" field.
func QuestionCategoryNotIn(vs ...enums.VendorScoringCategory) predicate.VendorRiskScoreHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldQuestionCategory, v...))
}

// AnswerTypeEQ applies the EQ predicate on the "answer_type" field.
func AnswerTypeEQ(v enums.VendorScoringAnswerType) predicate.VendorRiskScoreHistory {
	vc := v
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldAnswerType, vc))
}

// AnswerTypeNEQ applies the NEQ predicate on the "answer_type" field.
func AnswerTypeNEQ(v enums.VendorScoringAnswerType) predicate.VendorRiskScoreHistory {
	vc := v
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldAnswerType, vc))
}

// AnswerTypeIn applies the In predicate on the "answer_type" field.
func AnswerTypeIn(vs ...enums.VendorScoringAnswerType) predicate.VendorRiskScoreHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldAnswerType, v...))
}

// AnswerTypeNotIn applies the NotIn predicate on the "answer_type" field.
func AnswerTypeNotIn(vs ...enums.VendorScoringAnswerType) predicate.VendorRiskScoreHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldAnswerType, v...))
}

// ImpactEQ applies the EQ predicate on the "impact" field.
func ImpactEQ(v enums.VendorRiskImpact) predicate.VendorRiskScoreHistory {
	vc := v
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldImpact, vc))
}

// ImpactNEQ applies the NEQ predicate on the "impact" field.
func ImpactNEQ(v enums.VendorRiskImpact) predicate.VendorRiskScoreHistory {
	vc := v
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldImpact, vc))
}

// ImpactIn applies the In predicate on the "impact" field.
func ImpactIn(vs ...enums.VendorRiskImpact) predicate.VendorRiskScoreHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldImpact, v...))
}

// ImpactNotIn applies the NotIn predicate on the "impact" field.
func ImpactNotIn(vs ...enums.VendorRiskImpact) predicate.VendorRiskScoreHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldImpact, v...))
}

// LikelihoodEQ applies the EQ predicate on the "likelihood" field.
func LikelihoodEQ(v enums.VendorRiskLikelihood) predicate.VendorRiskScoreHistory {
	vc := v
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldLikelihood, vc))
}

// LikelihoodNEQ applies the NEQ predicate on the "likelihood" field.
func LikelihoodNEQ(v enums.VendorRiskLikelihood) predicate.VendorRiskScoreHistory {
	vc := v
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldLikelihood, vc))
}

// LikelihoodIn applies the In predicate on the "likelihood" field.
func LikelihoodIn(vs ...enums.VendorRiskLikelihood) predicate.VendorRiskScoreHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldLikelihood, v...))
}

// LikelihoodNotIn applies the NotIn predicate on the "likelihood" field.
func LikelihoodNotIn(vs ...enums.VendorRiskLikelihood) predicate.VendorRiskScoreHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldLikelihood, v...))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v float64) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v float64) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...float64) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...float64) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v float64) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v float64) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v float64) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v float64) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldScore, v))
}

// AnswerEQ applies the EQ predicate on the "answer" field.
func AnswerEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldAnswer, v))
}

// AnswerNEQ applies the NEQ predicate on the "answer" field.
func AnswerNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldAnswer, v))
}

// AnswerIn applies the In predicate on the "answer" field.
func AnswerIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldAnswer, vs...))
}

// AnswerNotIn applies the NotIn predicate on the "answer" field.
func AnswerNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldAnswer, vs...))
}

// AnswerGT applies the GT predicate on the "answer" field.
func AnswerGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldAnswer, v))
}

// AnswerGTE applies the GTE predicate on the "answer" field.
func AnswerGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldAnswer, v))
}

// AnswerLT applies the LT predicate on the "answer" field.
func AnswerLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldAnswer, v))
}

// AnswerLTE applies the LTE predicate on the "answer" field.
func AnswerLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldAnswer, v))
}

// AnswerContains applies the Contains predicate on the "answer" field.
func AnswerContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldAnswer, v))
}

// AnswerHasPrefix applies the HasPrefix predicate on the "answer" field.
func AnswerHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldAnswer, v))
}

// AnswerHasSuffix applies the HasSuffix predicate on the "answer" field.
func AnswerHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldAnswer, v))
}

// AnswerIsNil applies the IsNil predicate on the "answer" field.
func AnswerIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldAnswer))
}

// AnswerNotNil applies the NotNil predicate on the "answer" field.
func AnswerNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldAnswer))
}

// AnswerEqualFold applies the EqualFold predicate on the "answer" field.
func AnswerEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldAnswer, v))
}

// AnswerContainsFold applies the ContainsFold predicate on the "answer" field.
func AnswerContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldAnswer, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldNotes, v))
}

// VendorScoringConfigIDEQ applies the EQ predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldVendorScoringConfigID, v))
}

// VendorScoringConfigIDNEQ applies the NEQ predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldVendorScoringConfigID, v))
}

// VendorScoringConfigIDIn applies the In predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldVendorScoringConfigID, vs...))
}

// VendorScoringConfigIDNotIn applies the NotIn predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldVendorScoringConfigID, vs...))
}

// VendorScoringConfigIDGT applies the GT predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldVendorScoringConfigID, v))
}

// VendorScoringConfigIDGTE applies the GTE predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldVendorScoringConfigID, v))
}

// VendorScoringConfigIDLT applies the LT predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldVendorScoringConfigID, v))
}

// VendorScoringConfigIDLTE applies the LTE predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldVendorScoringConfigID, v))
}

// VendorScoringConfigIDContains applies the Contains predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldVendorScoringConfigID, v))
}

// VendorScoringConfigIDHasPrefix applies the HasPrefix predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldVendorScoringConfigID, v))
}

// VendorScoringConfigIDHasSuffix applies the HasSuffix predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldVendorScoringConfigID, v))
}

// VendorScoringConfigIDIsNil applies the IsNil predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldVendorScoringConfigID))
}

// VendorScoringConfigIDNotNil applies the NotNil predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldVendorScoringConfigID))
}

// VendorScoringConfigIDEqualFold applies the EqualFold predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldVendorScoringConfigID, v))
}

// VendorScoringConfigIDContainsFold applies the ContainsFold predicate on the "vendor_scoring_config_id" field.
func VendorScoringConfigIDContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldVendorScoringConfigID, v))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldEntityID, vs...))
}

// EntityIDGT applies the GT predicate on the "entity_id" field.
func EntityIDGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldEntityID, v))
}

// EntityIDGTE applies the GTE predicate on the "entity_id" field.
func EntityIDGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldEntityID, v))
}

// EntityIDLT applies the LT predicate on the "entity_id" field.
func EntityIDLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldEntityID, v))
}

// EntityIDLTE applies the LTE predicate on the "entity_id" field.
func EntityIDLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldEntityID, v))
}

// EntityIDContains applies the Contains predicate on the "entity_id" field.
func EntityIDContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldEntityID, v))
}

// EntityIDHasPrefix applies the HasPrefix predicate on the "entity_id" field.
func EntityIDHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldEntityID, v))
}

// EntityIDHasSuffix applies the HasSuffix predicate on the "entity_id" field.
func EntityIDHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldEntityID, v))
}

// EntityIDEqualFold applies the EqualFold predicate on the "entity_id" field.
func EntityIDEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldEntityID, v))
}

// EntityIDContainsFold applies the ContainsFold predicate on the "entity_id" field.
func EntityIDContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldEntityID, v))
}

// AssessmentResponseIDEQ applies the EQ predicate on the "assessment_response_id" field.
func AssessmentResponseIDEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEQ(FieldAssessmentResponseID, v))
}

// AssessmentResponseIDNEQ applies the NEQ predicate on the "assessment_response_id" field.
func AssessmentResponseIDNEQ(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNEQ(FieldAssessmentResponseID, v))
}

// AssessmentResponseIDIn applies the In predicate on the "assessment_response_id" field.
func AssessmentResponseIDIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIn(FieldAssessmentResponseID, vs...))
}

// AssessmentResponseIDNotIn applies the NotIn predicate on the "assessment_response_id" field.
func AssessmentResponseIDNotIn(vs ...string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotIn(FieldAssessmentResponseID, vs...))
}

// AssessmentResponseIDGT applies the GT predicate on the "assessment_response_id" field.
func AssessmentResponseIDGT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGT(FieldAssessmentResponseID, v))
}

// AssessmentResponseIDGTE applies the GTE predicate on the "assessment_response_id" field.
func AssessmentResponseIDGTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldGTE(FieldAssessmentResponseID, v))
}

// AssessmentResponseIDLT applies the LT predicate on the "assessment_response_id" field.
func AssessmentResponseIDLT(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLT(FieldAssessmentResponseID, v))
}

// AssessmentResponseIDLTE applies the LTE predicate on the "assessment_response_id" field.
func AssessmentResponseIDLTE(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldLTE(FieldAssessmentResponseID, v))
}

// AssessmentResponseIDContains applies the Contains predicate on the "assessment_response_id" field.
func AssessmentResponseIDContains(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContains(FieldAssessmentResponseID, v))
}

// AssessmentResponseIDHasPrefix applies the HasPrefix predicate on the "assessment_response_id" field.
func AssessmentResponseIDHasPrefix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasPrefix(FieldAssessmentResponseID, v))
}

// AssessmentResponseIDHasSuffix applies the HasSuffix predicate on the "assessment_response_id" field.
func AssessmentResponseIDHasSuffix(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldHasSuffix(FieldAssessmentResponseID, v))
}

// AssessmentResponseIDIsNil applies the IsNil predicate on the "assessment_response_id" field.
func AssessmentResponseIDIsNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldIsNull(FieldAssessmentResponseID))
}

// AssessmentResponseIDNotNil applies the NotNil predicate on the "assessment_response_id" field.
func AssessmentResponseIDNotNil() predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldNotNull(FieldAssessmentResponseID))
}

// AssessmentResponseIDEqualFold applies the EqualFold predicate on the "assessment_response_id" field.
func AssessmentResponseIDEqualFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldEqualFold(FieldAssessmentResponseID, v))
}

// AssessmentResponseIDContainsFold applies the ContainsFold predicate on the "assessment_response_id" field.
func AssessmentResponseIDContainsFold(v string) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.FieldContainsFold(FieldAssessmentResponseID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VendorRiskScoreHistory) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VendorRiskScoreHistory) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VendorRiskScoreHistory) predicate.VendorRiskScoreHistory {
	return predicate.VendorRiskScoreHistory(sql.NotPredicates(p))
}
