# OAuth Integration Configuration Example
# This file shows the complete configuration for OAuth integrations
# This is SEPARATE from social login configuration

# ================================
# Integration OAuth Provider Config
# ================================
integrationOauthProvider:
  # GitHub Integration Configuration
  github:
    # OAuth App Client ID (from GitHub OAuth App settings)
    clientId: "your_github_client_id"

    # OAuth App Client Secret (from GitHub OAuth App settings)
    clientSecret: "your_github_client_secret"

    # Base URL for OAuth callbacks
    clientEndpoint: "http://localhost:17608"

    # Scopes requested for integration access
    # These are EXTENDED scopes compared to social login
    scopes:
      - "read:user" # Read user profile information
      - "user:email" # Access user email addresses
      - "repo" # Full repository access (read/write)
      # Additional scopes can be added as needed:
      # - "gist"        # Access to gists
      # - "public_repo" # Access to public repositories only
      # - "read:org"    # Read organization membership

  # Slack Integration Configuration
  slack:
    # Slack App Client ID (from Slack App settings)
    clientId: "your_slack_client_id"

    # Slack App Client Secret (from Slack App settings)
    clientSecret: "your_slack_client_secret"

    # Base URL for OAuth callbacks
    clientEndpoint: "http://localhost:17608"

    # Scopes requested for Slack integration access
    scopes:
      - "channels:read" # View channels in workspace
      - "chat:write" # Send messages
      - "users:read" # View people in workspace
      # Additional scopes can be added as needed:
      # - "files:write"   # Upload files
      # - "pins:read"     # View pinned messages
      # - "reactions:read" # View message reactions

# ================================
# Social Login Configuration (SEPARATE)
# ================================
auth:
  providers:
    github:
      # Social login uses different configuration
      clientId: "your_github_social_login_client_id" # Can be same as integration
      clientSecret: "your_github_social_login_client_secret" # Can be same as integration
      clientEndpoint: "http://localhost:17608"
      redirectUrl: "/v1/github/callback" # Different callback URL for social login
      scopes: [] # Usually empty or basic scopes for social login

    google:
      clientId: "your_google_client_id"
      clientSecret: "your_google_client_secret"
      clientEndpoint: "http://localhost:17608"
      redirectUrl: "/v1/google/callback"
      scopes:
        - "openid"
        - "email"
        - "profile"

# ================================
# Environment Variables (Alternative)
# ================================
# Instead of YAML config, you can use environment variables:
#
# Integration OAuth:
# INTEGRATION_OAUTH_GITHUB_CLIENT_ID=your_github_client_id
# INTEGRATION_OAUTH_GITHUB_CLIENT_SECRET=your_github_client_secret
# INTEGRATION_OAUTH_GITHUB_CLIENT_ENDPOINT=http://localhost:17608
# INTEGRATION_OAUTH_SLACK_CLIENT_ID=your_slack_client_id
# INTEGRATION_OAUTH_SLACK_CLIENT_SECRET=your_slack_client_secret
# INTEGRATION_OAUTH_SLACK_CLIENT_ENDPOINT=http://localhost:17608
#
# Social Login OAuth:
# OAUTH_GITHUB_CLIENT_ID=your_github_social_client_id
# OAUTH_GITHUB_CLIENT_SECRET=your_github_social_client_secret
# OAUTH_GOOGLE_CLIENT_ID=your_google_client_id
# OAUTH_GOOGLE_CLIENT_SECRET=your_google_client_secret

# ================================
# OAuth App Requirements
# ================================
#
# GitHub OAuth App Settings:
# - Application Name: "Your App Name - Integrations"
# - Homepage URL: http://localhost:17608
# - Authorization callback URLs:
#   - http://localhost:17608/v1/integrations/oauth/callback  (for integrations)
#   - http://localhost:17608/v1/github/callback              (if sharing with social login)
#
# Slack App Settings:
# - App Name: "Your App Name - Integrations"
# - Redirect URLs:
#   - https://localhost:17608/v1/integrations/oauth/callback
#
# ================================
# Key Differences Summary
# ================================
#
# Integration OAuth vs Social Login:
#
# Configuration:
# - Integration: integrationOauthProvider.github
# - Social Login: auth.providers.github
#
# Callback URLs:
# - Integration: /v1/integrations/oauth/callback
# - Social Login: /v1/github/callback
#
# Scopes:
# - Integration: Extended scopes (repo, gist, etc.)
# - Social Login: Basic scopes (profile, email)
#
# Token Storage:
# - Integration: Organization-scoped in Hush secrets
# - Social Login: Session-based tokens
#
# Use Cases:
# - Integration: Long-term API access for automation
# - Social Login: Short-term authentication for user sessions
