//go:build cli

package main

import (
	core "github.com/theopenlane/core/cmd/cli/cmd"

	// since the cmds are not part of the same package
	// they must all be imported in main
	_ "github.com/theopenlane/core/cmd/cli/cmd/apitokens"
	_ "github.com/theopenlane/core/cmd/cli/cmd/contact"
	_ "github.com/theopenlane/core/cmd/cli/cmd/control"
	_ "github.com/theopenlane/core/cmd/cli/cmd/controlimplementation"
	_ "github.com/theopenlane/core/cmd/cli/cmd/controlobjective"
	_ "github.com/theopenlane/core/cmd/cli/cmd/customdomain"
	_ "github.com/theopenlane/core/cmd/cli/cmd/dnsverification"
	_ "github.com/theopenlane/core/cmd/cli/cmd/documentdata"
	_ "github.com/theopenlane/core/cmd/cli/cmd/entity"
	_ "github.com/theopenlane/core/cmd/cli/cmd/entitytype"
	_ "github.com/theopenlane/core/cmd/cli/cmd/evidence"
	_ "github.com/theopenlane/core/cmd/cli/cmd/file"
	_ "github.com/theopenlane/core/cmd/cli/cmd/group"
	_ "github.com/theopenlane/core/cmd/cli/cmd/groupmembers"
	_ "github.com/theopenlane/core/cmd/cli/cmd/groupsetting"
	_ "github.com/theopenlane/core/cmd/cli/cmd/integration"
	_ "github.com/theopenlane/core/cmd/cli/cmd/internalpolicy"
	_ "github.com/theopenlane/core/cmd/cli/cmd/invite"
	_ "github.com/theopenlane/core/cmd/cli/cmd/jobresult"
	_ "github.com/theopenlane/core/cmd/cli/cmd/jobrunnertoken"
	_ "github.com/theopenlane/core/cmd/cli/cmd/jobtemplate"
	_ "github.com/theopenlane/core/cmd/cli/cmd/login"
	_ "github.com/theopenlane/core/cmd/cli/cmd/mappabledomain"
	_ "github.com/theopenlane/core/cmd/cli/cmd/mappedcontrol"
	_ "github.com/theopenlane/core/cmd/cli/cmd/narrative"
	_ "github.com/theopenlane/core/cmd/cli/cmd/organization"
	_ "github.com/theopenlane/core/cmd/cli/cmd/organizationsetting"
	_ "github.com/theopenlane/core/cmd/cli/cmd/orgmembers"
	_ "github.com/theopenlane/core/cmd/cli/cmd/orgsubscription"
	_ "github.com/theopenlane/core/cmd/cli/cmd/personalaccesstokens"
	_ "github.com/theopenlane/core/cmd/cli/cmd/procedure"
	_ "github.com/theopenlane/core/cmd/cli/cmd/program"
	_ "github.com/theopenlane/core/cmd/cli/cmd/programmembers"
	_ "github.com/theopenlane/core/cmd/cli/cmd/register"
	_ "github.com/theopenlane/core/cmd/cli/cmd/reset"
	_ "github.com/theopenlane/core/cmd/cli/cmd/risk"
	_ "github.com/theopenlane/core/cmd/cli/cmd/scheduledjob"
	_ "github.com/theopenlane/core/cmd/cli/cmd/search"
	_ "github.com/theopenlane/core/cmd/cli/cmd/standard"
	_ "github.com/theopenlane/core/cmd/cli/cmd/subcontrol"
	_ "github.com/theopenlane/core/cmd/cli/cmd/subprocessor"
	_ "github.com/theopenlane/core/cmd/cli/cmd/subscriber"
	_ "github.com/theopenlane/core/cmd/cli/cmd/switchcontext"
	_ "github.com/theopenlane/core/cmd/cli/cmd/task"
	_ "github.com/theopenlane/core/cmd/cli/cmd/template"
	_ "github.com/theopenlane/core/cmd/cli/cmd/trustcenter"
	_ "github.com/theopenlane/core/cmd/cli/cmd/trustcentercompliance"
	_ "github.com/theopenlane/core/cmd/cli/cmd/trustcenterdoc"
	_ "github.com/theopenlane/core/cmd/cli/cmd/trustcenterdomain"
	_ "github.com/theopenlane/core/cmd/cli/cmd/trustcenternda"
	_ "github.com/theopenlane/core/cmd/cli/cmd/trustcentersubprocessors"
	_ "github.com/theopenlane/core/cmd/cli/cmd/trustcenterwatermarkconfig"
	_ "github.com/theopenlane/core/cmd/cli/cmd/user"
	_ "github.com/theopenlane/core/cmd/cli/cmd/usersetting"
	_ "github.com/theopenlane/core/cmd/cli/cmd/version"

	// history commands
	_ "github.com/theopenlane/core/cmd/cli/cmd/controlhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/controlimplementationhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/controlobjectivehistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/documentdatahistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/entityhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/entitytypehistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/evidencehistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/filehistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/grouphistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/groupmembershiphistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/groupsettinghistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/hushhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/integrationhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/internalpolicyhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/mappedcontrolhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/narrativehistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/organizationhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/organizationsettinghistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/orgmembershiphistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/procedurehistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/programhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/riskhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/standardhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/subcontrolhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/taskhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/templatehistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/userhistory"
	_ "github.com/theopenlane/core/cmd/cli/cmd/usersettinghistory"
)

func main() {
	core.Execute()
}
