all: true
dir: ../../mocks
filename: mocks_provider.go
force-file-write: true
formatter: goimports
log-level: info
pkgname: mocks
recursive: false
template: testify
packages:
  github.com/theopenlane/shared/objects/storage/types:
    config:
      all: true
