mutation CreateBulkCSVDirectoryAccount ($input: Upload!) {
	createBulkCSVDirectoryAccount(input: $input) {
		directoryAccounts {
			accountType
			addedAt
			avatarLocalFileID
			avatarRemoteURL
			avatarUpdatedAt
			canonicalEmail
			createdAt
			createdBy
			department
			directoryName
			displayID
			displayName
			emailAliases
			environmentID
			environmentName
			externalID
			familyName
			givenName
			id
			identityHolderID
			integrationID
			integrationRunID
			jobTitle
			lastSeenIP
			managedBy
			metadata
			mfaState
			observedAt
			organizationUnit
			ownerID
			phoneNumber
			platformID
			primarySource
			profile
			rawProfileFileID
			removedAt
			scopeID
			scopeName
			secondaryKey
			sourceDefinitionID
			sourceDefinitionVersion
			sourceInstanceID
			sourceVersion
			status
			tags
			updatedAt
			updatedBy
			updatedByImpersonator
		}
	}
}
mutation CreateBulkDirectoryAccount ($input: [CreateDirectoryAccountInput!]) {
	createBulkDirectoryAccount(input: $input) {
		directoryAccounts {
			accountType
			addedAt
			avatarLocalFileID
			avatarRemoteURL
			avatarUpdatedAt
			canonicalEmail
			createdAt
			createdBy
			department
			directoryName
			displayID
			displayName
			emailAliases
			environmentID
			environmentName
			externalID
			familyName
			givenName
			id
			identityHolderID
			integrationID
			integrationRunID
			jobTitle
			lastSeenIP
			managedBy
			metadata
			mfaState
			observedAt
			organizationUnit
			ownerID
			phoneNumber
			platformID
			primarySource
			profile
			rawProfileFileID
			removedAt
			scopeID
			scopeName
			secondaryKey
			sourceDefinitionID
			sourceDefinitionVersion
			sourceInstanceID
			sourceVersion
			status
			tags
			updatedAt
			updatedBy
			updatedByImpersonator
		}
	}
}
mutation CreateDirectoryAccount ($input: CreateDirectoryAccountInput!) {
	createDirectoryAccount(input: $input) {
		directoryAccount {
			accountType
			addedAt
			avatarLocalFileID
			avatarRemoteURL
			avatarUpdatedAt
			canonicalEmail
			createdAt
			createdBy
			department
			directoryName
			displayID
			displayName
			emailAliases
			environmentID
			environmentName
			externalID
			familyName
			givenName
			id
			identityHolderID
			integrationID
			integrationRunID
			jobTitle
			lastSeenIP
			managedBy
			metadata
			mfaState
			observedAt
			organizationUnit
			ownerID
			phoneNumber
			platformID
			primarySource
			profile
			rawProfileFileID
			removedAt
			scopeID
			scopeName
			secondaryKey
			sourceDefinitionID
			sourceDefinitionVersion
			sourceInstanceID
			sourceVersion
			status
			tags
			updatedAt
			updatedBy
			updatedByImpersonator
		}
	}
}
mutation DeleteDirectoryAccount ($deleteDirectoryAccountId: ID!) {
	deleteDirectoryAccount(id: $deleteDirectoryAccountId) {
		deletedID
	}
}
query GetAllDirectoryAccounts {
	directoryAccounts {
		totalCount
		pageInfo {
			startCursor
			endCursor
			hasPreviousPage
			hasNextPage
		}
		edges {
			node {
				accountType
				canonicalEmail
				createdAt
				createdBy
				department
				displayID
				displayName
				externalID
				familyName
				givenName
				id
				integrationID
				jobTitle
				lastSeenIP
				mfaState
				observedAt
				organizationUnit
				ownerID
				profile
				rawProfileFileID
				secondaryKey
				sourceVersion
				status
				tags
				updatedAt
				updatedBy
			}
		}
	}
}
query GetDirectoryAccountByID ($directoryAccountId: ID!) {
	directoryAccount(id: $directoryAccountId) {
		accountType
		addedAt
		avatarLocalFileID
		avatarRemoteURL
		avatarUpdatedAt
		canonicalEmail
		createdAt
		createdBy
		department
		directoryName
		displayID
		displayName
		emailAliases
		environmentID
		environmentName
		externalID
		familyName
		givenName
		id
		identityHolderID
		integrationID
		integrationRunID
		jobTitle
		lastSeenIP
		managedBy
		metadata
		mfaState
		observedAt
		organizationUnit
		ownerID
		phoneNumber
		platformID
		primarySource
		profile
		rawProfileFileID
		removedAt
		scopeID
		scopeName
		secondaryKey
		sourceDefinitionID
		sourceDefinitionVersion
		sourceInstanceID
		sourceVersion
		status
		tags
		updatedAt
		updatedBy
		updatedByImpersonator
	}
}
query GetDirectoryAccounts ($first: Int, $last: Int, $where: DirectoryAccountWhereInput) {
	directoryAccounts(first: $first, last: $last, where: $where) {
		totalCount
		pageInfo {
			startCursor
			endCursor
			hasPreviousPage
			hasNextPage
		}
		edges {
			node {
				accountType
				canonicalEmail
				createdAt
				createdBy
				department
				displayID
				displayName
				externalID
				familyName
				givenName
				id
				integrationID
				jobTitle
				lastSeenIP
				mfaState
				observedAt
				organizationUnit
				ownerID
				profile
				rawProfileFileID
				secondaryKey
				sourceVersion
				status
				tags
				updatedAt
				updatedBy
			}
		}
	}
}
mutation UpdateDirectoryAccount ($updateDirectoryAccountId: ID!, $input: UpdateDirectoryAccountInput!) {
	updateDirectoryAccount(id: $updateDirectoryAccountId, input: $input) {
		directoryAccount {
			accountType
			addedAt
			avatarLocalFileID
			avatarRemoteURL
			avatarUpdatedAt
			canonicalEmail
			createdAt
			createdBy
			department
			directoryName
			displayID
			displayName
			emailAliases
			environmentID
			environmentName
			externalID
			familyName
			givenName
			id
			identityHolderID
			integrationID
			integrationRunID
			jobTitle
			lastSeenIP
			managedBy
			metadata
			mfaState
			observedAt
			organizationUnit
			ownerID
			phoneNumber
			platformID
			primarySource
			profile
			rawProfileFileID
			removedAt
			scopeID
			scopeName
			secondaryKey
			sourceDefinitionID
			sourceDefinitionVersion
			sourceInstanceID
			sourceVersion
			status
			tags
			updatedAt
			updatedBy
			updatedByImpersonator
		}
	}
}
